### ISSUE TITLE
GUI Customization for in game

### ISSUE THREAD

**Issue by ToXiCHaZe541** [CraftingStore/Suggestions#10]
Its quite frustrating to not be able to customize the in game GUI because it just looks bad with default formatting.

I know this isnt Minecraft Market (this service is better) but Minecraft Market had a nice system where you could format the text using color codes like in game on the in game description box on the website. It also let you add line breaks in the lore of items by using line breaks in the in game description box per item on the website. Also it allowed us to change the formatting to the GUI container name in game as well. So instead of it saying CraftingStore at the top we could change that to whatever we wanted and color it how we wanted as well. Also it would be nice to add a back button to the bottom row of the GUI to allow people to click on a category or item and be able to go back for easier navigation. If you could make the item of the go back button customizable via config that would be nice to. Like allow us to change the lore of it along with the type of item

**Comment by Tim-NL** [comment]
Hello,

It is now possible to change all of the above, for all items in the inventory.

-Tim
