### ISSUE TITLE
Writen Sale instead of variable

### ISSUE THREAD

**Issue by Predavanje** [CraftingStore/Suggestions#103]
When you are creating new variable, under name it says "Name for your sale" but you are creating new variable, see picture for more info.
![screenshot from 2019-01-11 18-08-47](https://user-images.githubusercontent.com/46409712/51048771-364c6a00-15cc-11e9-9b69-f1f72d3ad9eb.png)

**Comment by Tim-NL** [comment]
Thank you!

The typo has been fixed.

-Tim
