### ISSUE TITLE
Display date on payments

### ISSUE THREAD

**Issue by M4T14SG4M3R** [CraftingStore/Suggestions#105]
**Is your feature request related to a problem? Please describe.**
The store doesn't display the date of a payment on the payments module
**Describe the solution you'd like**
Add something like {{ payment.date }} to the templates and it should say like "Today 12:14" "Yesterday 14:21" "Jan 8 15:13"

**Comment by Tim-NL** [comment]
Hello,

The payments array has a "created_at" within it. You can call it like: {{ payment.created_at }} in the loop. 

-Tim

**Comment by M4T14SG4M3R** [comment]
It is not working... you said the same in the support request, and you said that if it doesn't work i need to create an issue on github and now you are replying the same
![image](https://user-images.githubusercontent.com/16471265/51807435-6ac75380-2265-11e9-9183-37b63d96ae5f.png)
![image](https://user-images.githubusercontent.com/16471265/51807437-731f8e80-2265-11e9-949a-080e3fdefc3d.png)

**Comment by Tim-NL** [comment]
Sorry,
I read through the issues here, and thought to myself; This is already in there. 

Please, ignore the last reply. 

-Tim

**Comment by Tim-NL** [comment]
We added "dateHuman".

You can now do payment.dateHuman.

-Tim

**Comment by M4T14SG4M3R** [comment]
It doesn't show up like i was asking in the first message, it should display something like
"Today 15:11"
"Yesterday 12:41"
"Jan. 24th, 12:00"

It is displaying the entire name on the month and showing the year, it is displaying today's payments as
"January 28th, 2019"
"January 27th, 2019"

**Comment by Tim-NL** [comment]
This is correct.

We cannot show it in the format you describe, as this would require us to update all stores every day. 
The current system caches all page content until you upload something new or make any change. 

It is not possible to support the requested format without changing the whole system, and that is not something we are going to do for something like this. 

-Tim
