### ISSUE TITLE
All coupons worth $1

### ISSUE THREAD

**Issue by Zenya4** [CraftingStore/Suggestions#106]
Coupons of any value have the worth of $1 when used by customers. I have tried creating a new coupon and the same error occurs. It would be really appreciated if this can be fixed. 

http://prntscr.com/m43t0n 
http://prntscr.com/m43tei

How to reproduce:
1. Create a coupon worth $10 (for example)
2. Use it on any package
3. It becomes worth $1

**Comment by Zenya4** [comment]
Apparently, it has been resolved recently. Closed.

**Comment by Tim-NL** [comment]
This issue has indeed been fixed already, thanks anyways for creating it! 

-Tim
