### ISSUE TITLE
Add prerequisites to purchase an item

### ISSUE THREAD

**Issue by Workinq** [CraftingStore/Suggestions#109]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
Let's say you have a server which offers ranks to other players which they can purchase from the web-store. I think it would be quite useful to add a feature (when adding new packages) which could be called: "Prerequisites". What this does is check if whoever is buying a package has bought another required package before.

An example would be this:
- User wants to buy first rank called "Rank 1". Purchase goes through and "Rank 1" is given to the user.
- User now wants to buy "Rank 2" so he buys a rank upgrade from "Rank 1" to "Rank 2" since he already purchased "Rank 1" before.
- If the user hasn't purchased "Rank 1" before then he wouldn't be allowed to buy "Rank 1" to "Rank 2" upgrade. But if he already purchased "Rank 1" before then the purchase is successful.

**Additional context**
No additional context.

**Comment by Tim-NL** [comment]
Hello,

The described feature is already present in the system, you can find it at the package editor (tab: "Requirements"). 

-Tim
