### ISSUE TITLE
Please release a full API that allows for a custom GUI that shows real-time prices and links

### ISSUE THREAD

**Issue by lowkeyHero** [CraftingStore/Suggestions#110]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by lowkeyHero** [comment]
The stock GUI is ok, but we have a custom plugin that uses buycraft's api -- which is full and robust.  Please consider releasing a full api.

**Comment by Tim-NL** [comment]
Hi,

You are talking about "real-time" prices, are you going to do a request every time the user enters a specific command to open the GUI? 

-Tim

**Comment by lowkeyHero** [comment]
I guess i would say to look at what buycraft includes in their api and match that.  It allows for a lot of connectivity between plugins and the server store.

**Comment by Tim-NL** [comment]
Hello,

I understand how a REST API should function, but building it takes a lot of time, so it would be lost time if you cannot use it the way you intended. 

Are you going to pull data down from the API every time a user enters a specific command? As this would be easy to abuse, and our system might even see that as a dos attack to our API endpoint.

-Tim

**Comment by lowkeyHero** [comment]
My dev said the following: "We'd want an API similar to Buycraft, but I can cache it so it doesn't request it every time they open the store"

some of the features we like about buycraft's API:
- it allows us to generate a clickable web address per package that takes a player to the store
- connects in-game coupon plugins to the store
- same for gift cards generated in-game
- allows us to db purchase history and use it in custom player stats
- allows for ongoing rewards for donators rather than just at the time of purchase
- the in-game GUI remains current to the store but is fully customizable
- our data caching allows us to verify purchases and time of delivery to a uuid and ip address in-game which allows us added protection against chargebacks.

We aren't looking to take advantage or potentially put your system at risk, there are just a lot of the purchase events and data that protects us in the transactions and allows for more customized player experiences.

**Comment by Tim-NL** [comment]
Hi,
We're going through old issues, and we are closing them as we move some to our internal tracker.

We are slowly releasing our beta API; https://docs.api.craftingstore.net/

It does not yet include all requested features here, but we are working on getting more in there. 

I'll close this issue, as we are slowly building out our public API on our internal tracker.

-Tim
