### ISSUE TITLE
[Suggestion] Add exporting options

### ISSUE THREAD

**Issue by TheIronMinerLv** [CraftingStore/Suggestions#111]
Hello,

Currently given "statistics" on control panel are really really poor. It is almost impossible to use it to make precise data statistics as they lack a lot of options compared to, for example, Buycraft's/Tebex's statistics.

I know it is not that easy to add such detailed system, , but **PLEASE** - at least **add possibility of exporting payments with as much info as possible** (nick, date, package, gateway, price, etc.), with possibility of choosing date range (for example, in a .csv). With that I and probably many others would be able to make statistics as we need ourselves.

#makeCraftingStoreBetterThanEver

**Comment by Tim-NL** [comment]
Hello,

We added the exporting feature to the system, you can find it under the "payments" section. 

~Tim

**Comment by TheIronMinerLv** [comment]
Amazing! Thanks a lot :)
