### ISSUE TITLE
Allow multiple coupon codes at checkout

### ISSUE THREAD

**Issue by LiamBinLaden** [CraftingStore/Suggestions#112]
Due to my server having a lot of promotional offers, players are wanting to put multiple codes in at checkout. However, every-time they put in more than one coupon code, the other is removed. It would be cool to have an option on every coupon code to say if its "stackable", true/false.

**Comment by Tim-NL** [comment]
Hello,

We will decline this request for now. You can already stack coupons on top of sales, and adding another extra layer can cause confusion. 

-Tim
