### ISSUE TITLE
Coupons add incorrectly to Donation Goal module

### ISSUE THREAD

**Issue by Zenya4** [CraftingStore/Suggestions#116]
Describe the bug:
When a user uses a coupon to purchase items, the full amount is still added to the donation goal module instead of the discounted value. This may cause it to be misleading to players as it will seem that the server is earning a lot that month, but even if coupons (amount) are used

Steps to reproduce the behaviour:
1. Create a new coupon [$5]
2. Create a new package (Cost $10)
3. Enable the "Donation Goal" module in the webstore and set it to any value ($100)
3. Use the coupon on the package to buy it

Expected behaviour:
The discounted value of the item purchased should count to the donation goal module, and not the full price of the item. In the example above, donation goal shows $10/$100 although the profit is only $5. It should be $5/$100

Platform:
Website

**Comment by Zenya4** [comment]
Seeing that this is an error, I think the same may apply to:

- Sales
- Coupons (percentage)
- Giftcards

**Comment by Tim-NL** [comment]
Hello,

I just tested your issue with; Sales, coupons, and gift cards. I also checked the code responsible for this.

I can not reproduce the issue on our end, the "Donation goal" module shows the correct (discounted) price every time. 

-Tim
