### ISSUE TITLE
Error on sponge

### ISSUE THREAD

**Issue by infamyreloaded** [CraftingStore/Suggestions#118]
**Describe the bug**
The plugin doesn't load/work. It shows green in /sponge plugins (like it loaded), but no commands work.
The error in the console looks like:
https://pastebin.com/fcys11ZJ

**To Reproduce**
1. Download off the website
2. Upload to server
3. Restart server

**Expected behavior**
There not to be an error.

**Platform**
Sponge server:
    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-70763aa8
    Sponge: 1.12.2-7.1.4
    SpongeForge: 1.12.2-2768-7.1.4
    Minecraft Forge: 14.23.5.2807

Running on ubuntu 16.04

**Comment by thijsa** [comment]
I have created a new build which should resolve the issue. You can download it from here: https://cdn.cloudprotected.net/craftingstore/dl/CraftingStoreBeta.jar.
If the issue has been resolved for you, we will update it on the SpigotMC.

**Comment by Tim-NL** [comment]
We confirmed that the plugin works on all supported platform, and this test build has been published to the production environment. You can use the link provided in thijsa's comment, or use the normal download link.

-Tim
