### ISSUE TITLE
Coupons | Max Uses

### ISSUE THREAD

**Issue by Tigerpanzer02** [CraftingStore/Suggestions#12]
**Describe the bug**
Coupons
It is ignoring the max uses.
I can use it more then 1 time when I set the max uses to 1

**To Reproduce**
1. Go to 'https://www.craftingstore.net/admin/coupons'
2. Click on 'New'
3. Do the Steps for creating Coupon
4. After use see that the max uses are one and the uses goes over it.

**Expected behavior**
That you can´t use the Coupon after the limit of Max Uses

**Platform**
CraftingStore Website | Coupons

**Comment by Tim-NL** [comment]
The fix for this issue has been implemented, thank you for pointing this out.

~Tim
