### ISSUE TITLE
Basket Minimum

### ISSUE THREAD

**Issue by plasticono** [CraftingStore/Suggestions#120]
Since payment providers such as paypal take a percentage of the money every purchase, it is important that PayPal doesn't take ALL of the money from the purchase.

It would be helpful to set a minimum purchase amount. Ex. You can't make a purchase unless your basket is worth at least $1.00

**Comment by TheMonDon** [comment]
I think this "could" be a useful feature but I also think you could just make your packages worth more.

**Comment by Tim-NL** [comment]
Hi,

Thanks for the suggestion! You can now configure the minimal basket value from [ Settings -> Webstore ].

-Tim
