### ISSUE TITLE
Coupon creation on certain Packages

### ISSUE THREAD

**Issue by FruitLabCBR** [CraftingStore/Suggestions#122]
Hey :)

Maybe you guys can add a Feature to create and send a Coupon of a certain Vaulue if someone buys like a lifetime Rank or something else

Person buys a Lifetime Rang for 50$ -> He gets an email with a 10$ Coupon Code

**Comment by Tim-NL** [comment]
Hi,

Thanks for your suggestion!

We've implemented the feature, but not with coupons, but with gift-cards.

You can configure these from the package -> advanced settings. We decided to use gift-cards because they don't have issues with things like expiration dates and such.

-Tim
