### ISSUE TITLE
Add  child commands ingame

### ISSUE THREAD

**Issue by lowkeyHero** [CraftingStore/Suggestions#123]
I was hoping that a future version of the plugin may allow things such as /buy [storename] (package name)

**Comment by Tim-NL** [comment]
Hello,

Can you please share with us, the way you want to make the plugin act when; 
- There are two items with the same name ("VIP" in one category and one in another).
- What should the plugin do when you enter this command. 

-Tim

**Comment by lowkeyHero** [comment]
Basically, it would allow you to have in-game items that bring up subcategories or links to packages when clicked.  Honestly, it may be more for categories or subcategories.  or if I wanted to have a way to do a custom GUI I could make one with a different plugin and still get the links or open up subcategories.  

in the case of 2 items having the same name it should work more like this:
To open a specific gui screen- /buy [SERVER_NAME] {CATEGORY_NAME} (SUBCATEGORY) --
to get a link to a package- /buy [SERVER_NAME] {CATEGORY_NAME} (SUBCATEGORY) PACKAGE

the trees should be unique enough to not have 2 identical items, or possibly get the PACKAGE id from the website i.e. ...admin/packages/**64231**/ 
(if the number code is unique)

**Comment by lowkeyHero** [comment]
Are you fucking kidding closing this with no response....

**Comment by Tim-NL** [comment]
Hi, 

Please read my response in #124. 

-Tim

**Comment by lowkeyHero** [comment]
it's a different issue kid

**Comment by lowkeyHero** [comment]
subcommands are controlled wholely by your plugin

**Comment by lowkeyHero** [comment]
You arent even gonna try to answer this question about **your** plugin?

**Comment by Tim-NL** [comment]
```you are a fucking trash dev

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.
```

Please use another platform, you are being very disrespectful. 

You are requesting something (#124) that is simply not possible without creating a plugin for 1.8 only. About 80% of our plugin traffic is coming from 1.13 servers. 

I wish you a very nice day, I closed both issues.

**Comment by lowkeyHero** [comment]
ok, so ignore #124 and answer the question asked here

**Comment by Tim-NL** [comment]
Sure,

It might be possible to support such commands, I'll re-open the issue and add it to the suggestions list. 

Please note that it will only be on the list, this is not the same as an "Accepted" mark, and we might still reject the feature request afterward, for any reason. 

-Tim

**Comment by lowkeyHero** [comment]
cheers

**Comment by Tim-NL** [comment]
We are further in the development of CraftingStore and decided that this is out of scope for the project. 

-Tim
