### ISSUE TITLE
Not all item names supported

### ISSUE THREAD

**Issue by lowkeyHero** [CraftingStore/Suggestions#124]
CLAY_BRICKS 
NETHER_BRICK_ITEM

possibly more, but I found those

**Comment by lowkeyHero** [comment]
PaperSpigot 1.8.8

**Comment by Tim-NL** [comment]
Can you please share the exact version, thanks in advance. 

-Tim

**Comment by lowkeyHero** [comment]
also I cant use ITEM_NAME:DAMAGE for different items

**Comment by lowkeyHero** [comment]
version of the plugin? or Paper?

**Comment by Tim-NL** [comment]
Paper.

-Tim

**Comment by lowkeyHero** [comment]
CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by Tim-NL** [comment]
Mojang changed their block names between versions, as our plugin supports 1.7 - 1.13, we use a class to allow the blocks to still work between versions. The naming scheme might not be completely correct, as these are different across versions.

The two blocks that you mentioned, do not exist in this list, please use:
CLAY_BRICK
NETHER_BRICK

Giving damage to the item is not possible at this moment. 

Full list: https://paste.projectdev.org/epahoxerih.stylus

-Tim

**Comment by lowkeyHero** [comment]
CLAY_BRICK comes up with a BRICK block

**Comment by Tim-NL** [comment]
This might be correct, as Mojang changed their block naming schema across versions.

I'll quote some messages from the 1.13 Spigot release; 

```he 1.13 API is largely not backwards compatible with older versions. This means that if your plugin targets native 1.13 support it will NOT be able to run on < 1.13. Whilst forwards compatibility has always been a design goal of Bukkit, backwards compatibility has not been.```

```All Materials have been renamed to match the names used in Vanilla. The old Materials have been prefixed with LEGACY_ and can only be validly accessed by plugins targeting previous API versions. Plugins converting data from old versions should use the new boolean parameter in Material.getMaterial and Material.matchMaterial to return the new Material with the closest possible mapping. Note however that there is not a 1:1 mapping between all old and all new Materials so correct conversion may not be possible.```

**Comment by lowkeyHero** [comment]
* doesn't support the most popular and widely played version of Minecraft*

**Comment by Tim-NL** [comment]
Please read my replies. 

We try to support 1.7 til 1.13, but some blocks do not work as there is not a 1:1 conversation for them. 

I'll close both issues, our V1 plugin is open-source if you'd like you can fork it and make it a 1.8 only plugin. 

Again: We try to support all versions, but block names changed over versions. 

-Tim

**Comment by lowkeyHero** [comment]
you are a fucking trash dev

**Comment by thijsa** [comment]
Hey,

The clay block is already in the list of items, but the nether brick does not. I have added the nether brick item in the next version.
Names:
Clay block: CLAY
Nether brick block: NETHER_BRICK_ITEM (Will be added in the version 2.0.6 of the CraftingStore plugin)

**Comment by Tim-NL** [comment]
The next version has been uploaded to our own storage server. We will update it on Spigot & Sponge later today;
http://cdn.cloudprotected.net/craftingstore/dl/CraftingStore.jar

-Tim
