### ISSUE TITLE
Module | Packages

### ISSUE THREAD

**Issue by MinecollYT** [CraftingStore/Suggestions#126]
**Feature request**

A new module:
       Packages.

Useful for something like "A new limited Rank:". There should be a picture of the price, add to cart and the name.
![rank_module](https://user-images.githubusercontent.com/43142792/52715368-999b3480-2f9c-11e9-9f9c-788dab870811.png)

**Comment by Tim-NL** [comment]
Duplicated with #73

Thanks for the request, I'll close the issue, as there is another issue with this feature request. 

-Tim
