### ISSUE TITLE
[Feature Request] Re-Send all Payments/Commands

### ISSUE THREAD

**Issue by PokeHub** [CraftingStore/Suggestions#127]
**Is your feature request related to a problem? Please describe.**
I can't switch over from tebex until I can re send all purchase commands. Our server restarts every 2 months completely, and deletes all data but the world.

**Describe the solution you'd like**
A Button to re-send all the purchase commands on player login

**Comment by TheMonDon** [comment]
This has been implemented now.

**Comment by Tim-NL** [comment]
This has indeed been implemented.

-Tim
