### ISSUE TITLE
Ability to Resend Commands

### ISSUE THREAD

**Issue by Anaerrobe** [CraftingStore/Suggestions#13]
**Is your feature request related to a problem? Please describe.**
No, it isn't.

**Describe the solution you'd like**
Add the possibility to resend all commands so for example players donated then after a few months I reset my server and all the donors lost what they bought from the store so then I can go to the resend commands button and click it to resend all the executed commands with also specifying between what date to what date were the commands I want to resend executed.

**Additional context**
Sadly no pictures because this was a feature of MinecraftMarket and now they shut down.

**Comment by Tim-NL** [comment]
We can allow re-sending commands, but not all of them, for lage servers this would result in a lot off stress on the servers. 

This might be something for the future. I'll close the issue for now.

~Tim
