### ISSUE TITLE
Clickable images, titles

### ISSUE THREAD

**Issue by wumptrax** [CraftingStore/Suggestions#130]
Option to make product images and product titles clickable would be nice! :)
![txmamoq](https://user-images.githubusercontent.com/39104996/53169027-6aa84280-35dc-11e9-95c7-903eee42a7e4.png)

**Comment by Tim-NL** [comment]
Hello,

You can modify the template on our premium plans to get such features. We won't implement these kinds of features on the general platform. 

-Tim
