### ISSUE TITLE
Giftcards / Coupons package

### ISSUE THREAD

**Issue by timhed** [CraftingStore/Suggestions#131]
possibility for customers to buy  **coupons** and **giftcards**

**Comment by TheMonDon** [comment]
I think this would be a nice feature. People would be able to buy a giftcard with X balance and use that as a means of paying for their package(s) in different ways, say once with paypal and the rest with a giftcard purchased with something else.

**Comment by Tim-NL** [comment]
Hi,

It is now possible to buy gift cards, to configure it, take a look at this article; https://help.craftingstore.net/books/premium-features/page/selling-gift-cards-on-your-store

-Tim
