### ISSUE TITLE
Products to download

### ISSUE THREAD

**Issue by MinecollYT** [CraftingStore/Suggestions#133]
A new compartment like the commands, the name should be "files" or "download". In that compartment, we can upload Files or Folders. It's useful when the Owner wants to sell plugins or something else. In the success page should be a "download" button. 

btw. sry for bad English...

**Comment by Tim-NL** [comment]
Hello,

CrafingStore is meant to sell in-game ranks or in-game items, providing custom services, like plugin downloads, is not something a normal server would do. As such, it's out-of-scope for the time being. 

Rejected.

-Tim
