### ISSUE TITLE
[Feature] Discord Moudle

### ISSUE THREAD

**Issue by TaZeDeveloper** [CraftingStore/Suggestions#134]
**Is your feature request related to a problem? Please describe.**
Since we for some reason cant add a widget into the html because it then deletes it after.

**Describe the solution you'd like**
I think a discord widget would be pretty neat or maybe just let us paste a widget into the homepage

**Additional context**
![screenshot 20](https://user-images.githubusercontent.com/30067965/53369690-aed07580-3943-11e9-9ba2-e466d7542229.png)

**Comment by Tim-NL** [comment]
Hello,

Thanks for the suggestion. 

As for the box; The box is only for plain text, and basic style. We do not allow script tags or other special tags, as this would allow free stores to remove the branding or make theme changes. 

-Tim

**Comment by Tim-NL** [comment]
We added the Discord module, you can enable it through the modules pages. 

-Tim
