### ISSUE TITLE
Just a small fix about the webpage title

### ISSUE THREAD

**Issue by TaZeDeveloper** [CraftingStore/Suggestions#137]
**Describe the bug**
I mean its not really a bug but just needs tweaking it
The homepage says index what looks a little bit ugly in my opinion

**To Reproduce**
1. Go to the main page of the store

**Expected behavior**
idk just change it to nothing or just something that looks better

**Screenshots**
![screenshot 22](https://user-images.githubusercontent.com/30067965/53693795-08e69600-3d9d-11e9-8e8a-fbfba4619430.png)

**Platform**
Craftingstore Website

**Additional context**
Idk if its just me being stupid like they might be a option but i looked through stuff didn't see anything

**Comment by Tim-NL** [comment]
Hello,

You can change the title by using the template editor on any of our premium plans. We do not offer such customizability by default. 

-Tim
