### ISSUE TITLE
Able to change Quantity.

### ISSUE THREAD

**Issue by jjj700** [CraftingStore/Suggestions#14]
**Is your feature request related to a problem? Please describe.**
make it so players can change how much of the item they want in the checkout.

**Describe the solution you'd like**
https://gyazo.com/b83f7ff98a95127b97b811df748fa513
https://gyazo.com/5f48fbebaaa4aee724efcfe790fac4f3

**Additional context**
n/a

**Comment by TheIronMinerLv** [comment]
Agree, this is needed and can make more sells as player's could purchase on bulk instead of buying one by one (need more time to spend = gives up, less revenue)

**Comment by Tim-NL** [comment]
Hi, 

Sorry for the delay on this issue. 

The feature has been implemented on the default template. 
https://github.com/CraftingStore/Templates/tree/master/default

If you're using a custom template, refer to these changes:
https://github.com/CraftingStore/Templates/commit/c14c992e102dbf18183b333bdeacefda29b71a14
https://github.com/CraftingStore/Templates/commit/7cf87029a6f8d398805cc7ce6525a3a46cd43778

The user will have the ability to enter a quantity between 1-100. 

-Tim
