### ISSUE TITLE
Uploading custom HTML/CSS

### ISSUE THREAD

**Issue by TheMonDon** [CraftingStore/Suggestions#140]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I think that being able to upload our own HTML/CSS would be a good feature, seems simple but copying-pasting is also simple, for uploading templates. Just an idea I think might be easy to implement

**Additional context**
None

**Comment by Tim-NL** [comment]
Hello,

The HTML/CSS files are stored in our database, they are not "real" .html files. As such, we cannot offer this.

-Tim
