### ISSUE TITLE
Access admin panel from own domain

### ISSUE THREAD

**Issue by TheMonDon** [CraftingStore/Suggestions#142]
**Is your feature request related to a problem? Please describe.**
No problem.

**Describe the solution you'd like**
I think it would be a useful feature to be able to access the admin panel from our domain. 
Like: store.crafters-island.com/admin vs craftingstore.net/admin

**Additional context**
Possibly just redirect to craftingstore.net/admin

**Comment by Tim-NL** [comment]
Hello,

The security risks do not way up against the possible gain this will bring. I will decline the issue, however, it is possible to create a redirect by simply creating a redirect file on your own web-hosting service. 

-Tim
