### ISSUE TITLE
[Feature Request] Option to disable quantity

### ISSUE THREAD

**Issue by TheMonDon** [CraftingStore/Suggestions#144]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Disable the option to change the quantity of a specific package.

**Additional context**
A feature found in Tebex.

**Comment by Tim-NL** [comment]
Hi,

Thanks for your suggestions!

It is now possible to disable the quantity box from [ Package -> Advanced tab ]. 

Please see this new article, it shows what you'll need to change; https://help.craftingstore.net/books/others/page/custom-template-new-basket-format.

-Tim
