### ISSUE TITLE
[Feature Request] Disable gift cards on specific packages

### ISSUE THREAD

**Issue by TheMonDon** [CraftingStore/Suggestions#145]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Do not allow gift cards to be used to purchase a specific package.

**Additional context**
Another feature from Tebex.

**Comment by bgbuddyboy** [comment]
Bump!

**Comment by Tim-NL** [comment]
Hi,

Would you be able to elaborate on this? What behavior are you looking for?

Do you want the gift-card box to be disabled when a package that has gift-cards disabled is in there, or something else?

-Tim

**Comment by Tim-NL** [comment]
Hi,

We've implemented the ability for gift-cards to be limited to specific packages some time ago. I think that also resolves this issue.

-Tim
