### ISSUE TITLE
Website says support for many games but only a minecraft donation store

### ISSUE THREAD

**Issue by TheMonDon** [CraftingStore/Suggestions#146]
**Describe the bug**
Website has a"feature" saying: "Many games
We support multiple games, including: Minecraft, HurtWorld and many others!" But 

**To Reproduce**
1. Go to 'https://craftingstore.net/'
2. Click on 'N/A'
3. Scroll down to 'Many Games'

**Platform**
Crafting store Homepage

**Comment by Tim-NL** [comment]
Hello,

We are still working on the other games, thanks for the report, we will correct the message on the homepage. 

-Tim
