### ISSUE TITLE
Server Versions FAQ is for Server Platforms

### ISSUE THREAD

**Issue by TheMonDon** [CraftingStore/Suggestions#148]
**Describe the bug**
The help page for Supported server versions is really a help page for Supported server platforms.

**To Reproduce**
1. Go to 'https://help.craftingstore.net/books/general/page/supported-server-versions'
2. See error

**Expected behavior**
Expected to be able to know what versions of Minecraft are supported, like the spigot page. Example: 1.7-1.13.2

**Platform**
Help.craftingstore.net

**Comment by Tim-NL** [comment]
Hello,

The name has been updated. 

-Tim
