### ISSUE TITLE
"Click" link missing on "Set up SSL certificates for your store"

### ISSUE THREAD

**Issue by TheMonDon** [CraftingStore/Suggestions#149]
**Describe the bug**
"Click" link missing on "Set up SSL certificates for your store"

**To Reproduce**
1. Go to 'https://help.craftingstore.net/books/general/page/set-up-ssl-certificates-for-your-store'
2. See error

**Expected behavior**
Able to click on the *click" area

**Platform**
help.craftingstore.net

**Comment by Tim-NL** [comment]
Hello,

Thank you, the problem has been corrected.

Kind regards,
Tim
