### ISSUE TITLE
"Crafty"  type a message is in dutch

### ISSUE THREAD

**Issue by TheMonDon** [CraftingStore/Suggestions#150]
**Describe the bug**
"crafty" AI on the homepage is all in English except the "type a message..." text

**To Reproduce**
1. Go to 'https://craftingstore.net/'
2. Click on '?'
3. See error

**Expected behavior**
Had expected the full thing to be in English.

**Screenshots**
![image](https://user-images.githubusercontent.com/11539895/54860784-28fadc80-4ced-11e9-9fcf-5e8e29fdabc5.png)

**Platform**
Crafting store website AI Bot

**Comment by Tim-NL** [comment]
Hello,

Thanks! The message will be resolved at the next deployment. 

-Tim
