### ISSUE TITLE
[Feature Request] Have "Crafty" store messages for set period of time

### ISSUE THREAD

**Issue by TheMonDon** [CraftingStore/Suggestions#151]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I think instead of "Crafty" re-starting every time you close it, it should save your messages for the past few minutes, ex 10 minutes or so. I believe this is a good idea because it takes like 10 seconds every time you open it

**Comment by Tim-NL** [comment]
Hello,

This is not something we can change ourselves, due to the way the system is implemented. I'll close the suggestion. 

-Tim
