### ISSUE TITLE
"Crafty" scroll function of text scrolls main page

### ISSUE THREAD

**Issue by TheMonDon** [CraftingStore/Suggestions#152]
**Describe the bug**
The "Crafty" AI menu has a scrollbar if you have a few messages in it if you scroll down to the bottom and continue using the scroll wheel, the main website will scroll down. After this, you need to click on the text inside the AI again to be able to scroll. 

**Platform**
Crafting store main page AI, "Crafty"

**Comment by Tim-NL** [comment]
Hello,

The described behavior is "expected behavior", we do not want to "block" the page from scrolling when the store owner is using the chatbot. 

-Tim
