### ISSUE TITLE
Accidental web store is "waiting remove approval"

### ISSUE THREAD

**Issue by TheMonDon** [CraftingStore/Suggestions#153]
**Describe the bug**
I made an accidental webstore, I don't know how long ago this was, but it's still "waiting remove approval"

**Expected behavior**
I expected to be able to instantly delete the webstore.

**Screenshots**
![image](https://user-images.githubusercontent.com/11539895/54860964-e1298480-4cef-11e9-8dd1-d510f165b1cb.png)

**Platform**
Craftingstore Dashboard

**Comment by Tim-NL** [comment]
Hello,

Clicking the remove button will E-mail you with a confirmation, it will not remove your store directly because that would be a huge risk. 

If you did not receive the E-mail, you might want to check your spam folder or create a ticket. 

-Tim

**Comment by TheMonDon** [comment]
> Hello,
> 
> Clicking the remove button will E-mail you with a confirmation, it will not remove your store directly because that would be a huge risk.
> 
> If you did not receive the E-mail, you might want to check your spam folder or create a ticket.
> 
> -Tim

Tim, I clicked the delete button a long time ago, I dont have the email anymore if i ever did. It just says waiting remove approval and there is no way to resend the email

**Comment by Tim-NL** [comment]
In that case, you can create a support ticket, so we can look into the account. 

-Tim
