### ISSUE TITLE
Make "?" click-expandable or remove the "?" from the different pages in dashboard.

### ISSUE THREAD

**Issue by TheMonDon** [CraftingStore/Suggestions#154]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
The question mark in Servers inside the dashboard should click to expand the help message or the question mark should be removed.

**Screenshot**
![servers](https://user-images.githubusercontent.com/11539895/54861073-62cde200-4cf1-11e9-8c23-be937ea94c10.PNG)

**Comment by TheMonDon** [comment]
**Is your feature request related to a problem? Please describe.**
no]

**Describe the solution you'd like**
The question mark in Payments inside the dashboard should click to expand the help message or the question mark should be removed.

**Screenshot**
![payments](https://user-images.githubusercontent.com/11539895/54861102-b7715d00-4cf1-11e9-8ba5-50784bce5280.PNG)

**Comment by TheMonDon** [comment]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
The question mark in Team Accounts inside the dashboard should click to expand the help message or the question mark should be removed.

**Screenshot**
![teamaccounts](https://user-images.githubusercontent.com/11539895/54861189-4e8ae480-4cf3-11e9-84ed-a34eb3e268c3.PNG)

**Comment by TheMonDon** [comment]
I didn't realize this is the same way on most pages, I suggest this for all of the information things.

**Comment by Tim-NL** [comment]
The question mark is put there to show that the message is informative, the icon should not open up any menu. 

-Tim
