### ISSUE TITLE
Clicking cancel inside Payments Lookup returns to dashboard homepage

### ISSUE THREAD

**Issue by TheMonDon** [CraftingStore/Suggestions#156]
**Describe the bug**
Clicking cancel inside Payments Lookup returns to the dashboard, but clicking cancel in manual payment returns to Payments -> Manage 

**To Reproduce**
1. Go to 'https://craftingstore.net/admin/paymentlookup/create'
2. Click on 'cancel'
3. Returns to the main dashboard page

**Expected behavior**
I expected it to return to "Manage Payments"

**Platform**
Crafting store Dashboard

**Comment by Tim-NL** [comment]
Hello,

Thanks!

The change has been made and it will be put live on the next deployment. 

-Tim
