### ISSUE TITLE
Clicking cancel inside Gateways brings you to Team Accounts

### ISSUE THREAD

**Issue by TheMonDon** [CraftingStore/Suggestions#157]
**Describe the bug**
Clicking cancel inside Gateways brings you to Team Accounts

**To Reproduce**
1. Go to 'https://craftingstore.net/admin/gateways'
2. Click on '.cancel'
3. See error

**Expected behavior**
Expected to be brought back to the main dashboard
**Platform**
Crafting store website

**Comment by Tim-NL** [comment]
Hello,

Thank you, the change will be live on the next deployment. 

-Tim
