### ISSUE TITLE
[Feature Request] Knowledge base: What is payment profiles?

### ISSUE THREAD

**Issue by TheMonDon** [CraftingStore/Suggestions#158]
**Is your feature request related to a problem? Please describe.**
Kind of. I have no idea what payment profiles are, or what it does.

**Describe the solution you'd like**
I want to know what payment profiles is. I added my email and confirmed it, but not sure what that does.

**Comment by Tim-NL** [comment]
Hello,

Thank you for the request, the help item has been created. 
https://help.craftingstore.net/books/general/page/what-are-player-profiles

-Tim
