### ISSUE TITLE
[Feature Request] Timed availability for packages

### ISSUE THREAD

**Issue by TheMonDon** [CraftingStore/Suggestions#159]
**Describe the solution you'd like**
I would like to automatically have packages appear on the store, for example, a holiday so people only buy the package during that time rather than manually having to enable or disable the package, or even having to delete the package and remake it.

**Comment by lackoSK** [comment]
Bump. Need it too

**Comment by Tim-NL** [comment]
Hi!

Thanks for the suggestion.

The feature has been implemented to the Silver plan (https://help.craftingstore.net/premium-features/timed-packages (due to the need for us to check all packages continuously)).

-Tim
