### ISSUE TITLE
Key validating doesnt work 

### ISSUE THREAD

**Issue by HetIsJoey** [CraftingStore/Suggestions#16]
Error: https://paste.projectdev.org/giwuyahoji.error

**Comment by kenita3222** [comment]
I had that same error for a long time, what I had to do was talk to my host provider (anvilnode in my case) and that I 'reinstalled' the server in another ip (like hiring a new server and moving the information) and problem solved was something drastic but I had no other

**Comment by Tim-NL** [comment]
I've removed some of the checks for bad servers (known spammer IP's, etc.), those aren't required for the API endpoint, but will block soms OVH ranges for example. 

Try if the plugin will validate now. 

~Tim

**Comment by Tim-NL** [comment]
-- Issue has been resolved --
