### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Reblxtemp3rYT** [CraftingStore/Suggestions#161]
**Is your feature request related to a problem? Please describe.**
A dark mode should be added to the admin panel, this is so there is a better feel to it
**Describe the solution you'd like**

**Additional context**

**Comment by TheMonDon** [comment]
I think this is a great idea. Otherwise, maybe have custom-themes available for the control panel? That would be cool

**Comment by Tim-NL** [comment]
Hello,

Can you please supply more information, the main message is still the default, are you referring to a dark theme on the dashboard, or on the stores? 

-TIm

**Comment by TheMonDon** [comment]
> Hello,
> 
> Can you please supply more information, the main message is still the default, are you referring to a dark theme on the dashboard, or on the stores?
> 
> -TIm

I believe he is referring to the dashboard since you can already have store themes

**Comment by Tim-NL** [comment]
Closed due not receiving a response from creator. 

-Tim
