### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by Askingg** [CraftingStore/Suggestions#162]
You guys should really try and get a HTTPS licensing (I don't know if that's to correct term for it, I wouldn't know.)
I'd imagine many people are gonna be kinda against donating when it warns them that the site is insecure...
I have no idea how you do this, I've never worked with web development at all, I'm just here to make a suggestion
https://gyazo.com/437be3ed71d0fad389727405c0da2651

**Comment by Tim-NL** [comment]
Hello,

We do have a TLS certificate on our craftingstore.net domain, please add "https://" instead of "http://" in front of your domain, or enable the HTTPs redirect within the domain's settings page. 

You can change this here: https://craftingstore.net/admin/settings/domain

-Tim
