### ISSUE TITLE
Large images go off main page

### ISSUE THREAD

**Issue by TheMonDon** [CraftingStore/Suggestions#164]
**Describe the bug**
Large images take up too much space in packages - image area

**To Reproduce**
1. Go to a package
2. Click on image tab and upload large img, for example 1100 x 1100
3. see error

**Expected behavior**
Fit within the border of the main page, shrunken down

**Screenshots**
![imagecs](https://user-images.githubusercontent.com/11539895/54963834-32c45000-4f38-11e9-8060-48a17a78937e.PNG)

**Platform**
craftingstore website

**Comment by Tim-NL** [comment]
Thank you! The issue will be resolved in the next release. 

-Tim
