### ISSUE TITLE
[Feature Request] Save how far down you've scrolled after editing a package

### ISSUE THREAD

**Issue by TheMonDon** [CraftingStore/Suggestions#165]
**Describe the solution you'd like**
I have a bunch of different categories with different stuff, If I'm editing stuff that's further down the page I would like it to save my spot or close to where I was instead of needing to scroll all the way down again.

**Comment by Tim-NL** [comment]
Hello,

We cannot store how for you scrolled as this is browser behavior and it will differ for each device. This is unfortunately out of scope for CraftingStore.

-Tim
