### ISSUE TITLE
Adding to requirements of a package

### ISSUE THREAD

**Issue by Chasewhip8** [CraftingStore/Suggestions#166]
**Describe the solution you'd like**
When adding requirements to packages, we need to be able to say if the user has purchased [package1] then they cannot purchase [package2]
Also saying you can only purchase one package from a category as an option would also be a good addition alongside this.

**Additional context**
Adding requirements to package purchases

**Comment by TheMonDon** [comment]
There already are requirements to purchase packages, but not the only being able to purchase one package from category.

**Comment by Tim-NL** [comment]
The first feature is already present in the system. And the second feature (only allowing one package from the category) is currently not requested enough to be implemented.

-Tim
