### ISSUE TITLE
Option to set material data

### ISSUE THREAD

**Issue by Mizioki** [CraftingStore/Suggestions#167]
Hello, I'm coming with suggestion to add ability to set data of an item inside /buy gui.

**Comment by thijsa** [comment]
Hi,

What item are you trying to create?
We have already added some new item names so you don't have to add any material data.

**Comment by Mizioki** [comment]
I'm trying to create multiple items. I'll list some of them.
Lapis Lazuli, Purple Dye, Yellow Dye, Red Dye..., Zombie Egg, Cave Spider Egg...

**Comment by Tim-NL** [comment]
We're closing this issue.

These are all the items that you can use; https://raw.githubusercontent.com/CraftingStore/MinecraftPlugin/master/bukkit/src/main/java/net/craftingstore/bukkit/util/XMaterial.java

This combines the ID and data type.

-Tim
