### ISSUE TITLE
Support for Mobile Payments

### ISSUE THREAD

**Issue by TheSilentPro** [CraftingStore/Suggestions#168]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would really like to have an option to receive mobile payments that go straight to my mobile.
This would be really useful for people without a PayPal and such that just want an easy way to pay and receive money!

**Additional context**
/

**Comment by Tim-NL** [comment]
Hello,

We cannot send payments directly from one phone to the other, there are providers available that process mobile payments. Like: PaymentWall or PayGol. 

-Tim
