### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by ICEconchy** [CraftingStore/Suggestions#17]
**Describe the bug**
There is a spelling mistake on the category page

**To Reproduce**
1. Go to 'New category'

**Expected behavior**
No spelling mistakes

**Screenshots**
https://gyazo.com/c0b3132caa926fbf6fa96866a7f1a6a8

**Platform**
website

**Additional context**
Nothing

**Comment by Tim-NL** [comment]
Thank you! 

I just fixed the mistake.
