### ISSUE TITLE
Allow support tickets to be replied to more than once per minute or dont delete text

### ISSUE THREAD

**Issue by TheMonDon** [CraftingStore/Suggestions#170]
**Is your feature request related to a problem? Please describe.**
Sort of, if you try to reply to a support ticket before 1 minute is up it deletes all your text

**Describe the solution you'd like**
Either enable replying before 1 minute or dont delete text upon the notification

**Comment by Tim-NL** [comment]
Hello,

Can you elaborate on text remove query? We did block replies because it was spammed a lot in the past. 

~Tim

**Comment by TheMonDon** [comment]
Hi, when you type something it deletes everything you typed if you click send before the one minute

**Comment by Tim-NL** [comment]
The system will no re-post your text into the box when the time limit is not yet reached. 

~Tim
