### ISSUE TITLE
Manual payment 

### ISSUE THREAD

**Issue by Dauwks** [CraftingStore/Suggestions#171]
Hello, I would like you to add the manual payment as on Buycraft with the possibility of sub-code. It would be great especially that this function is very used in your competition and that it would not ask you too much work. I hope to see my request arrive at most.

thank you in advance

**Comment by Tim-NL** [comment]
Hello,

Can you please elaborate on your feature request? I am not exactly sure what this is referring to. 

~Tim

**Comment by Tim-NL** [comment]
-- Closed due to missing information --
