### ISSUE TITLE
Allow the user to pay what they want bug (when sale is on)

### ISSUE THREAD

**Issue by didjee2** [CraftingStore/Suggestions#175]
**Describe the bug**
The "allow the user to pay what they want" option works fine when there is no sale, but once a sale is on it, it ignores the amount the user entered and takes the default prices - % sale.
(I only tested it with % sales)

**To Reproduce**
- create a package with "allow the user to pay what they want option"
- create a sale on that package (although I created the sale on the category, might matter)
- try to enter your own price and go to checkout

**Expected behavior**
I expected the price entered by the user - 15 % (in my case of the sale), but got the original product price (not user entered price) - 15 %.

**Screenshots**
With sale on:
![image](https://user-images.githubusercontent.com/12124549/56296828-8721b080-612f-11e9-9c20-7761350ab68c.png)

With sale disabled:
![image](https://user-images.githubusercontent.com/12124549/56296995-cb14b580-612f-11e9-8801-2e64bf60b355.png)

**Platform**
CraftingStore site: https://store.centrixpvp.eu
Do note that I now just disabled the sale on this package, as it is only a gift package, for which a sale is completely useless.
However, the bug might be more annoying for other customers.

**Comment by Tim-NL** [comment]
Thanks for the report, we are currently working on completely re-doing the front-end (you won't notice this in the usage of the platform). We did encounter this issue too, alongside some other issues regarding sales and cumulative packages. 

~Tim

**Comment by didjee2** [comment]
Doesn't seem to be a front-end issue though, as when I try to pay, it is the same amount as shown in checkout.
So I'm assuming it's something the sale price just overrides the user input price.

However, thank you for the quick answer!
I don't think this is a high priority bug though, as most users will just pay the package price anyways.
