### ISSUE TITLE
Feature Request: Manual Payment counting for required packages

### ISSUE THREAD

**Issue by didjee2** [CraftingStore/Suggestions#176]
**Is your feature request related to a problem? Please describe.**
It kindof is, we have been using BuyCraft for quite some time before, and a bunch of users bought a rank on our old BuyCraft store.
And as we want to give them the possibility to buy rank upgrades, we have to manually "convert" BuyCraft donations into CraftingStore, but Manual Payments are not being counted as a 'real' payment, therefore does not work for Package Requirements.

*(also in BuyCraft manual payments did count for package requirements)*

**Describe the solution you'd like**
Adding an option when creating a manual payment that makes it so the payment is valid for package requirements.

An API URL for this would be even better (as then I could just write a simple script that does this for me) but I would be happy already if I could do it manually.

**Comment by Tim-NL** [comment]
Hello,

The required packages feature will now work with manual payments. 

Thanks for the request!

~Tim
