### ISSUE TITLE
/buy ingame automatic price tag with sale

### ISSUE THREAD

**Issue by IamWTbro** [CraftingStore/Suggestions#177]
**Is your feature request related to a problem? Please describe.**
No it isn't.

**Describe the solution you'd like**
Is it possible to make it so that the packages in /buy ingame already have a price matching the ones on the store instead of having to do it manually? Also with sales like if there is a sale the price would be the same as the online store.

**Additional context**

**Comment by Tim-NL** [comment]
Hello,

You can now use the placeholder {price} in the In-Game description. 

This is the fixed price from the store, it will not take sales/coupons or cumulative packages in an account. 

-Tim
