### ISSUE TITLE
Add discord bot

### ISSUE THREAD

**Issue by YTFurys** [CraftingStore/Suggestions#178]
Is your feature request related to a problem? Please describe.
No it isn't.

Describe the solution you'd like
Add discord bot that u can add to discord server it should work like that if u add it it automatlicli decdects ur all roles in discord and if u  create rank packace it  shows all ranks in your discord server and that bot can automatlicly put users in discord to that rank

**Comment by TheMonDon** [comment]
I don't think this would be a good idea because they would have to host every single bot and manage every discord which could get costly for hosting. I suggest just using a minecraft to discrod bot

**Comment by YTFurys** [comment]
no like it is 1 bot and u can put it on your server like tebex bot

**Comment by Tim-NL** [comment]
This has been implemented a few weeks ago.

-Tim
