### ISSUE TITLE
More localizeable text in language settings

### ISSUE THREAD

**Issue by PsychoLynx** [CraftingStore/Suggestions#179]
**Is your feature request related to a problem? Please describe.**
I would like to localize the webstore as fully as I can. 

**Describe the solution you'd like**
Add the following texts to language settings, if possible:
* "Home"-tab in webstore
* "Pay what you want" in packages with "Pay what you want"-option.
* "Update" and "Remove" in basket
* "I agree with the CraftingStore Terms Of Service and allow CraftingStore to process my data in this way, and herby confirm that I'm over the age of 18, or have permission from my guardian."
* "Copyright" (Not really important, but might be nice. I understand if you'd rather not)

* Also, there is a bug in that "Name" and "Price" are not localized in the package screen, despite being set in the language config. The "Price" is also not localized in the shopping

**Comment by Tim-NL** [comment]
Hello,

Thanks for the feedback.

The items have been added (except for the footer). 

-Tim

**Comment by PsychoLynx** [comment]
Thank you kindly :)
