### ISSUE TITLE
SMTP Email

### ISSUE THREAD

**Issue by Jackis18** [CraftingStore/Suggestions#18]
Would love if you were able to send out emails to my customer, e.g. receipts, via an SMTP email service (e.g. cPanel/Sendgrid - so that emails come directly from the server, and not through crafting store)

Thanks!

**Comment by Tim-NL** [comment]
I looked into this, and we can't support this feature for now. 

We send our E-mails though Mailgun, using their API, and most of our servers are behind CloudFlare's network to prevent direct DDoS attacks against our IP's. 

If we allow you to send mails though your own SMTP settings, those might leak our processing server's origin IP's.  

~Tim
