### ISSUE TITLE
Refund and Chargeback options

### ISSUE THREAD

**Issue by felxjit9** [CraftingStore/Suggestions#180]
**Is your feature request related to a problem? Please describe.**
I can't set a payment to refunded or charged back and trigger the chargeback commands.

**Describe the solution you'd like**
I would like an option where I can mark a payment as chargebacked or refunded. This should automatically execute the chargeback commands too.

Thanks for reading, hope you'll implement it!

**Comment by Tim-NL** [comment]
Hi,

Thanks for the suggestion!

You can now update the status (Paid or Charge-back) at our dashboard.

-Tim
