### ISSUE TITLE
scheduled maintenance

### ISSUE THREAD

**Issue by MinecollYT** [CraftingStore/Suggestions#181]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The owner of the store can say the maintenance should begin at 25.04.2019 19:30 and it should end at 29.04.2019 15:30. (Like the Sales)

My english is not the best, hope you can understand what i mean.
![maintenance_cs](https://user-images.githubusercontent.com/43142792/56460288-c6a30380-63a0-11e9-80a9-a063c611eccf.PNG)

**Comment by Tim-NL** [comment]
Hi,

We've decided to not implement this feature, as maintenance mode is made for the store owner to make changes. We added the ability to see the store when this mode is active in the past. We believe that there is no real need for an automatic maintenance mode.

-Tim
