### ISSUE TITLE
Variables seems to have broken.

### ISSUE THREAD

**Issue by didjee2** [CraftingStore/Suggestions#182]
**Describe the bug**
It seems like the variables are broken. Packages which used to have variables (and still have them assigned in the admin panel) suddenly do not have their variables anymore.

**To Reproduce**
- Make a package
- Make a variable and link it to the package
- Check on the store, it will not ask for the variable to be filled in.

**Expected behavior**
That the store asks the variable to be filled in (right now there is not even a form field to fill in).

**Platform**
CraftingStore Website

**Additional context**
On https://store.centrixpvp.eu, the following packages should have a variable:
- Tags / ChatTags / Custom Tag
- Tags / NameTags / Custom NameTag
- Other / Gift

**Comment by Tim-NL** [comment]
Hello,

The variables are now fully working again. 

~Tim
