### ISSUE TITLE
Deleted manual payments still count for Cumulative Category

### ISSUE THREAD

**Issue by TheMonDon** [CraftingStore/Suggestions#183]
**Describe the bug**
Deleted manual payments still count for Cumulative Category

**To Reproduce**
Create a manual payment that's inside a cumulative category, then delete the manual payment. Go to make a purchase with the username of the manual payment in the cumulative category.

**Expected behavior**
Deleted manual payments to revoke the cumulative category behavior

**Platform**
Craftingstore website (stores)

**Comment by Tim-NL** [comment]
Hello,

Thanks for the report the issue has been resolved. 

~Tim
