### ISSUE TITLE
Gold Plan and Not receiving receipts! 

### ISSUE THREAD

**Issue by Alkiyy** [CraftingStore/Suggestions#184]
My bug is that I have the Gold Plan and I have enable Receipt to be sent out but so far with all my purchases no receipt have been sent out.
![aion](https://user-images.githubusercontent.com/49962002/56693069-6067fa80-6698-11e9-991a-7d088c00d9f0.png)
![aion](https://user-images.githubusercontent.com/49962002/56693108-7c6b9c00-6698-11e9-9b56-f6f840c69024.png)

**Comment by Tim-NL** [comment]
Hello,

The system will now also sent receipts for $0 payments.

~Tim
