### ISSUE TITLE
Sales still marked as Enabled after internally being disabled

### ISSUE THREAD

**Issue by TheMonDon** [CraftingStore/Suggestions#185]
**Describe the bug**
After a sale has ended the Active section is incorrect, it still says yes but on the store website the sale is not active. 

**To Reproduce**
Create a sale that starts now and ends in say a few minutes. When sale ends it will still says its enabled even though the sale is disabled. 

**Expected behavior**
Enabled: Yes turns to Enabled: No after a sale has ended.

**Screenshots**
![sales](https://user-images.githubusercontent.com/11539895/56694530-86979580-66ac-11e9-9477-3b8d0ed5d8d2.PNG)

**Platform**
Craftingstore Website

**Comment by Tim-NL** [comment]
Hello,

This is correct, they enabled / disabled toggle does not change based on the start/end date, you can use it to disable the sale from happening, even within the time frame. 

~Tim
