### ISSUE TITLE
Cumulative Packages not working in hierarchy

### ISSUE THREAD

**Issue by TheMonDon** [CraftingStore/Suggestions#188]
**Describe the bug**
I have some packages on my store,
1: $5
2: $10
3: $20
Now, with cumulative packages I buy rank 1 and it gives me $5 off rank 2 BUT when i buy rank 2 i then have $15 off rank 3 even though i've only spent $10 for rank 2. I do not believe cumulative packages should work like this, it should take what the user has paid and not the total packages cost up to that point.

**To Reproduce**
Have cumulative packages enabled and do make manual payments for the ranks

**Expected behavior**
I expected after buying rank 1 I would get $5 off rank 2, this is correct but then I should get $10 off rank 3 and not $15 off rank 3.

**Platform**
Craftingstore website

**Additional context**
None, can provide more if needed.

**Comment by Tim-NL** [comment]
Hello,

Thank you, this is indeed not the correct format, the issue has been resolved.

~Tim
