### ISSUE TITLE
Unable to buy a package if it's $0.00 (with cumulative package enabled)

### ISSUE THREAD

**Issue by TheMonDon** [CraftingStore/Suggestions#189]
**Describe the bug**
I made a package that is $0.00 on my store, but there is no 'buy now' button, there is only close.

**To Reproduce**
Create a package for $0.00. Try to buy said package. 

**Expected behavior**
I expected to be able to check out with the package.

**Comment by Tim-NL** [comment]
Hello,

Does this also happen when cumulative packages is disabled? 

~Tim

**Comment by TheMonDon** [comment]
No it does not

**Comment by Tim-NL** [comment]
Hi,

As this is expected behavior, we've decided to close this issue. You can use normal categories if you require free packages.

-Tim
