### ISSUE TITLE
More Detailed Statistics

### ISSUE THREAD

**Issue by electro2560** [CraftingStore/Suggestions#19]
At the moment statistics can be viewed by week. It would be amazing if we could view by a range of dates or by month.

Thank you!

**Comment by TheIronMinerLv** [comment]
Agree, this is really needed for proper statistic data usage

**Comment by Tim-NL** [comment]
Hi,

It's now possible to select a range, with a max of two years. We might lift this limit in the future. 

Thanks for the feature request!

-Tim

**Comment by electro2560** [comment]
Looks great. Thank you!
