### ISSUE TITLE
[Feature Request] Plugin More customizable

### ISSUE THREAD

**Issue by TitanFrex** [CraftingStore/Suggestions#190]
It's really nice how you can customize the messages and the interfaces, but I'm frustrated as we are at these levels in 2019, so I would have thought about the possibility of customizing everything, that is:

Customizable Messages (Type): 
- Modify the types of messages in chat, action bar and title. From the site typing this type, of 
  course, if you have emssoi title, you will see a nice title

Customizable GUI +: 
- Make it possible to customize the GUI to your liking. I also thought ocme do, first of all you 
  decide how many rows a GUI must have, second you can put any decoration block and when you  
  want to put a category, on the site, when you create it, check it with a slot in the GUI, put the slot 
  and will buy the category / chest. In the meantime, you can also put thin glass panels.

Show the price in the lore with a placeholder: 
- Set a placeholder {Price}, and in the lore of the item when you set it will buy the price, so 
  consequently even if you change the price, with that placehoder it changes automatically.

This is my proposal and it would be the best thing for this fantastic storeis is my proposal and it would be the best thing for this fantastic store

**Comment by Tim-NL** [comment]
Hello,

Most of these features have been implemented in the recent updates. 

-Tim
