### ISSUE TITLE
Privacy Statement And  terms and conditions

### ISSUE THREAD

**Issue by ChiefJava** [CraftingStore/Suggestions#195]
add 
Privacy Statement
 We take your privacy seriously. We collect data to process your order and to provide updates about our network in line with our Privacy Policy. By ticking this box you confirm you are over 16 years of age or have the permission of your guardian, and consent to us processing your data in this way.

and
I agree to the terms and conditions of this purchase.

**Comment by Tim-NL** [comment]
Hello,

We already have a required checkbox on the store, one regarding privacy and GDPR for CraftingStore, and one for the Terms Of Service. You can change the message for the Terms Of Service from the "language settings". 

~Tim
