### ISSUE TITLE
Ticket & suggestions within the Discord community server

### ISSUE THREAD

**Issue by ChiefJava** [CraftingStore/Suggestions#197]
Add "Suggestion" Bot
Customers can suggest suggestions, 
Customers can vote for them
Add "Ticket" Bot
- VIP Support
- Access from phone too
- Accessible Platform for everyone
add discord roles:
- Customers (to display your customers)
- Guest (to display guest)
- Linked ( Customers that linked their discord acount)
- CraftingStore Bot ( So they wont become mixed up with other roles )

**Comment by Tim-NL** [comment]
Hello,

We discussed the suggestion and we decided to decline the request. 

Several community members shared their thoughts on the question and all off them are fine with the current systems. 

We currently offer support through: 
- Discord (community)
- E-mail
- Tickets on the website
- Twitter (public & DM)

We think this is the best way to support our customers. 

As for the suggestions, we had this on Discord before but it was not organized, thus we will keep our suggestions here, public with a full track record and the possibility to ask follow-up questions. 

~Tim
