### ISSUE TITLE
Add footer links & translate the "accept tos" line

### ISSUE THREAD

**Issue by jokett** [CraftingStore/Suggestions#198]
**Is your feature request related to a problem? Please describe.**
Yes, it's similar, because it would be better for my german customers.

**Describe the solution you'd like**
It would be great if I can add footer links, for example a imprint button. And I want to translate the "I accept the CraftingStore" too.
**Additional context**
-

Kind regards from germany,
Jonas

**Comment by jokett** [comment]
Also I want to request that people kann translate the player count at the players online module.

**Comment by Tim-NL** [comment]
Hello,

We are not able to make this fully translatable, but we can add various ways for this message (predefined by us). Can you share the message that you would like to have for German customers? (globally, on all stores).

-Tim

**Comment by Tim-NL** [comment]
Closed due to not receiving response.

-Tim
