### ISSUE TITLE
Server status module

### ISSUE THREAD

**Issue by lrmtheboss** [CraftingStore/Suggestions#199]
**Is your feature request related to a problem? Please describe.**
yes, as I need the server status module to watch a hostname for the status of the server but you can only put in an IP address for it to watch

**Describe the solution you'd like**
to allow the server status module to accept a hostname like example.com in the IP address field (the one that points to the server that your keeping watch on for the status)

**Additional context**

**Comment by Tim-NL** [comment]
Hello,

Thanks for your suggestions.

It is now possible to enter a hostname instead of the IP. 

-Tim
