### ISSUE TITLE
lockdown mode

### ISSUE THREAD

**Issue by jjj700** [CraftingStore/Suggestions#2]
**Is your feature request related to a problem? Please describe.**
people could buy stuff while you are editing the store that isn't set up yet

**Describe the solution you'd like**
store lockdown or construction mode so you can do maintenance without people seeing or buying anything

**Additional context**
N/A

**Comment by Tim-NL** [comment]
We've just added maintenance mode, you can enabled it from the webstore settings page (https://www.craftingstore.net/admin/settings/webstore). 

If will use the "maintenance.html" file, and only the "language" variable will be available. You can find the default template here; https://raw.githubusercontent.com/CraftingStore/Templates/master/default/maintenance.html

~Tim
