### ISSUE TITLE
Amount of times a item can be bought

### ISSUE THREAD

**Issue by jjj700** [CraftingStore/Suggestions#20]
**Is your feature request related to a problem? Please describe.**
we want to stop people being able to buy the same product again

**Describe the solution you'd like**
we would like a system to select how many times an item can be bought in total and how many times it can be bought by a player.

**Comment by XpcAdam** [comment]
I would like this feature too

**Comment by ToXiCHaZe541** [comment]
Yea this is a necessary feature. I have a unban package but I only want 1 purchase per player.

**Comment by Tim-NL** [comment]
The feature has been implemented, you can now set this at the packages edit page. 

-Tim
