### ISSUE TITLE
Edit my server formula

### ISSUE THREAD

**Issue by gaRt3n** [CraftingStore/Suggestions#200]
**Is your feature request related to a problem? Please describe.**
Since I'm just using a BungeeCord as Server I wanted to Test the API of CraftingStore. Since the Test is just Sending a /say command BungeeCord doesn't know how to use it since the command doesn't exist in BungeeCord

**Describe the solution you'd like**
Add BungeeCord Plugin as a Connection Type to use /alert instead of /say to check the working API.

**Additional context**
Thank you for Creating CraftingStore 👍

**Comment by Tim-NL** [comment]
Hello,

Thanks for the suggestion. 

We now sent both, an Alert and the Say message. 

-Tim
