### ISSUE TITLE
[Feature Request] Email when my silver is about to expire

### ISSUE THREAD

**Issue by TheMonDon** [CraftingStore/Suggestions#201]
As title says, My silver lapsed without me realizing it and i would like to prevent this in the future without topping up all the time.

**Comment by Tim-NL** [comment]
Hello,

We are sending a few E-mails; 
- 7 days reminder
- 5 days reminder
- 3 days reminder
- Expire E-mail.

Did you receive them in your spam box maybe? 

~Tim

**Comment by TheMonDon** [comment]
I have looked in my spam, I did not get any reminder emails except for the expire email.

**Comment by Tim-NL** [comment]
The E-mails are sent as described above, I'll close the issue for the time being. 

-Tim
