### ISSUE TITLE
Missing some Translations

### ISSUE THREAD

**Issue by AntoLuMeju99** [CraftingStore/Suggestions#204]
No translation for the "Redeem coupons/gift cards" at the checkout and the price on the top right

Proof: https://i.imgur.com/hn0229Q.png

**Comment by Tim-NL** [comment]
Hello,

The price field is now taking the "price" language translation.

And the text inside the input box is named "Redeem placeholder" at the panel. 

The text above does not exist in the default template.

-Tim
