### ISSUE TITLE
Option to use plugin for server status

### ISSUE THREAD

**Issue by TaZeDeveloper** [CraftingStore/Suggestions#206]
**Describe the solution you'd like**
The server status moudle currently works by ip and port.

Can you make a option to use the plugin to check the status since we have to put full ips like 2.446.747 
I think this will be easy to configure and will allow more people to use it

**Additional context**
*allow more people to use it* like people on hosts

**Comment by Tim-NL** [comment]
Hello,

Some store owners use BungeeCord and require the stats from their Bungee Network as well, making the plugin push this data instead of getting it from the server directly is currently out-of-scope for CraftingStore. 

-Tim
