### ISSUE TITLE
Come back of the boxes at the top of the stats page

### ISSUE THREAD

**Issue by AntoineHrn** [CraftingStore/Suggestions#207]
**Is your feature request related to a problem? Please describe.**
Before the back-end update, we could see 4 boxes indicating the incomes the current day, week, month and all time/year.

**Describe the solution you'd like**
 Please make these boxes come back, they were really important in matter of seeing where we were at this point of the month for our business.

**Additional context**

**Comment by Tim-NL** [comment]
Hello,

The stats have been added back, they will be visible within a few minutes. 

-Tim
