### ISSUE TITLE
When I try logging in with my IGN on the webstore I get an error.

### ISSUE THREAD

**Issue by hitansh16** [CraftingStore/Suggestions#209]
**Describe the bug**
I get this error when I put my IGN in the login bar, "There is no store located on this domain. If you just set your domain, please wait up to 5 minutes for it to become active."
But when I go back to the web store and select the "Donor Ranks" section again it works. 

**To Reproduce**
https://gyazo.com/9a0baa66bbbc95dd5333883036111e1b

**Expected behavior**
It should go the packages page

**Screenshots**
https://gyazo.com/9a0baa66bbbc95dd5333883036111e1b

**Platform**
The platform the problem occurred on the CraftingStore website.

**Comment by hitansh16** [comment]
I am still waiting for a reply to resolve this issue. The problem still persists.

**Comment by Tim-NL** [comment]
Hello,

We will only update the issue when we resolve the issue or have a question regarding it. 
Please take a look at our readme: https://github.com/CraftingStore/Suggestions

We are working on the issue as we speak. 

-Tim

**Comment by Tim-NL** [comment]
Hello,

The issue only exists when the name is not valid, in the video, it's not long enough. 

We will continue to look at why your store behaves in this way, but the issue will not affect real users.

-Tim

**Comment by hitansh16** [comment]
The name is very much valid and real player/user, 1GN is my IGN, https://namemc.com/profile/1GN.9 
I know other people too with 3 digit in game names.

**Comment by hitansh16** [comment]
@Tim-NL

**Comment by Tim-NL** [comment]
We are aware, the limit has been set to three now, and the issue itself has been resolved too. 

-Tim

**Comment by hitansh16** [comment]
Now this is what happens: https://gyazo.com/106c4cc3ccd936d710f012eccc48a9a2
After I put my IGN and press enter or click buy now, it stays on the login page only and nothing happens. But then if I click on a package it works. Should it not be like as soon as I put in my IGN and press enter it takes me into the store automatically?

**Comment by Tim-NL** [comment]
Your name appears to be not valid for our validation, we'll look into your specific name. 

-Tim
