### ISSUE TITLE
List of Feature Requests AND Issues

### ISSUE THREAD

**Issue by Exophobias** [CraftingStore/Suggestions#21]
Sorry for the big list. These are all the suggestions that I made on Support Tickets (Which isn't the best but I didn't know where else to do it until I was finally directed here to post my issues and suggestions!)

If you find any errors with mine or don't understand. Let me know and I'll see what I can do to fix it and/or help you understand what I mean!

Best Regards,
Ryan

### Feature Request 1

General Feature Title: Ingame /buy - Subcategories are **IN** their **PARENT** categories.

Issue: I had to rename all of my subcategories because when you do /buy in-game - It will not put Ranks or Perks in their parent category.

Outcome: All subcategories should be IN their parent category in /buy

### Issue 1 - Related to Feature Request 1

General Feature Title: Subcategories with the same name will only show one of the actual items in the subcategory. The other one just doesn't show.

Outcome: I wish for this to be fixed. So I can just name my Survival and Skyblock subcategories to just 

> Perks

and not have to call it 

> Survival Perks or Skyblock Perks

Its kind of an inconvenience and un-needed!

### Feature Request 2

General Feature Title: One OR multiple commands to be run when someone files a chargeback

Request: If someone were to file a chargeback. I had this issue on MinecraftMarket. I want it to run a BungeeCord command `/ban {player} Violated Terms of Service by charging back on a purchase.`

### Feature Request 3

General Feature Title: Team Account Permissions Control

Issue: You can add a Co-Owner to your store but they have ALL permissions for the store.

Outcome: What if I want my admins to have access but NOT be able to view any sensitive information or add packages or anything. What if I just want them to view the transaction or re-run commands, etc. I want `individual/specific permissions control for each page and things on the store.` like how BuyCraft does it.

### Feature Request 4

General Feature Title: Make Shop Sales more customizable - Referring to #1 

Issue: You can only do GLOBAL sales for your market/store. I want it so I can only do a specific category or do the ENTIRE store EXCEPT for a specific Category. So a Whitelist AND a Blacklist option.

Outcome: I want to be able to have a 50% sale on my Survival category but maybe a 25% on my Skyblock category. Or have a sale on just one sub-category in the entire store and nothing else. Or vice-versa entire store on sale except for one category. 

### Feature Request 5

General Feature Title: If you used MinecraftMarket they had really good variables. You had a selection of what variable you could use. Dropdown, Text/Writing area (Like how it is now), and many other ways.

A site called DonationStore is using the same site as MinecraftMarket. This is what you should add
[Create Variable](https://donationstore.net/static/img/variables.png)
[Create Coupon](https://donationstore.net/static/img/discounts.png)

Outcome: This will give us more options when creating Coupons, Sales, Variables, etc. and overall allow us to do more with our store such as creating Rank Upgrades. A good way to do rank upgrades is [Create Variable](https://donationstore.net/static/img/variables.png)
and then just make it so that you had to of purchased a certain rank or package to use the package with this varaible attatched.

### Feature Request 6

General Feature Title: New Package Page - In the category selection. Put indent for subcategories under its parent category so that you know its Survival Perks or Skyblock perks - Refers to my Feature Request above so that I don't have to name subcategories. `Skyblock Perks` or `Survival Perks` I just want to name it `Perks`

Issue: In the creation of new packages. Make it so that subcategories are under the parent category with an indent so that we know its a subcategory. I don't want to name specific categories so I know its Survival like S-Perks which means S(urvival)-Perks or C-Perks for C(reative)-Perks

Outcome: Have it so its like
```
Minigames
Survival
    > Ranks
    > Perks
    > Crates
Skyblock
    > Ranks
    > Perks
Creative
```

### Issue Request 2 

General Feature Title: GiftCards Broken - Sets the cost the remaining balance on the giftcard to the price of the last item they purchased. 

Issue: I gave someone a $7 giftcard and they used it to buy a $4 rank. It set the remaining balance on the $7 giftcard t o $4 - NOT $3 like it should of been. Referring to issue #7 

Outcome: Make it so it properly sets the remaining balance.

### Feature Request 7

General Feature Title: Maintenance Mode #2 - Keep the background and have a CUSTOM message

Issue: You just have a blank white screen saying in maintenance mode.

Outcome: Keep the default or custom background the store owner/manager add and allow them to add a CUSTOM store maintenance message with the same editor as the package thing. So we can add colors and bold and whatnot.

**Comment by Tim-NL** [comment]
Moved all items to their own issues, to keep them organized. 

~Tim
