### ISSUE TITLE
Requirements are not working

### ISSUE THREAD

**Issue by TerrorGamesOff** [CraftingStore/Suggestions#210]
**Describe the bug**
Requirements are not working.

**To Reproduce**
1. Go to any package
2. Click on requirements
3. Setup your requirements

**Expected behavior**
To solve the problem, i tested on other sites on craftingstore and it still not working

**Screenshots**
-

**Platform**
CraftingStore

**Additional context*
-

**Comment by Tim-NL** [comment]
Hello,

Thanks for the report.

We identified the problem and resolved the issue. Please go ahead and check if you are now able to purchase the items.

-Tim

**Comment by TerrorGamesOff** [comment]
Hi! I test it again and still working....
Test on donatii.terrorgames.ro

În dum., 16 iun. 2019 la 02:15, Tim Kwakman <notifications@github.com> a
scris:
