### ISSUE TITLE
Packages not available for manual payment

### ISSUE THREAD

**Issue by Predavanje** [CraftingStore/Suggestions#211]
When creating manual payment not all packages get shown in that selection so you can't create manual payment for some packages.

**Comment by AntoLuMeju99** [comment]
Same problem

**Comment by Tim-NL** [comment]
Hello,

We changed the way the packages are received in the selector, the build is currently being deployed. 

Please check if the missing packages are showing correctly in ~10 minutes. 

-Tim

**Comment by AntoLuMeju99** [comment]
Now i can see all packages, but there still an error, if 2 sub category have the same name, but their main category is different, they will be showed all in the same sub category

**Comment by Tim-NL** [comment]
Hi,

We will now add the category ID to any duplicate categories, so it will be something like:
Ranks
- Package 1
Ranks (12345)
- Package 2
Ranks (54321)
- Package 3

-Tim
