### ISSUE TITLE
Voucher creation command

### ISSUE THREAD

**Issue by ImCasperr** [CraftingStore/Suggestions#213]
I am frustrated that there is no way to create vouchers in-game and no way to stick it in a variable within the API. 

**Describe the solution you'd like**
I want a way to either make a plugin that creates an in-game item and have a lore show the voucher code or a way to use the API to make that myself.

**Comment by Tim-NL** [comment]
Hello,

Before we can make this API endpoint, we require;

What do you want to give as input? 

What do you expect as output? 

-Tim

**Comment by ImCasperr** [comment]
/craftingstore voucher (create|delete) (code) (if create then enter amount)

Is this what you mean?

**Comment by Tim-NL** [comment]
We are able to create an API on our endpoint: https://api.craftingstore.net

This will be a JSON API that you can call for, not in the plugin.

-Tim

**Comment by ImCasperr** [comment]
Can I get documentation on how to use it?

**Comment by Tim-NL** [comment]
We do not have such API at this moment, I'm asking you for your requirements before we can build it. 

-Tim

**Comment by Tim-NL** [comment]
Declined as we have not received a response regarding this.

-Tim
