### ISSUE TITLE
Problem with upgrades.

### ISSUE THREAD

**Issue by TerrorGamesOff** [CraftingStore/Suggestions#214]
**Describe the bug**

To Reproduce
    1.Go to any package
    2.Click on requirements
    3.Setup your requirements
    4.See error

**Expected behavior**
To solve the problem, i tested on other sites on craftingstore and it still not working

**Platform**
CraftingStore

**Additional context**
-

**Comment by Tim-NL** [comment]
Setting up the requirements works without problem on all test stores and we have seen many stores using requirements. There was a problem with the validation (#187) but this has been resolved.

Is this issue related to the mentioned issue or are you referring to something else? 

-Tim

**Comment by TerrorGamesOff** [comment]
The problem is now fixed! Some days ago, the problem was still here, but
now its fixed :D

În vin., 19 iul. 2019 la 02:34, Tim Kwakman <notifications@github.com> a
scris:
