### ISSUE TITLE
Stripe is enabled yet it doesn't show

### ISSUE THREAD

**Issue by rnateh** [CraftingStore/Suggestions#215]
**Describe the bug**
I have set up Stripe correctly and enabled it, and yet when I go to purchase something on the site stripe isn't an option. (I was told to make this ticket by Tim (staff).

**To Reproduce**
Simply set up stripe correctly and click enable. I have it set up correctly and enabled and yet it won't show up as a option.

**Expected behavior**
Stripe to be shown as a payment method

**Screenshots**
http://prntscr.com/o9m9om

**Platform**
Occurred on CraftingStore website

**Comment by Tim-NL** [comment]
Hello,

Is your store using any custom templates? I told you to create the ticket but after doing tests we noticed that the issue does not occur on any other store.

-Tim

**Comment by rnateh** [comment]
I fixed it. It was my stupidity not so much a bug and I forgot about this. Each package has to have stripe enabled or its disabled by default.

**Comment by Tim-NL** [comment]
Thanks for the update! I'll close the issue and we will make sure to look into the default.

-Tim
