### ISSUE TITLE
Cumulative Package

### ISSUE THREAD

**Issue by iTwitchTV** [CraftingStore/Suggestions#216]
**Describe the bug**
No money is taken off when cumulative package is enabled
**To Reproduce**
1. Go to 'categories'
2. Click on 'create a category and enable cumulative package'
3. Do 'add packages to the category and acquire lower tier'
4. See error 'then no money is discounted'

**Expected behavior**
No money is discounted off a cumulative package 
**Screenshots**
http://prntscr.com/obioze I have the $10 tier (lower than $20) and no money is discounted off it
**Platform**
The platform the problem occurred on. Ex. the CraftingStore website or the Minecraft plugin. 
In case of the Minecraft plugin, please list the details of the environment, such as server type, version.
CraftingStore website
**Additional context**

**Comment by Tim-NL** [comment]
Cumulative categories will take the money off other packages, for example:
VIP - VIP Plus

If you buy "VIP" the "VIP Plus" will get a discounted price, this seems to be one and the same package.

-Tim

**Comment by iTwitchTV** [comment]
I know how they work that's not what I asked. I'm telling you it doesn't take money off the package, thanks for replying 12 days later though

**Comment by Tim-NL** [comment]
Did you buy the same package two times? Cumulative packages will only work if there is a clear pricing structure; 

VIP -> VIP plus

Buying VIP two times with different prices will not create any discounts.

-Tim
