### ISSUE TITLE
Suggestion: allow limitations to variables

### ISSUE THREAD

**Issue by dieterblancke** [CraftingStore/Suggestions#217]
**The problem for which this feature is being suggested:**
In our store, we sell tags & nametags, which have a minimum size of 3 and maximum size of 12 and have to apply to a certain (latin only) regex.
If people enter an invalid (name)tag in the store, they don't receive the package and this might lead to confusion // an unhappy buyer because he couldn't get what he wanted (after paying).

**Describe the solution you'd like**
When creating / editing a variable, it would be nice to be able to set limits for a variable, such as minimum and maximum length or a Regex pattern.

**Comment by Tim-NL** [comment]
Hi,

Thanks for your suggestion!

You can now do dropbox boxes, and set a max / min length on items.

Template changes required: https://github.com/CraftingStore/Templates/commit/969a41713137e941d8ba2aba8bab3ae5630e7b52

-Tim
