### ISSUE TITLE
auto give role

### ISSUE THREAD

**Issue by MCEpicShasta** [CraftingStore/Suggestions#218]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
auto give a role when a user purchases something on their store

**Additional context**
none

**Comment by Blocksnmore** [comment]
If your talking about minecraft just use your permission plugin to grant it. If you are talking about discord that is not avalible yet but i belive it already has been suggested.

**Comment by MCEpicShasta** [comment]
> If your talking about minecraft just use your permission plugin to grant it. If you are talking about discord that is not avalible yet but i belive it already has been suggested.

dude did I say rank? No. I said role there's a difference

**Comment by Tim-NL** [comment]
If this is related to Discord Roles it's a duplicate with #178 

--Closed for now--

~Tim
