### ISSUE TITLE
Block specific items from being bought with giftcards

### ISSUE THREAD

**Issue by M4T14SG4M3R** [CraftingStore/Suggestions#219]
**Is your feature request related to a problem? Please describe.**
I want to block some packages from being bought with giftcards like unbans etc

**Describe the solution you'd like**
Add a option on the gateways of the packages like the paypal one with a menu to enable or disable that package from being bought with giftcards and if someone tries to buy it the store will show a message saying that the package is not able to accept giftcards

**Comment by Tim-NL** [comment]
Duplicate with #145. 

-Tim
