### ISSUE TITLE
Products in categories not sortable

### ISSUE THREAD

**Issue by FruitLabCBR** [CraftingStore/Suggestions#221]
**Describe the bug**
In my store (store.fruitlab.net) i cant sort the products in the categories "Kisten Schlüssel" and "Kosmetik Kisten"

**To Reproduce**
Have no idea

**Screenshots**
Backend sorted: http://prntscr.com/ojwibf
Frontend: http://prntscr.com/ojwio3

**Platform**
Craftingstore Website

**Comment by Tim-NL** [comment]
Hello,

Thank you for reporting, the issue has been resolved.

-Tim
