### ISSUE TITLE
Gift Cards generation of purchase

### ISSUE THREAD

**Issue by HipporunnerXTyler** [CraftingStore/Suggestions#223]
I think it would be cool to make it so when someone buys a package it can generate a gift card for X amount after it is purchased and is emailed to the user via the receipt system

**Comment by Tim-NL** [comment]
Hi,

You can now configure packages to create a gift-card on purchase. See this article for information on how to set it up; https://help.craftingstore.net/books/premium-features/page/selling-gift-cards-on-your-store

-Tim
