### ISSUE TITLE
Display the statistics per server

### ISSUE THREAD

**Issue by RSLuke** [CraftingStore/Suggestions#225]
**Describe the solution you'd like**
It's simple, when our server grows, it often becomes a network and packages become assigned to different servers, so it would be useful to know how much per month/range/day we managed to sell.

**Comment by Tim-NL** [comment]
Hi,
Since this issue has been created, we have created the "Statistics" section & allow .csv exports for date ranges, that shows exactly the packages and amount you've made.

-Tim
