### ISSUE TITLE
[BUG] MySQL commands won't send

### ISSUE THREAD

**Issue by GerardoWacker** [CraftingStore/Suggestions#227]
**Describe the bug**
MySQL commands not sending properly, status keeps displaying "Pending".

**To Reproduce**
1. Add the MySQL server information, as well as the database.
2. Add commands.
3. Buy a random package, to test the service.
4. Payment goes through, but commands stay at "Queued" and "Pending".
5. Doesn't matter how much the commands are re-sent, it will not change.

**Expected behavior**
SQL Commands should send properly to the server.

**Screenshots**
![image](https://user-images.githubusercontent.com/32494885/62407323-d67bd780-b58c-11e9-9375-a7bb362fc7dd.png)

**Platform**
CraftingStore with MySQL server configuration

**Additional context**
MySQL commands include the UPDATE statement.
MySQL server is open, and allows connections from every IP.
Connection information is well stated, and it should properly connect.

**Comment by Tim-NL** [comment]
Hello,

Can you share the command that you executed? 

~Tim

**Comment by GerardoWacker** [comment]
Sure, the command is
`UPDATE users SET hat=1 WHERE usuario='TestUser'`

**Comment by GerardoWacker** [comment]
Well, 2 months have passed. Is it fixed now?

**Comment by Tim-NL** [comment]
Thanks for your patience. The issue has been resolved in our testing environment. We are currently deploying the fixes to production.

Expect the bugfix to be live in around 20 minutes. We also added logging on our end, so if the commands do still not process, please contact us through the ticket system and we can see the exact error message.

-Tim
