### ISSUE TITLE
[BUG] Exception whilst parsing RCON input | Cauldron 1.7.10

### ISSUE THREAD

**Issue by TheDeafCreeper** [CraftingStore/Suggestions#228]
**Describe the bug**
When attempting to process an order, the server returns "Exception whilst parsing RCON input" and does not run any commands.

**To Reproduce**
1. Start a 1.7.10 Cauldron server
2. Setup RCON
3. Attempt to have a command run by the store.

**Expected behavior**
The commands would run.

**Comment by Tim-NL** [comment]
Hello,

I just tried the command "Hoi {player}".

Image: https://cdn.ownshot.eu/direct/7DGpMcVZStIAb9fZCd8U/b9gwLOfJc7

The system is processing this command without a problem, can you share the command that you tried? 

~Tim

**Comment by TheDeafCreeper** [comment]
The package includes:
broadcast {player} just bought Fly!
pex user {player} add essentials.fly.safelogin
pex user {player} group set Donator
pex user {player} add essentials.fly

**Comment by TheDeafCreeper** [comment]
It actually appears to be an issue with Cauldron. We've updated to thermos and now it works.

**Comment by Tim-NL** [comment]
Thanks for the information, we'll add it to our knowledge base for future reference. 

-Tim
