### ISSUE TITLE
Sever selector 

### ISSUE THREAD

**Issue by doragoncraft** [CraftingStore/Suggestions#229]
**Is your feature request related to a problem? Not  problem more for convenience 

**Describe the solution you'd like**
The ability to select a server for what you would like a perk on ie I run a network off servers and allow purchases of in game money on most off them but have to do separate categories and packages for each one would like it to be all in one and just select the server that the buyer would like it on 

**Additional context**
I'm on discord if you want more info doragoncraft#6019

**Comment by Tim-NL** [comment]
Hi,
We are going to decline this feature request at this point in time, as it is not something we believe can be used by a lot of users.

As an alternative, it is possible to create one category for each server. Then, you can select on what server(s) commands should run for a specific package as you describe in your original issue. I think this is the best way to do this at the moment. 

-Tim
