### ISSUE TITLE
One OR multiple commands to be run when someone files a chargeback

### ISSUE THREAD

**Issue by Tim-NL** [CraftingStore/Suggestions#23]
General Feature Title: One OR multiple commands to be run when someone files a chargeback

Request: If someone were to file a chargeback. I had this issue on MinecraftMarket. I want it to run a BungeeCord command /ban {player} Violated Terms of Service by charging back on a purchase.

--
Copy of @Exophobias's issue (#21) to separate them.

**Comment by MisterZet** [comment]
This is not possible.

**Comment by Exophobias** [comment]
In the Other > Commands - Have it so you can add multiple  commands like you can do when creating/editing packages and have the same ability to select what server it is on and when it runs

So `broadcast Thank you {player} for purchasing {package_name}!` will be run on ALL servers on time of purchase BUT `/ban {player} Violated Terms of Service - Filing a chargeback` on only the BungeeCord server (I use AdvancedBan punishment plugin so it has to be BungeeCord server) when the player files a chargeback,

**Comment by MisterZet** [comment]
You see Exo, this is impossible. A minecraft store can only accept payments, but after money is in your balance, it has no control over the paymemt, so this is not possible.

**Comment by Exophobias** [comment]
Actually it is possible. The store can detect whether a chargeback is filed. They can’t do anything with the money or anything but all I want it to do is when someone files a chargeback it sends a command that I set it to do.

________________________________

**Comment by Tim-NL** [comment]
Because we entered our IPN URL, PayPal will notify us of changes in the payments. If for example the user charges back the money, PayPal will send us a notification that this specific payment did get a chargeback. 

~Tim

**Comment by Exophobias** [comment]
@Tim-NL 

So is there a planned implementation of global commands on chargeback
![buycraft-global command types](https://user-images.githubusercontent.com/26949488/44068812-d19762e8-9f30-11e8-9699-786069b6b2e6.png)

Such as the picture I got from BuyCraft. I want to be able to run chargeback commands. Such as pex user delete and /ban <user>

but I also want the announcement of them purchasing.

**Comment by Tim-NL** [comment]
Hi, 

It's now possible to choose Initial/Expiry/Charge-back for global commands. It also handles PayPal chargebacks now. 

-Tim

**Comment by Exophobias** [comment]
@Tim-NL - Can you make it so you can select what server it runs on? I want to be able to have a global broadcast saying "{username} has bought {package}!" but when a chargeback happens. I want it to run "ban {username} Chargeback" but I only want it to run on my BungeeCord server. If it runs on the Spigot server it will Essentials Ban them because that's what the consoles recognizes as /ban to.

**Comment by Tim-NL** [comment]
You can use the package commands for specific requests like these. 

-Tim

**Comment by Exophobias** [comment]
That means I have to put ban <username> on ALL packages and that’s a big inconvenience and useless thing to add

________________________________

**Comment by Tim-NL** [comment]
Okay, that's possible.

**Comment by Tim-NL** [comment]
Implemented server selection for global commands.

-Tim
