### ISSUE TITLE
Run command when server goal is completed

### ISSUE THREAD

**Issue by CaszGamerMD** [CraftingStore/Suggestions#230]
Would be great to have a command run on the server when goal is reached, would act just like the commands on purchase but for everyone that is on currently or has been on within a timeframe

**Comment by Tim-NL** [comment]
Hi,

Thanks for the suggestion!

We have introduced "Community Goals" some time ago.

https://help.craftingstore.net/books/features/page/community-goals

This feature offers the ability to run commands when the goal is reached.

-Tim
