### ISSUE TITLE
RCON does not send correctly on Paper

### ISSUE THREAD

**Issue by Agnax** [CraftingStore/Suggestions#236]
**Describe the bug**
When you make a payment manually, the commands in RCON are sent instantly. But if someone buys a product, the command stays in a kind of queue, until you manually resend it, and all the commands that were queued, are sent suddenly

**To Reproduce**
1. Only buying something in the own web store
2. You'll see how the command never comes
3. Now, make a manual payment and all the commands that were not executed will do so now.

**Expected behavior**
You should execute the commands when completing the payment.

**Screenshots**
The commands that the server should execute, But after an hour, still queued
![image](https://user-images.githubusercontent.com/29905447/63149734-9411bc00-bfca-11e9-857f-f28b395e2294.png)

Here I make a payment manually
![image](https://user-images.githubusercontent.com/29905447/63149873-f5d22600-bfca-11e9-8361-a532d2642664.png)

When creating the payment manually, after 5 seconds the missing commands are executed together with the new manual payment commands.
![image](https://user-images.githubusercontent.com/29905447/63150367-3a11f600-bfcc-11e9-8a07-fdb377cd6b94.png)

**Platform**
CraftingStore via RCON Minecraft

**Additional context**
It only happens when you buy something, not when you make a manual payment. (RCON)

With the plugin if it works correctly, I have it installed in the bungee and lobby

**Comment by Tim-NL** [comment]
Hello,

This issue has been resolved a few weeks ago, thank you for reporting!

-Tim
