### ISSUE TITLE
Gift card creation

### ISSUE THREAD

**Issue by projay11** [CraftingStore/Suggestions#238]
**Is your feature request related to a problem? Please describe.**
On our server we give people store credit for certain activities, currently we have to manually create a gift card and then send them a code which causes issues when lots of people try to redeem them for a gift card.

**Describe the solution you'd like**
We would either like a command added into the plugin to create a gift card or either a way of creating them using your api as we can integrate this api with our server.

**Additional context**
N/A

**Comment by Tim-NL** [comment]
Hi,
We have released our BETA API a few weeks ago, that includes support for the Gift-card API endpoint; https://docs.api.craftingstore.net/

You can use that endpoint to generate gift-cards from in-game.

-Tim

**Comment by MatiasMunk** [comment]
I would like to know, how do we generate this from in-game exactly?

**Comment by Tim-NL** [comment]
Please do not use our suggestions/issues tracker for general questions. You can use our support system for that.

-Tim
