### ISSUE TITLE
No top packages

### ISSUE THREAD

**Issue by Dinoosawruss** [CraftingStore/Suggestions#239]
**Describe the bug**
Top packages not shown in statistics

**To Reproduce**
1. Go to statistics
2. Click on get results
3. Look at top packages
4. None shown

**Expected behavior**
A list of all the top packages are shown

**Screenshots**
_The amounts are shown but I have blanked them out_
![image](https://user-images.githubusercontent.com/22278485/63295684-341a5e80-c2c5-11e9-8528-80101efec568.png)

**Platform**
CraftingStore website

**Additional context**
All the donations are real donations and have successfully processed and gone into the paypal

**Comment by Tim-NL** [comment]
I have never updated this issue here at GitHub, but the issue itself was resolved weeks ago.

Closed.

-Tim

**Comment by Dinoosawruss** [comment]
Not solved for me

**Comment by Tim-NL** [comment]
Now the issue is solved, the fixes are live in about 15 minutes.

-Tim
