### ISSUE TITLE
Referral System

### ISSUE THREAD

**Issue by NekrosBurek** [CraftingStore/Suggestions#240]
I would like to create a referral codes or users could create them and i can view them in admin panel this could be great add-on or feature for server owners to see which of their advertisers or youtubers brought the most profit to the server

I for example would like to give % of my profits to youtubers but only to % they brought, like if one youtuber with his invitations brought only 5 $ profit and other 20 $ i don't want to mix their rewards , the first one would get 0.5 as his 10% and other would get 2$ (this is an example not a fixed price)

**Comment by Tim-NL** [comment]
Hi,
We believe that this feature is currently out of scope for the CraftingStore system. I recommend you use coupons to achieve the same goal, you can create coupon-codes for different YouTubers, and use our .csv export feature to see exactly what coupon-code was used. You can import this .csv file into something like Excel and use that to filter the results as you see fit.

-Tim
