### ISSUE TITLE
See users email

### ISSUE THREAD

**Issue by Trnrr** [CraftingStore/Suggestions#242]
**Is your feature request related to a problem? Please describe.**
Not sure because I'm not sure if it's intended or not.

**Describe the solution you'd like**
I would like to see the users email that they used to pay with. Some items I have I need to contact them, but it is very difficult since the only way currently is through Minecraft. It would be nice if it showed on the payment page.

**Comment by Tim-NL** [comment]
Hello,

We do not provide such information to the store owner due to the GDPR. The E-mail us used by us to notify the customer about their payment when this is enabled.

The customer can also create a profile for themselves by confirming the account, so they can see any payment they made from their e-mail. This way they can redact information if they wanted to. It is not intended to be shown to the store owner.

-Tim

**Comment by Trnrr** [comment]
So you couldn't add a little checkbox or something that says "Allow the store owner to contact me"? I'm not well versed in GDRP but it says you need to ask consent to email/store it. This is a pretty big/basic feature for a online store. You already have the user account system where they can redact information if needed, so why not add their email to that (if they allowed it upon purchase)? I appreciate the reply.

**Comment by Tim-NL** [comment]
The e-mail field is not intended for the store owner, it is intended for the reasons specified above. It would be possible in the future to add it to the payments information tab, but not at this moment.

We do provide you with the PayPal transaction ID, for example, so you would be able to use their PayPal e-mail from the PayPal dashboard.

-Tim

**Comment by Trnrr** [comment]
Thank you for the clarification. I think this would be a good feature addition in the future. For now I will try what you said and see their email in Paypal.

**Comment by Tim-NL** [comment]
I'll keep the suggestion open for the future.

**Comment by Tim-NL** [comment]
Due to the GDPR, we'll stay by our existing statement, of not showing the e-mail address. 

-Tim
