### ISSUE TITLE
Spoiler buttons

### ISSUE THREAD

**Issue by Explosivee** [CraftingStore/Suggestions#243]
Spoiler buttons to make our store pages more cleaner and organized, example; 
![example1](https://user-images.githubusercontent.com/35429381/64447184-72948380-d0e3-11e9-8e91-c1d3bdda3a0b.png)

**Comment by Tim-NL** [comment]
Sorry for the delay.

Store owners have the ability to do so on our premium plans. This is currently "out of scope" for the default theme. And the platform has "categories" to solve this issue. 

-Tim
