### ISSUE TITLE
Public API / CraftingStore for Fabric

### ISSUE THREAD

**Issue by DrexHD** [CraftingStore/Suggestions#245]
**Is your feature request related to a problem? Please describe.**
I want to open a 1.15 snapshot server and automate purchases made on there. I am using Fabric to modify my server, similar to spigot.

**Describe the solution you'd like**
To make this possible, it would be great if there was a publicly available API for CraftingStore or even a Fabric Mod.

**Comment by Tim-NL** [comment]
Hi,
After looking into this more, we are not going to create a Fabric mod plugin at this point in time. I recommend you to use our RCON server type. This allows you to automate purchases (it will just not have the /buy menu). 

-Tim
