### ISSUE TITLE
Custom gateway (Feature request)

### ISSUE THREAD

**Issue by Gahvila** [CraftingStore/Suggestions#247]
**Is your feature request related to a problem? Please describe.**
The store does not support a certain payment method.

**Describe the solution you'd like**
The solution would be a "Custom gateway" button where you can link it to a page, eg discord server where you can then ask to buy a rank.

**Additional context**
![image](https://user-images.githubusercontent.com/43291143/65384881-33e00980-dd30-11e9-8215-71e1a519bcf9.png)

**Comment by Tim-NL** [comment]
Merged with #68

The same request, but different names.

-Tim
