### ISSUE TITLE
Package page doesn't show currency

### ISSUE THREAD

**Issue by ar00n** [CraftingStore/Suggestions#249]
**Describe the bug**
Package page doesn't show currency. (Price: 4.99)

**To Reproduce**
1. Open the package page.

**Expected behavior**
Price: 4.99 GBP

**Platform**
CraftingStore Website

**Comment by Tim-NL** [comment]
Thanks for the report!

The price will now show correctly on the default template. We will contact the custom template builders shortly to inform them about the change.

-Tim
