### ISSUE TITLE
Requirement bug + some people cannot buy package

### ISSUE THREAD

**Issue by dieterblancke** [CraftingStore/Suggestions#251]
**Describe the bug**
When someone buys a 'Phantom' rank in our store, and afterwards he buys a 'Phantom to Vanguard' upgrade, then he cannot buy 'Vanguard to Titan' upgrade and I have to add the Vanguard package manually, while these are the requirements of the 'Vanguard to Titan' package:
![image](https://user-images.githubusercontent.com/12124549/66146452-199a0b80-e60d-11e9-9d0c-8b39d7810288.png)

The second bug is that people cannot buy the Unban package,, I don't know what causes this problem.
It does have a limit of 1 per player, but even people who never bought it cannot buy it (it's also annoying there is no error message)

**Expected behavior**
People should be able to buy the package if they have the requirements of it.

People should be able to buy the unban package.

**Platform**
CraftingStore website

**Additional context**
My store is located at: **store.centrixpvp.eu**

**Comment by dieterblancke** [comment]
super annoying bug still ^
Nearly all donators have to buy a donation gift package (where u can set custom amount) so I can manually upgrade their rank because of the requirements being broken.

They did buy **one** of the requirements of the rank upgrade package, but then they cannot buy it.

**Comment by dieterblancke** [comment]
.

**Comment by Tim-NL** [comment]
The issue has been resolved, it only occurred when the user did buy the second package - looking at the creation date of the packages -

Thanks for reporting!

-Tim
