### ISSUE TITLE
[Feature Request] Limit access to team accounts/add permissions to team accounts

### ISSUE THREAD

**Issue by MrPranklez** [CraftingStore/Suggestions#252]
**Is your feature request related to a problem? Please describe.**
It is more or less related to an issue. I want for some of my team accounts to be able to look up purchases and such but not to manually register new purchases and a few other things.

**Describe the solution you'd like**
Setting up a permissions system for team accounts. If you were to implement this it would be cool to add permissions to everything, so you can customize team accounts to access only what the store owner would want.

**Additional context**
I know buycraft supports a permissions system with their team accounts and I think craftingstore too would benefit from such a system.

**Comment by Tim-NL** [comment]
Merged with #24 

-Tim
