### ISSUE TITLE
Minimum basket amount to checkout

### ISSUE THREAD

**Issue by IGNFiqs** [CraftingStore/Suggestions#254]
**Is your feature request related to a problem? Please describe.**
So we recently added "key sale" wich make our crate keys very cheap, around 5 cents to 40 cents, but if users only buy like 1 or 2 keys of 5 cents, it's a total of 10 cents but all of that amount get's taken by paypal fee's, so I suggest adding a selection were we can set a minimum basket, example they must have $1 in their basket to checkout.

**Comment by Tim-NL** [comment]
Duplicate with #120

-Tim
