### ISSUE TITLE
New Payments method??

### ISSUE THREAD

**Issue by Kapakulia** [CraftingStore/Suggestions#255]
**Is your feature request related to a problem? Please describe.**
As xSolla isn't allowed in CraftingStore I recommend starting adding new payment methods like SMS payments, Bank transfers, etc. Maybe some of the server owners don't even need new payments method but some servers most players use xsolla as payments.

**Describe the solution you'd like**
Here are my solutions for SMS we could use OneBIP can we use worldwide as for bank transfers PaySera as they too work worldwide. One of my developers checks the API for both and both can be easily integrated into CraftingStore or even other.

**Comment by Tim-NL** [comment]
Hi,
We have implemented the OneBip payment method a few weeks ago. As for other payment options (like bank transfers), we believe that our current offering is enough for most payment methods.

-Tim
