### ISSUE TITLE
Limit items in cart from catagory

### ISSUE THREAD

**Issue by TheCynicalKitty** [CraftingStore/Suggestions#257]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
N/A

**Additional context**
Can you add a way to make it so only one rank can be in a cart at a time (highest one selected) so people cannot buy multiple ranks from one category (unless option is enabled) so people cannot buy (using your example) VIP1,2&3 in one purchase (Tags and cosmetic for multi buys and stuff is fine), but id love to ability to limit "multiple" rank purchases in the same buy since there going up in a hierarchy

**Comment by Kensharma** [comment]
#283 I believe we have the same suggestion just different wording? Maybe we can get these suggestions merged :)

https://github.com/CraftingStore/Suggestions/issues/283

**Comment by Tim-NL** [comment]
Hi,

I think that these are indeed the same issue. I think #283 is easier to read & understand. So I'll close this one.

-Tim
