### ISSUE TITLE
Giftcard Suggestions.

### ISSUE THREAD

**Issue by olliemortal1** [CraftingStore/Suggestions#259]
If there isn't already a way, We would like a way to let people buy gift-cards from the store. When people do, it would auto generate a code and send it to there email they provided.

We would also like Gift-cards to be like the coupons, where you can select what they work on and if there will work with sales or not.

If theses are implemented you could have a setting where you can choose the default setup of what a gift-card would work on for people who buy them off the store.

**Comment by Tim-NL** [comment]
Duplicated issue.

-Tim
