### ISSUE TITLE
AutoRole bot 

### ISSUE THREAD

**Issue by TerrorGamesOff** [CraftingStore/Suggestions#260]
**Is your feature request related to a problem? Please describe.**
There is no problem.

**Describe the solution you'd like**
You can make bot accept only that format: "!craftingstore:claim code" and if someone send other messages the bot automatically delete the message.

**Additional context**
-

**Comment by Tim-NL** [comment]
In this case, the bot would remove every message on the server that is being sent? Please let me know if you mean this. 

-Tim
