### ISSUE TITLE
[Issue] Formatting for Packages/Categories/Pages not working

### ISSUE THREAD

**Issue by MrPranklez** [CraftingStore/Suggestions#261]
**Describe the bug**
A while ago I was editting descriptions of packages,... and bolding, italic and underlined format was working just fine today when i tried to do the same I can use italic and underline just fine but the bold doesn't seem to work. This applies to packages and also appears to be the case for categories/pages.

**To Reproduce**
See above.

**Expected behavior**
The text to format like it should when using the buttons.

**Platform**
CraftingStore website

**Comment by Tim-NL** [comment]
Hello,

We have been unable to confirm this in the current editor. Would you be able to share what browser you are using?

-Tim
