### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by pricelessdev** [CraftingStore/Suggestions#263]
**Is your feature request related to a problem? Please describe.**

I'll give a specific plugin example, to explain better.

I have deluxe tags, the plugin where users can decide what tag themselves want to use as a prefix. 
But there is one problem because I can automatically create tags, but it needs a unique identifier.
The command itself is setup /tags create <unique id> <thetag>, but there is nowhere I can get anything unique from CraftingStore, I was first thinking about using their {player} Minecraft name, but if he purchases a second it will clash with the first purchase. This can be useful for so many other automated things as well in other plugins where users themselves can create things. 

**Describe the solution you'd like**
I want an additional option to {UUID}, {PLAYER} and so on, that's more unique and I think the best practice would be timestamps. 

**Additional context**

**Comment by Tim-NL** [comment]
Hello,

Thanks for your request.

We added the following new placeholders:

> {random_10} -> Random text of 10 characters.
> {random_20} -> Random text of 20 characters.
> {random_30} -> Random text of 30 characters.
> {execution_timestamp} -> The unix timestamp the command was executed, might not be unique when multiple commands are being run.

I'd suggest using the random_ placeholders, or use the timestamp combined with the playername. 

-Tim
