### ISSUE TITLE
Error in console connection time out

### ISSUE THREAD

**Issue by Trnrr** [CraftingStore/Suggestions#265]
**Describe the bug**
This shows in console sometimes, not sure what is the cause or how severe it is.
https://gist.githubusercontent.com/Trnrr/1b62cd3d973075339aa15c707b44860d/raw/6247ac029d2514500ad41abf0c1e02676d6133cc/gistfile1.txt

**To Reproduce**
I'm not sure it just happens sometimes

**Platform**
Sponge server

**Comment by Tim-NL** [comment]
Hello,

If this only happens sometimes, its no big deal. We had some large DDoS attacks to our platform, so some API requestes from your server might have been rate-limited. 

Does this still occur now? 

-Tim

**Comment by Trnrr** [comment]
Ok it was probably those ddos attacks then. I have not noticed it in quite a while. I will close the issue and if anything changes I will leave another comment. But it was probably like you said, since I have not seen it lately.
