### ISSUE TITLE
Color Codes dont work on minecraft when used in any form of message

### ISSUE THREAD

**Issue by EMcKee10** [CraftingStore/Suggestions#266]
**Describe the bug**
Im wanting my buyers to be able to set a custom rank via a product they can buy. so i set up a variable {RankTag} Which is the goes in the prefix tag of my permission manager (lucky perm) but whenever i execute the command with color codes in the variable i get a very strange set of characters. Example: I have a custom rank with the tag "&6TEST" being set by the variable {RankTag}. but whenever it executes the command, (lets just say its broadcast This is a &cTest {RankTag}) I get the following: [Broadcast] This is a Test mp;cTEST where the Test is in red (like expected) and the mp;cTEST is in green but i dont want mp;c to be there and i want the correct color code

**To Reproduce**
1. create a package with a command that will say something within your server. something like "broadcast This is a &cTest"
2. Make a manual sale so that the command executes. Make sure that you are on the server to observer what happens

**Expected behavior**
From the above text, you expect "This is a Test" to have the word "Test" in red coloring
However you end up with "This is a mp;cTest" in the normal broadcast color (Green)

**Platform**
Minecraft Plugin
Running on paper-300
We are running on a OVH Dedicated server, using a Ubuntu OS
I can confirm that the above doesnt work on a server run on windows either.
Also the same for Spigot
Noteable plugins:
Lucky perm (permissions manager)
CMI

**Additional context**
I was requested to put this into a bug report by Tim
Ticket #4663

**Comment by Tim-NL** [comment]
Thanks!

The issue has been resolved for the variables, they will now pass the & sign correctly. 

-Tim
