### ISSUE TITLE
[Bug] Incorrect coupon sale calculation

### ISSUE THREAD

**Issue by TimHeidinger** [CraftingStore/Suggestions#267]
Hi, 

this "Stack on top of sale (after)" coupon function doesn't calculate the new prices correctly. The coupon amount is applied on top of sale. Well, thats right. But the coupon amount seems to be calculated with the original price. Which doesnt't make any sence. It should be calculated with the sale price. 

Example:
```
=== Example #1 (how it is currently calculated) ===
Premium orginal price 20,00€
Premium sale price 15,00€

Customer uses 10% coupon. New price is: 13,00€
Because: You subtract 10% from 20,00€. Which is 2€. Then you put in on top of sale. Which is 13,00€

=== Example #2 (how it should be calculated) ===
Premium orignal price: 20,00€
Premium sale price: 15,00€

Customer uses 10% coupon. New price is: 13,50€
Because: You have to subtract 10% from 15,00€ sale price. Which is 1,50€. Then you put in on top of sale. Which is 13,50€
```

It doesn't make any sence to use the original price for these calculations, because the original price should be completly ignored.

Thanks Tim! :)

**Comment by Tim-NL** [comment]
Hi,
We have made modifications to the calculation a few weeks ago, and we have corrected some issues inside of this. This should fix the issue you've created.

-Tim
