### ISSUE TITLE
Cumulative Packages // Sale Discount Incorrect

### ISSUE THREAD

**Issue by ArathiaMC** [CraftingStore/Suggestions#269]
There is an issue with cumulative packages when sales are applied. For reference I have the following ranks:

Rank A: $9.99
Rank B: $19.99

So a user purchases rank A for $9.99 without any sale. The rank upgrade is now $10 due to the cumulative discount. But if a sale is applied, in this case, a 25% OFF sale, the price of this rank upgrade is now $5 instead of the intended $7.5. This effectively makes all rank purchases cheaper and there have been situations where expensive ranks have cost nothing but a few bucks.

1. Create two rank packages with different values. Make sure the category is cumulative.
2. Do manual payment for the first rank.
3. Go on your webstore and check the price without sale.
4. Go back to the store, apply a sale, and check the updated cumulative rank upgrade price with the sale. It will be less than expected.

**Comment by Tim-NL** [comment]
Hi,
We have resolved this issue some time ago, the calculation will now take in account the correct prices, even for sales.

-Tim
