### ISSUE TITLE
Discord Donation Broadcast

### ISSUE THREAD

**Issue by WalkingPixel1** [CraftingStore/Suggestions#270]
Might already be suggested but couldn't see any relating to this.

Possible to broadcast in a servers announcement channel that someone has donated.

**Comment by Dracconus** [comment]
I second this.  I'm not sure if it's a premium feature or not, but it would definitely be nice to see implemented.

**Comment by ZoneRaids** [comment]
i agree.

**Comment by Tim-NL** [comment]
Hi,
We offer this feature on our Gold plan, it is under [ Profile -> Notifications ]. Before it was not useful for server-wide broadcasts because it was not customizable, but now you can configure your own message. 

-Tim
