### ISSUE TITLE
WEbsite Category to GUI in-game

### ISSUE THREAD

**Issue by 10splaya** [CraftingStore/Suggestions#272]
Create the website to allow the user to re-organize the categories allowing the GUI in-game to look exactly how the website categories look. For example, instead of Ranks, Keys, and Rank Upgrades, in the website. Once the user moved the category, in this case Keys and Rank Upgrades. The order will now look like Ranks, Rank Upgrades, Keys. In-Game the Category will also change to Ranks, Rank Upgrades, and Keys. :)

**Comment by Tim-NL** [comment]
Store owners have the ability to create their own inventory from the website - Gold only

https://craftingstore.net/blog/the-inventory-update

As for the inventory by default, it should now respect the order from the website. 

-Tim
