### ISSUE TITLE
Slider-type package

### ISSUE THREAD

**Issue by kevin777787** [CraftingStore/Suggestions#273]
It would be cool if players could choose the amount of something with a slider. Instead of having multiple separate packages with 100 coins or 500 coins, you just have one package with a slider. The slider will automatically adjust the price for you when you change it. Players should also be able to set discount when a player bulk buys a certain item. So when a player for example buys more than 10000 coins, he, for example, gets 10% discount.

**Comment by Dracconus** [comment]
This isn't really a necessity given you have the capability within your package setup to "allow greater quantities" of an item, thusly the consumer would be able to simply edit the number of items they wish to purchase at once.

**Comment by Tim-NL** [comment]
Hi,
We'll have to decline this request, as this request is out-of-scope for the CraftingStore project, not for normal shopping systems, but it is for gaming servers in our belive. 

-Tim
