### ISSUE TITLE
Cyborg color schema quantity text color is white background is white as well

### ISSUE THREAD

**Issue by Dracconus** [CraftingStore/Suggestions#274]
On the Cyborg color schema the input field for 'quantity' is white, and the background is too.
I'd suggest this text color be changed to black to make it easily visible instead of having users select the text to view it once highlighted.
This can be seen below:
![image](https://user-images.githubusercontent.com/59084739/71246645-b438eb00-22dc-11ea-8731-0b8ddee7b91c.png)

**Comment by Tim-NL** [comment]
The issue has been resolved.

-Tim
