### ISSUE TITLE
Show parent categories of categories when choosing item categories

### ISSUE THREAD

**Issue by Vankka** [CraftingStore/Suggestions#277]
**Is your feature request related to a problem? Please describe.**
Show the parent category of categories when editing item categories

**Describe the solution you'd like**
Showing the parent before the subcategory, eg. "SkyBlock / Ranks"

**Additional context**
n/a

**Comment by Tim-NL** [comment]
Hi,
Since this issue was created, we have implemented a whole new category editor, that shows the packages in the correct order, in a tree. I believe this resolves this issue.

-Tim
