### ISSUE TITLE
Package giftcard option 

### ISSUE THREAD

**Issue by mlefeb01** [CraftingStore/Suggestions#278]
**Is your feature request related to a problem? Please describe.**
You are not able to limit whether a package can be purchased with giftcards.

**Describe the solution you'd like**
I would like an option added to packages where you can choose whether or not the package can be purchased with a giftcard.

**Additional context**
No additional context.

**Comment by Tim-NL** [comment]
Hi,

This issue is a duplicate issue with #145. I've closed this one, please see the other issue if you want to see updates.

-Tim
