### ISSUE TITLE
Suggestion for adding a currency section at store.

### ISSUE THREAD

**Issue by Heroruler** [CraftingStore/Suggestions#28]
**Is your feature request related to a problem? Please describe.**

Using only one type of currency for example only EUR is not that good for many reasons.
first if a player from a country that has not the same type of currency as EUR he would not know how much the item that he wants to buy is on his currency so he/she won't be able to buy it. He/She may don't know that he/she can buy with his/her currency the item even if the currency is different and Etc.
I hope you understand my point of the problem here.

**Describe the solution you'd like**

A solution would be to let the customer decide his/her currency by adding next to Shopping basket a button that when you click it a menu to appear with some different options of currencies for the customer to choose, for example there to be EUR, USD, GBP, AUD etc at the menu. Also, I suggest that to be added at all the plans free and premium. I hope that feature to be an addition to that great host, I think it will be useful.

**Additional context**
Here are some screenshots please go to that Link: https://imgur.com/a/B6YrRp6

**Comment by Tim-NL** [comment]
We are declining this request, sorry.

It is possible to select the global store currency. We have no plans on adding the ability for the client to see the exchange rates between different currencies at this point in time.

-Tim

**Comment by Scrulius** [comment]
idk why this option is not enable, because this in gonna migrate to Tebex...

**Comment by Tim-NL** [comment]
You can find the answer to your question in my previous reply. @Scrulius
