### ISSUE TITLE
Allow package name to be displayed without player name included

### ISSUE THREAD

**Issue by Kensharma** [CraftingStore/Suggestions#281]
Dear CraftingStore team,

I just moved from Tebex to CraftingStore and have a minor issue with the {package} placeholder. Can you add an option to make the package placeholder display ONLY the package name without the player name included at the end?

When the player name is included, the package name becomes too long and gets cut off on many devices. It also makes the players name show multiple times on Discord integration, in-game messages, e-mails, etc because they already list the player name who purchased separately.

This is how they currently look:
![image](https://user-images.githubusercontent.com/4781065/72695450-f1c4aa00-3b0e-11ea-84b0-9f8f87efba7a.png)

This is how they should look for clean integration:
![image](https://user-images.githubusercontent.com/4781065/72695505-1ae53a80-3b0f-11ea-936d-99f6519a0e2c.png)

I hope you will consider making this small change so that the package placeholders will be more clean and usable as they are on Tebex. Thanks for your time!

**Comment by Tim-NL** [comment]
The suggestion has been implemented. Thank you for adding it!

-Tim
