### ISSUE TITLE
Moet 'staat' verplicht invullen in NL

### ISSUE THREAD

**Issue by TastyBlueberry** [CraftingStore/Suggestions#284]
Mensen moeten verplicht de staat én provincie invullen als je Nederland als land selecteert bij de check-out, terwijl alleen het invullen van de provincie voldoende is. Het invullen van de staat is dus overbodig. Kan dat worden uitgeschakeld?

**Comment by Tim-NL** [comment]
Waar gebeurt dit? Op de shop zelf staat enkel:
```State / Province```
