### ISSUE TITLE
Manual Payments

### ISSUE THREAD

**Issue by RyderBelserion** [CraftingStore/Suggestions#285]
**Is your feature request related to a problem? Please describe.**
Its not a problem.

**Describe the solution you'd like**
Exclude manual payments from Top Donator & Recent Payments & Donation Tracking as when you had $10 to a manual payment, it adds on to the goal which is not accurate if the rank was a giveaway etc.

**Additional context**
None

**Comment by Tim-NL** [comment]
Hi,

You can configure the amount that will be counted when creating the manual payment. The donation goal will use this amount. If you set it to zero, it will not count towards it. This was not present when this issue was created, but it has been for some time.

-Tim
