### ISSUE TITLE
Abiltiy to change email format

### ISSUE THREAD

**Issue by ItzTalli** [CraftingStore/Suggestions#286]
Having the ability to change the format of emails sent to clients when purchase made. 

This is the email sent to acviate the discord roles. 

Emails is sent from crafting store. With just a link. Memebers are confused and worried what the email is for. 

I've had to mention to 50+ ppl what's it for so far. 

I'm aware you can edit the receipt format

**Comment by Tim-NL** [comment]
This has been implemented.

Please see this article for information on it: https://help.craftingstore.net/books/payment-gateways/page/using-custom-html-for-your-e-mails

-Tim
