### ISSUE TITLE
Minecraft Bedrock Edition implementation

### ISSUE THREAD

**Issue by EntenGamesNET** [CraftingStore/Suggestions#287]
**Is your feature request related to a problem? Please describe.**
Minecraft Bedrock Edition is becoming pretty big because its an cooperation between mobile, Windows 10, Nintendo Switch and PS4.

**Describe the solution you'd like**
There are several softwares for Minecraft Bedrock Edition like PocketMine(PHP) and Nukkit(Java).
So I would like to have an option to choose Minecraft Bedrock Edition for a store.

**Additional context**
/

**Comment by Tim-NL** [comment]
Hi,

We've tested Pocketmine-MP and it seems to support RCON just fine, we've tested it, and CraftingStore is able to execute commands on here out-of-the-box.

We've described how to set-up RCON on PocketMine-MP here: https://help.craftingstore.net/books/plugin-help/page/how-to-install-the-plugin#bkmrk-minecraft%3A-bedrock-%2F

We've also added "Minecraft: Bedrock" as a selectable game type for new stores, this will hide all other plugins that we offer, and just show RCON.

We might create a dedicated plugin in the future, so there can be a /buy menu, but at this point in time, we'll limit it to just command processing (the main focus of our platform).

-Tim
