### ISSUE TITLE
Price Placeholder Support for In-Game GUI

### ISSUE THREAD

**Issue by Savag3life** [CraftingStore/Suggestions#288]
**Is your feature request related to a problem? Please describe.**
Nope. just a new feature not currently implemented.

**Describe the solution you'd like**
A price placeholder you can use on the in-game item (DisplayName, and Lore) that will reflect the price of a package.
**Additional context**

**Comment by Tim-NL** [comment]
Hi,

Sorry for the delay, thanks for your suggestion!

We have the {price} placeholder in the in-game menu. This one does show the price, but it will not reflect the sales. 

-Tim
