### ISSUE TITLE
More Placeholders e.g.Top Donator of all time.

### ISSUE THREAD

**Issue by AaronInTheBox** [CraftingStore/Suggestions#289]
**Is your feature request related to a problem? Please describe.**
My server has a spot for our Top donator of all time as opposed to our top of the month.

**Describe the solution you'd like**
Extra placeholders for things such as all time top.

**Comment by Tim-NL** [comment]
Hi,

This is not something I want to implement at this time, due to it having to go through every payment you ever had, and ordering it by the price. For now, we will keep our current placeholders only.

-Tim
