### ISSUE TITLE
sub-category

### ISSUE THREAD

**Issue by jjj700** [CraftingStore/Suggestions#29]
**Describe the bug**
if you disable a sub-category it still shows in the dropdown menu

**To Reproduce**
1. Go to categories
2. Click on a sub Category
3. Scroll down to 'enable/disable this category
4. check your sub-categories on your store page

**Expected behavior**
people can see in disabled categories

**Screenshots**
N/A

**Platform**
website and probably in game

**Additional context**
N/A

**Comment by Tim-NL** [comment]
Duplicated with #52 (resolved).

Issue closed.

-Tim
