### ISSUE TITLE
Fix that you can't buy packagers lower then your package...

### ISSUE THREAD

**Issue by Jonawoning1** [CraftingStore/Suggestions#290]
**Is your feature request related to a problem? Please describe.**
Yes, it is a bugg that if you buy a package like VIP+ you can still purchase VIP.

**Describe the solution you'd like**
I want to have that if you buy a specific package that you cant purchase a package lower then that.

**Additional context**
Here a screenshot of what happens with this shitty ''bug''.

https://gyazo.com/2eafde006b1098f4e7692a957a7f2706

Greets, Jona

**Comment by Tim-NL** [comment]
Hi,
We have resolved this issue some time ago, but never updated this issue here. 

We'll make it as resolved now.

-Tim
