### ISSUE TITLE
Per-package fees

### ISSUE THREAD

**Issue by sampdevi** [CraftingStore/Suggestions#291]
So setting one fee for every package doesn't make it fair for higher and lower prices, I use PHP [Philippine Peso] as my currency and my lowest product is worth 50 PHP. so having a fixed fee of 25% wouldn't make up for paypal fees and etc. 
Paypal charges $0.30 [16~ in PHP] and 2.9% [1.45 in 50 PHP], resulting in 17.45~ PHP, all in all, 17.45 is 34.9% of 50 PHP, which means 25% wouldn't be enough.
Given another example, my highest priced product as of now, 300 PHP, 25% would be too much for it. 2.9% of 300 PHP is 8.7 PHP, adding the $0.30 [16~ in PHP], gives it all in all 24.7~ PHP.
25% for 300 PHP is 75. so I'm earning 50.3 PHP more than I should be.

In my case, I want to make it so that the charge is exactly how I want it to be, 2.9% of the price of the product.

 Please add this, it would be more convenient.

**Comment by Tim-NL** [comment]
Hi,

Thanks for the suggestion!

Unfortunately this is not a feature that we can implement. It's a very specific edge-case. I do not really see how a per-package fee would be different from raise the package prices (unless you have multiple payment gateways).

-Tim
