### ISSUE TITLE
[Feature] Money Changer

### ISSUE THREAD

**Issue by Rodaviva29** [CraftingStore/Suggestions#293]
Change in the Website what type of money you wanna see, like anyone want to see the Product in Dolars and one want in Euros. 
![FC533BEE-9EC9-4668-961A-BF612FE412DF](https://user-images.githubusercontent.com/52529400/76522046-d1093880-645d-11ea-9126-08a9a4e9a7a9.jpeg)

**Comment by Tim-NL** [comment]
We offer the ability for the store owner to update the currenty for the whole store. We are not planning on adding this from the store's side.
