### ISSUE TITLE
Subscription

### ISSUE THREAD

**Issue by lackoSK** [CraftingStore/Suggestions#294]
I would like to create a monthly subscription that players can subscribe to, but that option does not exist.

The ability to create a monthly subscription with packages.

**Comment by Tim-NL** [comment]
This request has already been suggested, and the required template has not been followed for the feature request.

**Comment by lackoSK** [comment]
when it will be added ?

**Comment by Tim-NL** [comment]
We have no ETA for this at this point in time.
