### ISSUE TITLE
Add more information to the exporter .csv files

### ISSUE THREAD

**Issue by mlefeb01** [CraftingStore/Suggestions#295]
**Is your feature request related to a problem? Please describe.**
My feature request is not related to a problem, the exported works perfectly I just want more information added to it.

**Describe the solution you'd like**
I would like more information added to the .cvs files output by the exporter feature. Examples of information I would like added include: coupon code (if any) and date of purchase. 

**Additional context**
The exporter feature is already a fantastic addition to the CraftingStore panel. Being able to download a .csv and analyze data is very valuable to any business model. Adding more detailed information such as coupon code and data of purchase would allow for more in-depth data analysis.

**Comment by Tim-NL** [comment]
Implemented.

The coupon will now be added to the export, if there is any, it will be empty if there is no coupon linked.

As for the date; This is already in the export under label "Date" in this format: 2019-02-17 14:04:22

-Tim
