### ISSUE TITLE
Adding more gateways

### ISSUE THREAD

**Issue by TerrorGamesOff** [CraftingStore/Suggestions#298]
**Is your feature request related to a problem? Please describe.**
If it's possible, i want to add Skrill for payment method, like Tebex

**Describe the solution you'd like**
More easier to pay with paysafecard/skrill. With mollie or PayGol you need a bussines, and the taxes are high.

**Additional context**
-

**Comment by Tim-NL** [comment]
Hi,
We have tried implementing Skrill, be we are currently not able to get into contact with them. We have tried multiple times. For now we are not able to implement Skrill.

-Tim
