### ISSUE TITLE
categorie drop down

### ISSUE THREAD

**Issue by jjj700** [CraftingStore/Suggestions#3]
**Is your feature request related to a problem? Please describe.**
hard to switch between categories

**Describe the solution you'd like**
 make it so on the sidebar you can drop down more than one category at once so instead of opening one then opening a new one and it closing it stays open

**Additional context**
https://gyazo.com/567d315224948f42fc79ef80badedb96

**Comment by Tim-NL** [comment]
Hello,

You can use different browser tabs for this, our platform is not able to "remind" the "opened" categories in the sidebar.

Or do you mean something else?

~Tim

**Comment by jjj700** [comment]
ok thx for your help. never mind.
