### ISSUE TITLE
Module Changes

### ISSUE THREAD

**Issue by Apyrax** [CraftingStore/Suggestions#30]
Instead of having the modules attached to the main body which depending on how many packages you have. It unnecessarily leaves a large amount of white space behind

Detaching the modules and having them be placed on the left or right side would be more appealing then having them combined with the main body. 

https://cdn.discordapp.com/attachments/387413673980723210/475492449649819654/unknown.png
![image](https://user-images.githubusercontent.com/32464690/43682106-03be291a-9837-11e8-9e9c-c59314123d22.png)

**Comment by Tim-NL** [comment]
This is the default template, if you require changes like these you can modify them on one of our premium plans, as such this "feature" already exists in the platform.

~Tim
