### ISSUE TITLE
Refresh problem

### ISSUE THREAD

**Issue by TerrorGamesOff** [CraftingStore/Suggestions#300]
**Describe the bug**
When someone donated the "Latest Donator" module didn't refresh. Actually all modules didn;t refresh when i modify something or someone donate. I tried to change the order of the modules, but it didn't work.

**To Reproduce**
1. -
2. -
3. -
4. -

**Expected behavior**
-

**Screenshots**

**Platform**
CraftingStore

**Additional context**
Store: https://donatii.terrorgames.ro/
Screenshots: https://imgur.com/a/5Ur2HkX

**Comment by Tim-NL** [comment]
The issue has been resolved.
