### ISSUE TITLE
Parent Category QOL

### ISSUE THREAD

**Issue by mlefeb01** [CraftingStore/Suggestions#301]
**Is your feature request related to a problem? Please describe.**
Yes, when you have multiple parent categories, their children are in no particular order in the packages menu and it is very hard to navigate. Also, there is no way to change the order of children categories in their parent category.

**Describe the solution you'd like**
I would like to be able to change the order children categories appear in the parent category and in the packages view, if a category is a child category, group it with other categories that share the same parent.

**Additional context**
No additional context

**Comment by Tim-NL** [comment]
Implemented.

You can now drag & drop the sub-categories just like the normal categories.

-Tim
