### ISSUE TITLE
Own mail design

### ISSUE THREAD

**Issue by ivenassenkamp** [CraftingStore/Suggestions#304]
**Is your feature request related to a problem? Please describe.**
Not really, it would only be nice to have

**Describe the solution you'd like**
I would like to be able to edit the entire mail and not just the text in the white area.

**Comment by Tim-NL** [comment]
Implemented.

Please follow this guide: https://help.craftingstore.net/books/payment-gateways/page/using-custom-html-for-your-e-mails

-Tim
