### ISSUE TITLE
Capitalization of Shopping "b"asket?

### ISSUE THREAD

**Issue by sharkaholic** [CraftingStore/Suggestions#307]
**Is your feature request related to a problem? Please describe.**
Could we maybe see concise capitalization on the Shopping Basket? Currently the B is lowercase, so it doesn't fit in with the other buttons.

**Describe the solution you'd like**
Fix the B! :)

**Comment by Tim-NL** [comment]
You can change it directly from [ Settings -> Language ]. Its called "Shopping basket" on the list. My personal preference is "Shopping basket", but you can change it from there.
