### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by SuchSvett** [CraftingStore/Suggestions#308]
The default theme doesnt scale after your screen its just same size for every screen so it doesnt fit to my screen as you can see here: https://gyazo.com/31cab46386878527da3e57d6df863af8 
the reason its black is because i use "dark reader" but it happens with it off aswell.
Thank you!

**Comment by Tim-NL** [comment]
Hi,

We have implemented a new dashboard theme since this issue was created. So this issue has since been resolved.

-Tim
