### ISSUE TITLE
Xsolla Payment Gateway

### ISSUE THREAD

**Issue by Roosteridk** [CraftingStore/Suggestions#313]
Xsolla is a superior alternative to Paymentwall. No review bs, more payment methods and less fees.

**Comment by Tim-NL** [comment]
Xsolla does not allow CraftingStore clients to sign up, we used to have Xsolla integration, but they kept redirecting our clients to other platforms. And they were not able to accept us as a partner. 

Thus for the moment, our Xsolla integration is disabled.
