### ISSUE TITLE
"No premium" cumulative packages problem

### ISSUE THREAD

**Issue by gwladyka** [CraftingStore/Suggestions#316]
**Describe the bug**
After "no premium" player buy one of cumulative packages, the discount is not shown in the category, but in the basket is. Also, purchased packages do not disappear from category. For premium players, there is no problem.

**To Reproduce**
1. Buy cumulative package as "no premium" player (cracked).
2. Go back to the cumulative packages category on your store.
3. See error.

**Expected behavior**
Correctly displayed discount in the category.

**Screenshots**
[https://youtu.be/SK86im9FND4](https://youtu.be/SK86im9FND4)

**Platform**
CraftingStore website

**Comment by ShaunaFurry** [comment]
i have the same issue

**Comment by Tim-NL** [comment]
Hi,

Thanks for the report! 
The issue has reproduced, identified, and resolved.

-Tim
