### ISSUE TITLE
Placeholders

### ISSUE THREAD

**Issue by BiggDaddyy** [CraftingStore/Suggestions#317]
**Is your feature request related to a problem? Please describe.**
Make some placeholders that works with LeaderHeads

**Describe the solution you'd like**
LeaderHeads currently only works with 'per player' leaderboards, e.g. '%kills%' returns your personal kills.
So you can do it like %craftingstore_donator% 1

**Comment by iDirtniverse** [comment]
Bump!

**Comment by BiggDaddyy** [comment]
No need found a half way around it 😂 servernpc can edit skin depinding on what placeholder tell it XD
