### ISSUE TITLE
Gifting Suggestion

### ISSUE THREAD

**Issue by CooliYT** [CraftingStore/Suggestions#318]
**Is your feature request related to a problem? Please describe.**
If someone wants to buy someone else a package, they have to put in the other player's name but they don't get the money added onto their own donation amount for the goal.

**Describe the solution you'd like**
I would like to have people on my store be able to gift packages to others. This would allow people to still have money added onto their total spent in the month/week.

**Additional context**
Perhaps when you click on "more info" on a package, instead of just showing "buy", it can also show "Gift"

**Comment by MatiasMunk** [comment]
I think this is a great idea.

**Comment by Tim-NL** [comment]
Hi,

This seems to be a duplicate with #232 - You can watch that issue for any updates.

-Tim
