### ISSUE TITLE
Variables problem

### ISSUE THREAD

**Issue by TerrorGamesOff** [CraftingStore/Suggestions#319]
**Describe the bug**
I've created a package where you can buy a Suffix. You can write what suffix do you want but CraftingStore execute the command with "mp;1". A player set his Suffix "&aAlpha"

**To Reproduce**
1. Create a Variable
2. Type something
3. Pay
4. Go to commands and you will see the problem

**Expected behavior**
-

**Screenshots**
https://imgur.com/a/GnSSmFf
Someone else had the same problem: https://imgur.com/a/pL6nt0e

**Platform**
CraftingStore website

**Additional context**
-

**Comment by Tim-NL** [comment]
Hi,

Sorry, I missed this issue. The issue was already resolved a few months ago.

-Tim
