### ISSUE TITLE
Transaction IDs

### ISSUE THREAD

**Issue by chaosworlds1** [CraftingStore/Suggestions#32]
**Is your feature request related to a problem? Please describe.**

I'm annoyed how limited the lookup feature is for the store admin panel

**Describe the solution you'd like**

Add transaction IDs to payments as well as the lookup feature so if a player has masked their ip or changed their minecraft name you can still track the payment and the player doesn't need to know the exact date/time, or their previous names, or what IP they had before.

**Additional context**

**Comment by chaosworlds1** [comment]
"the player doesn't need to know the exact date/time, or their previous names, or what IP they had before."

I didn't mean remove it I just meant those are limited in what they can do to help admins look up a specific transaction instead of needing a name/ip that admins may not even be able to find. However transaction ids can be sent with the purchase email sent to the user who bought something from a store, and if a user knows the transaction id it's easy to find it for the admin and help them out faster.

**Comment by Tim-NL** [comment]
We've added the option to search for transaction ID's, and made a change to our default receipt template to contain this transaction ID in future mails. 

You can find the template changes here:
https://github.com/CraftingStore/Templates/commit/f9a692437f3716ea490f14d11710dce5c6285da0

And here is the raw file:
https://raw.githubusercontent.com/CraftingStore/Templates/master/default/emails/receipt.html

~Tim
