### ISSUE TITLE
[FEATURE] New Manual Payment option

### ISSUE THREAD

**Issue by dieterblancke** [CraftingStore/Suggestions#321]
**Is your feature request related to a problem? Please describe.**
Yes, we are trying to switch stores and we want to use Cumulative packages. These however do not support manual payments so we want to have another option when creating a manual payment that allows you to count it as a real payment.

**Describe the solution you'd like**
A new option (checkbox) in manual payment create that asks "Count as real payment" which would make the Manual Payment count as a real one.

**Comment by Tim-NL** [comment]
Hi,

Sorry, I missed this issue. It has been resolved some weeks ago. Thanks for adding it!

We've made sure that manual payments also count as real payments now, as long as you set a price.

When creating the manual payment, you set what price the client paid. If you set the price to the same price as the package, then it will count as a real payment.

-Tim
