### ISSUE TITLE
IP checks

### ISSUE THREAD

**Issue by User4675** [CraftingStore/Suggestions#327]
**Is your feature request related to a problem? Please describe.**
Not really a problem I have had yet but just for the future and bigger servers what if someone that was banned from the store comes on another account.

**Describe the solution you'd like**
I would like IP checks so we can ip ban people from the store if necessary.

**Additional context**
It would be very helpful.

**Comment by Tim-NL** [comment]
Feature already exists, created by a misunderstanding from our side. Closed.
