### ISSUE TITLE
Template history

### ISSUE THREAD

**Issue by mhermanny** [CraftingStore/Suggestions#329]
Have a button that allows you to restore & view a **.html / .css** file at each modification.

**Comment by Tim-NL** [comment]
Hi,

This is out-of-scope for CraftingStore, so we are going to have to decline this request. If you want to keep track of changes you make to templates you can use a version control system like Git (Github can do it for free, even for private repositories). 

We use Github as well, to keep track of our template changes; https://github.com/CraftingStore/Templates/commits/master

Systems like Git are made for this and offer much better history & version control than we ever can.

-Tim
