### ISSUE TITLE
Per Package Giftcard Option

### ISSUE THREAD

**Issue by mlefeb01** [CraftingStore/Suggestions#330]
**Is your feature request related to a problem? Please describe.**
This feature is not related to a problem, it is just suggestion new functionality for giftcards. 

**Describe the solution you'd like**
I would like the option (per package) to choose whether a giftcard can be used on them or not. This would be useful because you dont want every single item on the store to be accessible via giftcards.

**Additional context**
I have no additional context

**Comment by MatiasMunk** [comment]
Stupid, things need to be accessible via giftcards if u bought em. You bought giftcard with money, as will you buy whatever u wish to block giftcard from with money.

**Comment by Tim-NL** [comment]
Hi,

We added support for disabling gift-cards on specific packages some time ago. But I was not aware of this suggestion. So this has been implemented. You can disable gift cards from the advanced tab.

Thanks for the suggestion!

-Tim
