### ISSUE TITLE
Cumulative Package feature

### ISSUE THREAD

**Issue by Esmaay** [CraftingStore/Suggestions#331]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
Can you add a feature so the cumulative packages, which already have been purchased, show in the list, but you can't buy them (so it's like you've bought the maximum amount of it)

**Additional context**
Not really

**Comment by JustAMatt** [comment]
A very sensible addition.

**Comment by Tim-NL** [comment]
Hi,

Thanks for the suggestion!

The feature has been implemented, you can enable it from the category editor page, this will still show the package, while hiding the "buy now" button at the modal that comes up. So they can still see the package details.

-Tim

**Comment by Esmaay** [comment]
It does not hide the "buy" button, so this allows you to buy lower packages.
