### ISSUE TITLE
When putting `&` in a variable, it comes out as `&amp;`

### ISSUE THREAD

**Issue by matthewjk123** [CraftingStore/Suggestions#332]
I created a few custom variables for users to be able to purchase their own tags on the website and they would be created automatically and then assigned to them. If they decide to use Minecraft Chat formatting in their tag, when the tag is created, it appears like this
`  TestTag:
    order: 27
    tag: '&amp;0Test Tag'
    description: '&f'
    permission: deluxetags.tag.Test Tag`

I just need the & to display as an `&` instead of `&amp;` so that way Minecraft can understand it.

**Comment by Tim-NL** [comment]
Resolved.

& will no longer get replaced to &amp;

-Tim

**Comment by Tim-NL** [comment]
Now the issue is resolved.

-Tim
