### ISSUE TITLE
Easier template editing

### ISSUE THREAD

**Issue by PandaZGaming** [CraftingStore/Suggestions#333]
**Is your feature request related to a problem? Please describe.**
I get frustrated having to constantly re-open my .css file when editing my template.

**Describe the solution you'd like**
A "return" button near the "save" button so it doesn't keep closing my editor and so I keep track where I was and what I was editing.

**Additional context**
Nope :)

**Comment by Tim-NL** [comment]
Implemented.

The page will now not redirect you away from the file you're editing.

-Tim
