### ISSUE TITLE
Apply Coupon After Sale

### ISSUE THREAD

**Issue by mlefeb01** [CraftingStore/Suggestions#334]
**Is your feature request related to a problem? Please describe.**
This feature is not related to a problem

**Describe the solution you'd like**
I would like the option for a coupon to apply to a package price after the sale has been applied. 

**Additional context**
I have no additional context

**Comment by Tim-NL** [comment]
Hi,

We already offer the requested feature, you can enable it at the coupon creator. You can set coupon to stack on top of sales, so it will apply the discount after other discounts.

-Tim
