### ISSUE TITLE
Customizable Discord command Mail

### ISSUE THREAD

**Issue by EffeDion** [CraftingStore/Suggestions#338]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like to see a possibility to change the look and text in the Mail that you get when you add a Discord command to a package
[![Screenshot from Gyazo](https://gyazo.com/402010db4d746bcc54e91ddd96860bd6/raw)](https://gyazo.com/402010db4d746bcc54e91ddd96860bd6)
So i would like to see that you can change this to what you want ( For example add your own server name etc. )

**Additional context**
...

**Comment by Tim-NL** [comment]
We have moved the Discord role section to the receipt mail. 

Changes: https://github.com/CraftingStore/Templates/commit/2c7c1e1688e1f46fb7b9800c43be6224f86eff57
New file: https://raw.githubusercontent.com/CraftingStore/Templates/master/default/emails/receipt.html

With any premium plan, you are able to modify the full HTML of the receipt mail, and thus also of the Discord roles section now.

For stores that have an active template at the moment, we've added a new option to the settings -> webstore section and enabled it by default. This makes sure that nothing changes for stores using custom templates until they have modified their receipt.html to include the changes. Then they can disable the option, and the mails will be combined.

-Tim
