### ISSUE TITLE
The monthly goal is missing an important feature

### ISSUE THREAD

**Issue by plebexer** [CraftingStore/Suggestions#340]
The monthly goal needs a feature to set the date the goal resets, because, i actually have to pay my host not at the end of the month, so if a goal was reached last month, then i pay the host, and it still looks like i reached the goal, so people think i already reached the goal for the next month when i did not.

**Comment by Shulkershell** [comment]
For this, you could see if you could do some deal with the host where you pay for x amount of days to shift your payment date to the first of the month ^-^, but do see your point mine is midway through to

**Comment by Tim-NL** [comment]
Hi,

The suggestion above might work indeed, it's worth a shot. For now, we will not implement this, when you pay your server is not really useful information to your players. You would not receive more money, the amount would be the same. 

As long as the goal is reached every month, you have enough money, it does not matter when you pay it, as long as the box is full. And if you'd have to pay the15th of each month, then you'd still have a 1 month time between them, so this should not pose any issues.

-Tim
