### ISSUE TITLE
Gold plan feature

### ISSUE THREAD

**Issue by JamesF2001** [CraftingStore/Suggestions#343]
I'm recently upgraded to Gold and I'm loving it so far.. I think a lovely new feature to add would be the option to edit how the embeds look with the Discord Notifications Feature. To add maybe our own storename instead of payment received on CraftingStore and maybe some color options and just overall more customization to fit to each persons server best.

Thank you :)

**Comment by Tim-NL** [comment]
Hi,

This has been implemented. You can now enter your own message and use placeholders (see: https://help.craftingstore.net/books/premium-features/page/discord-payment-notification)

You can also modify the title now.

-Tim
