### ISSUE TITLE
Stripe more payments

### ISSUE THREAD

**Issue by TheDutchEestar** [CraftingStore/Suggestions#344]
Op t moment kan je dus alleen credit card betalingen via stripe doen terwijl je daar juist zonder kvk van veel betaalmethodes kan genieten.

het zou leuk zijn als er zeker voor de nederlandse, duitse en belgische betaling systemen ook support zou komen

**Comment by Tim-NL** [comment]
Please use the format provided for feature requests - And ask your question in English.
