### ISSUE TITLE
Payment methods

### ISSUE THREAD

**Issue by M1SM4TCH** [CraftingStore/Suggestions#35]
Good morning all good?
I'm from Brazil.
I know that you probably will not accept, however, it would be very good to include Brazilian payment methods in CRAFTINGSTORE.
I know that PaymentWall has some, however, it charges some extra fees.
The methods I would recommend would be PagSeguro (the most used in the country) and PicPay.
(https://pagseguro.uol.com.br/)
(https://ecommerce.picpay.com/)
Just a suggestion, thanks for your attention.

**Comment by Tim-NL** [comment]
Hello,

I'm sorry but due the low amount of stores possible using this gateway, we have to decline the request for the time being. We might re-consider adding county specific gateways in the future. 

~Tim
