### ISSUE TITLE
Command Placeholder Unique Identities

### ISSUE THREAD

**Issue by telegraphical** [CraftingStore/Suggestions#350]
I am currently working on a plugin which confirms a player's package on my server to prevent people charging back on each other.

This is done by packages having to be confirmed in game by my plugin before they can receive any of the awards - admitting they know if the package is charged back on they will be blacklisted. I have managed to get this far working using CraftingStore - but the problem comes with the chargeback command.

The problem is there is no unique identifier which is passed through the command in my plugin to store it - as there are currently no command placeholders for it. This means there is no way for me to link a chargeback to a specific purchased package from the store, and therefore my custom chargeback command has no way of deciding who to ban.

To solve this I would like either the transactionID (or any random unique identifier) to be able to be passed through a placeholder for initial commands and chargeback commands - meaning there is a way to link items via my plugin to what items are charged back on - so I can only ban the players which have actually claimed the packages.

**Comment by Tim-NL** [comment]
Hi,

We implemented the {transactionId} placeholder, this will be a unique string that will be the same for all commands in a payment. 

-Tim
