### ISSUE TITLE
Global MC name and basket placeholders

### ISSUE THREAD

**Issue by Raymond2112** [CraftingStore/Suggestions#351]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
Would like to have '{{ mcName }}' placeholder (or an alternate placeholder) to be made for global use which wouldn't be limited just to the basket/checkout page.

As well as basketItems placeholder to be available for global use.

**Additional context**
Have a theme that requires those features, specifically. User Hub, that checks if user is logged in or not on every page. Example image below:
https://i.imgur.com/qCMNwx1.png

**Comment by TheMonDon** [comment]
I use lightmarket and and it uses player.name which works, so I don't think you need mcName just change it to player.name

**Comment by Tim-NL** [comment]
player.name / player.uuid are indeed available on all pages, I was not aware of that placeholder. You may use that one.
