### ISSUE TITLE
Add options to ignore manual payments from specific modules

### ISSUE THREAD

**Issue by RyderBelserion** [CraftingStore/Suggestions#352]
**Is your feature request related to a problem? Please describe.**
No problem.

**Describe the solution you'd like**
Add options to ignore manual payments for "Donation Goal and "Top Donator" Module

**Additional context**
None.

**Comment by Tim-NL** [comment]
Hi,
We believe that there is no need for this, as you can set the price paid in manual payments. If you set it to zero, it will not show up in either of those two modules. 

-Tim
