### ISSUE TITLE
Bitcoin Payments (without Paymentwall)

### ISSUE THREAD

**Issue by Lexxonist** [CraftingStore/Suggestions#353]
**Is your feature request related to a problem? Please describe.**
No major problem other than the fact that I cannot take Bitcoin payments through Craftingstore and I rather not use Paymentwall if possible.

**Describe the solution you'd like**
I would like to receive Bitcoin and Ethereum payments preferably directly sent to my wallet addresses rather than through the use of a third-party service such as Paymentwall.

**Comment by Tim-NL** [comment]
Hi,
After looking into the options, we are currently sticking with our current gateways. We must handle it through a third party at this point in time because we do not want to take responsibility for handling conversions between currencies. As currencies like these can shift pretty fast.

-Tim

**Comment by Shybella** [comment]
Taking Crypto would be great
