### ISSUE TITLE
Better color picker for text editor

### ISSUE THREAD

**Issue by HeckiYT** [CraftingStore/Suggestions#354]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to go to the HTML part of the text editor to choose the color I want because the default colors look horrible.

**Describe the solution you'd like**
I'd really like a new text editor where I can paste the color code I want or at least add nicer looking colors to the default palette like the [minecraft colors](https://minecraft.gamepedia.com/Formatting_codes#Color_codes)

**Comment by Tim-NL** [comment]
Hi,

Are you talking about the command colors? Those are not HTML colors, they are the same colors used in-game in your Minecraft server. You can look up the colors by googling them, and there are only a few of them, so I do see no need to create a color selector for this at the moment.

If you are referring to something else, please let us know, for now, I'll close the issue.

-Tim

**Comment by HeckiYT** [comment]
No, I mean the color picker for the shop item description

**Comment by Tim-NL** [comment]
Those only support Minecraft color codes, not HTML color codes. For now, we'll have to decline the request due to the reasons stated above.

-Tim

**Comment by HeckiYT** [comment]
I mean this thing here
![grafik](https://user-images.githubusercontent.com/40500858/89796106-85041200-db29-11ea-8ce1-e5473c6f58d6.png)

**Comment by Tim-NL** [comment]
Yeah, I was notified that you were talking about that one. We can unfortunately not change this selector, as this is the one in our WYSIWYG editor, we cannot modify it, sorry.

This selector is directly from the editor, and we are not looking at changing this.

-Tim
