### ISSUE TITLE
Forge Server Side mod 

### ISSUE THREAD

**Issue by DrewSin-4** [CraftingStore/Suggestions#356]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated at the fact that all purchases require intervention from Staff and Players rather than being automated.

I personally don't use Sponge, Bukkit, Spigot, etc, due to the fact it tends to not work well with Modded Servers and certain mods and migration to Sponge and stability work would take much longer than is reasonable.

**Describe the solution you'd like**
Port the CraftingStore Server Plugin to a Server Side mod for 1.12+ (1.12.2+ Modded Servers are quite popular at the moment) featuring the same functionality without the need for additional APIs.

**Additional context**
Tebex currently offer this sadly for only 1.13 and we are loving CraftingStore much more in comparison to Tebex.

Tebex Git: https://github.com/tebexio/Tebex-Forge

**Comment by Tim-NL** [comment]
We do currently not have plans on porting our plugin to Forge. I recommend you to use our RCON server type, this is present in all Minecraft server types, including their Vanilla server. 

The limitation here is that you will not be able to use our /buy menu (but you can still make one using another mod). 

-Tim
