### ISSUE TITLE
Auto delete bot message.

### ISSUE THREAD

**Issue by Flumess** [CraftingStore/Suggestions#358]
**Is your feature request related to a problem? Please describe.**

I dont know if I would consider this a problem. But for our donator claim chat we want to keep the chat clean except for a message explaining how to claim your role. Right now the bot messages dont get deleted. 

**Describe the solution you'd like**

I would like to see the bot message get deleted after X amount of seconds. I think 30 seconds or so is a good time for the bot message to auto delete itself.

**Additional context**

**Comment by Tim-NL** [comment]
Hi,

We've implemented a new system, where no command is required. Thus, this is no longer a "issue", and is herby marked as resolved.

Thanks for the suggestion tho! 

More Information: https://help.craftingstore.net/books/general/page/discord-integration

-Tim
