### ISSUE TITLE
NoPremium cant buy or see cumulative

### ISSUE THREAD

**Issue by ShaunaFurry** [CraftingStore/Suggestions#360]
**Describe the bug**
my users nopremium/cracked cant buy or see your next rank with discount
or add items to checkout

**To Reproduce**
1. Introduce Nopremium name how Juliii__ next select package and try buy and cant

**Expected behavior**
can buy

**Screenshots**
https://www.youtube.com/watch?v=50e4h1jdG3w

**Platform**
Bungeecord minecraft server

**Additional context**
my webstore is nopremium mode and test with default template

**Comment by Tim-NL** [comment]
The issue has been resolved, it was caused by the user-limit misbehaving when used for cracked players.

-Tim

**Comment by ShaunaFurry** [comment]
no are solved
