### ISSUE TITLE
Limit Request

### ISSUE THREAD

**Issue by Aarpn** [CraftingStore/Suggestions#362]
This is a Limit Suggestion

So, I was looking at the support discord earlier, and was wondering if its possible if you could maybe add a way to set a max limit, where you could set a max item limit of 3 for an item, but you can obviously change it per item. I know you can remove it but I dont wanna remove it as some thing I want people to buy as much as they want, but with monthly crates etc, I wanna make it max of 3 per month etc

**Comment by Tim-NL** [comment]
You are already able to create user limits & global limits for each package, with specific time frames. Or is this not were you are referring to? (see the advanced tab).

**Comment by Tim-NL** [comment]
No response received, the issue is now closed due to lack of information.

-Tim
