### ISSUE TITLE
pls add unturned as a server option

### ISSUE THREAD

**Issue by User46751** [CraftingStore/Suggestions#363]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Can you add unturned as a server option as I run one but I can't use you for it.

**Additional context**
none

**Comment by Tim-NL** [comment]
The issue is not filled in correctly, please fill in the issue and correct the title (do not include things like "plz"). You can mention me here when you have done so, so I can re-open the issue.

-Tim
