### ISSUE TITLE
Gift card suggestions 

### ISSUE THREAD

**Issue by 3oa** [CraftingStore/Suggestions#365]
**Is your feature request related to a problem? Please describe.**
Yes, I this request is related as it is hard to work out how to use coupons correctly as It is confusing when you have a sale active.

**Describe the solution you'd like**
I would like there to be an option to make gift cards for only curtain categories or make it so you can enable/disable vouchers to be used for package/category 

**Additional context**
Make it like the enable feature, call it ‘vouchers’ then have an on and off switch

**Comment by Tim-NL** [comment]
Hi,

Thanks for your suggestion! It is now possible to select the packages/categories that your card may be used on. 

-Tim
