### ISSUE TITLE
Package Lookup [EXTREMELY NEEDED!]

### ISSUE THREAD

**Issue by Sacha-PvP** [CraftingStore/Suggestions#366]
Please add a feature in the webstore where we can check how many of each individual package has been sold with each payment gateway within a certain timeframe! This is extremely needed!!!

Thanks!

**Comment by Tim-NL** [comment]
We have added a "package" selector to the lookup page, it works for payments created from today. 

We also have our export feature, you can export the payments to a .csv file and use software like Microsoft Excel to easily filter it on both package, and creation date, and even per gateway. 

-Tim

**Comment by Sacha-PvP** [comment]
We truly appreciate this.

Is there any way you can provide a permission node to block the ability to
view statistics for certain users? This would be very helpful.

Thanks,
Sacha

**Comment by Tim-NL** [comment]
We can, but could you please create another Github issue for it, so it does not get mixed together? Please use the template when creating it. 

-Tim
