### ISSUE TITLE
A one-time-payment option (like MinecraftMarket had)

### ISSUE THREAD

**Issue by LiamBinLaden** [CraftingStore/Suggestions#37]
I think CraftingStore should implement a one-time-payment for the Silver plan. It'll dramatically increase sales for one, and you'll be giving the clientele of your platform a hand - especially those on a tight budget and looking for a viable option against Buycraft or any other platform - be the better, not the same.

**Comment by Tim-NL** [comment]
Hello,

We will stick with our monthly subscription for now, adding a "one time payment" for premium features will increase the sales one time, and after that we will not receive any income, as such the platform can't survive. 

~Tim

**Comment by LiamBinLaden** [comment]
You will receive income due to the Gold Plan.

**Comment by Tim-NL** [comment]
I can see the statics, the income from those packages is not enough to cover the server & development costs of the platform, I'm really sorry but I can't accept this request.
