### ISSUE TITLE
Gift-Cards Improvement

### ISSUE THREAD

**Issue by aZaOcean** [CraftingStore/Suggestions#371]
**Is your feature request related to a problem? Please describe.**
No, it's not related to a problem.

**Describe the solution you'd like**
Why don't you improve the gift-card features and make it so we can sell gift cards in the webstore automatically? Like there should be an option on the page where you create a package and make it so when a player purchases a specific package, a gift-card is automatically generated and sent to the buyer email address. Also, can you make it so we can _optionally_ add an expiration date for the gift card?

**Additional context**
That's something Tebex.io has, you should look into it. It's a great feature.

**Comment by MatiasMunk** [comment]
This is a new plugin that auto generates the Gift Card and sends it to the player. Additionally it also sends the code to the player's email (used during purchase) with a pretty HTML Template, that is editable.
https://www.spigotmc.org/resources/craftingstore-gift-card-extension.83243/

**Comment by Tim-NL** [comment]
Hi,

We have implemented the ability to buy gift-cards in store. You can find out how here; https://help.craftingstore.net/books/premium-features/page/selling-gift-cards-on-your-store

-Tim
