### ISSUE TITLE
Items increase

### ISSUE THREAD

**Issue by Aarpn** [CraftingStore/Suggestions#372]
**Is your feature request related to a problem? Please describe.**
I think its stupid how with a sale or coupon active you can only purcahse 1 of the item, kinda the downfall of using craftingstore (even tebex allow this)

**Describe the solution you'd like**
Make a way to allow people to add multiple items when using coupons or sales, kinda the downfool for this store, it would be so much better if you can do this, Please.

**Additional context**

**Comment by Tim-NL** [comment]
Could you please attach to your ticket, the way you want us to implement this? As mentioned on Discord; 
```If you have a suggestion on how we can do it, feel free to add it to our suggestions board. This tradeoff is currently the best I could come up with.```

**Comment by Aarpn** [comment]
What I mean tim, as in Buycraft, idk how you can do it, but you could add for quantity with the code you can put multiple, or even, if you allowed it so you can add multiple of same item, like rn, if I put 1 of a item it wont let me go through the process of adding a second one, just, I do coupon payouts for my server and I know for a fact people will wanna buy multiple of certain items

**Comment by Tim-NL** [comment]
Hi,

Thanks for your suggestion! 

It is now possible to modify the quantity, even when a coupon/gift-card is active.

https://help.craftingstore.net/books/others/page/custom-template-new-basket-format.

-Tim
