### ISSUE TITLE
Rank system

### ISSUE THREAD

**Issue by BiggDaddyy** [CraftingStore/Suggestions#375]
**Is your feature request related to a problem? Please describe.**
okay i just moved from tebex and they i needed to put every purchase into your system and then people can't upgrade there rank because your system don't see that they have made a purchase and got the rank that i put into the system

**Describe the solution you'd like**
look into what rank the player have on the server or in the system and not look for its a purchase or manual inset or a option to enable and disable the way it looks into it :)

**Comment by Tim-NL** [comment]
Hi,
Our plugin currently works one-way, it fetches information from the dashboard. Storing all ranks every user has, for every server, is out of scope for a shared platform. As it would be too much data to take from every server and store it on our servers.

-Tim
