### ISSUE TITLE
Dark Mode on CraftingStore Dashboard

### ISSUE THREAD

**Issue by sxphirus** [CraftingStore/Suggestions#376]
**Is your feature request related to a problem? Please describe.**

I've always found it difficult to use pages that don't natively support dark mode, and despite using a multitude of different "dark mode" plugins on my web browsers they always run into issues, Crafting Store is one of the sites they tend not to work with, so i believe this should be added as a default feature regardless.

**Describe the solution you'd like**

Dark mode to be available as a default option on the CraftingStore Dashboard,

**Additional context**

Thank you :)

**Comment by Tim-NL** [comment]
We have dark mode, you can enable it by clicking on your name at the top right corner, and then on "Switch to dark mode".

-Tim
