### ISSUE TITLE
Custom mail-server disable his self

### ISSUE THREAD

**Issue by Sundeep-deJongh** [CraftingStore/Suggestions#379]
**Describe the bug**

**To Reproduce**
1. Go to 'https://craftingstore.net/admin/settings/receipt'
2. Click on 'update receipt settings'

**Expected behavior**
De "custom mail-server" disable his self

**Screenshots**
nvt

**Platform**
Craftingstore (Admin dashboard)

**Additional context**
nvt

**Comment by Tim-NL** [comment]
Hi,

We have found the reason for it being disabled. The receipts feature is a gold feature, it will disable itself when you try to enable it on any lower plan. We added a check, so you cannot enable it with plans below the Gold plan. 

Thanks for the report.

P.S. "nvt (niet van toepassing)" is Dutch.

-Tim
