### ISSUE TITLE
Package Creation/Edits via Config/TextEditor

### ISSUE THREAD

**Issue by PokeHub** [CraftingStore/Suggestions#380]
**Is your feature request related to a problem? Please describe.**
Yes. At the moment, it takes FOREVER to add a significant number of packages.

**Describe the solution you'd like**
I love the UI and all you have to edit/add packages. However, clicking through so much does get tedious at times when adding a TON of packages. Having some kind of text editor for packages would make it SIGNIFICANTLY easier to work with hundreds of packages. Being able to mass edit, replace, etc. using a text editor would save an incredible amount of time.

Just like... an Import/Export Package button, that allowed us to add or change packages as we choose. 

**Additional context**
I'm not sure how much sense that made, but even though it would be a bit more.. complex at first than UI, it would allow people to edit/create packages MUCH faster once you did understand it.

**Comment by Tim-NL** [comment]
Hi,
We've looked at the request, and for now, we are going to decline it. I believe that the work required to create this does not reflect the user's benefit. This is only helpful for a small number of servers that have huge numbers of packages.

-Tim
