### ISSUE TITLE
a overall placeholder

### ISSUE THREAD

**Issue by BiggDaddyy** [CraftingStore/Suggestions#383]
Is your feature request related to a problem? Please describe.
its just i don't get donations every month so it would be nice with a placeholder that can show the total amount of donations so my donations stand won't stand empty the month where people don't donate :)

Describe the solution you'd like
a placeholder that can say who donated the most in all time and not only pr month

**Comment by Tim-NL** [comment]
This is not something I want to implement at this time, due to it having to go through every payment you ever had, and ordering it by the price & it not being very useful, as newer players would never be able to get on top of that list.

-Tim
