### ISSUE TITLE
Add expiry support for Discord roles

### ISSUE THREAD

**Issue by zydde** [CraftingStore/Suggestions#385]
**Is your feature request related to a problem? Please describe.**
On my store, there's an option to get Donor rank for only 1 month, at a cheaper price. I've set it to take away the in-game rank after a month, but I can't set it to get rid of the Discord role after a month.

**Describe the solution you'd like**
I'd like the feature to remove a Discord role once the rank expires.

**Additional context**
/

**Comment by Tim-NL** [comment]
Duplicate with #364

-Tim
