### ISSUE TITLE
Statistic Permission

### ISSUE THREAD

**Issue by Sacha-PvP** [CraftingStore/Suggestions#387]
**Is your feature request related to a problem? Please describe.**
This feature request is simply a permission node in the highest package of crafting store to limit the ability to view statistics of sales, etc. for certain users. 

**Describe the solution you'd like**
Please implement a permission node to limit the viewing of monthly, weekly, daily, etc. sales 

**Additional context**
N/A

**Comment by Tim-NL** [comment]
Hi,

We have implemented the statistics permission to the roles feature for team accounts. The option is on the bottom of the page, you can also enable/disable it for existing roles that you have. Thank you for reporting this.

-Tim

**Comment by Sacha-PvP** [comment]
Hey Tim,

I granted this permission to one of my users, and it doesn’t work. I
disabled the node, and they are still able to see the weekly/hourly/monthly
earnings. Please fix this ASAP. thanks!
