### ISSUE TITLE
Basket tab title is not showing

### ISSUE THREAD

**Issue by clementinise** [CraftingStore/Suggestions#388]
**Describe the bug**
The tab title for the basket is not showing (Only the site name and "|" are showing)

**To Reproduce**
Steps to reproduce the behavior: (For my store at least)
1. Go to your basket
2. See error

(You can test on my site: https://mc.funwise.fr/checkout/basket)

**Expected behavior**
Title for this page showing correctly 

**Screenshots**
![image](https://user-images.githubusercontent.com/35346472/90429406-f3b31380-e0c5-11ea-9a37-1da95d89ce81.png)
![image](https://user-images.githubusercontent.com/35346472/90429420-f877c780-e0c5-11ea-9196-33cf44d92fb1.png)

**Platform**
Crafting store website (https://mc.funwise.fr/)

**Additional context**
\\\\\\

**Comment by smessie** [comment]
Side info: This does not seem to be a custom template related bug, as I can reproduce this on my store with the default template enabled.

**Comment by Tim-NL** [comment]
Hi,

Thanks for the report, the issue is fixed, it will now use the basket name translation as it should.

-Tim
