### ISSUE TITLE
Hex colors in /buy menu

### ISSUE THREAD

**Issue by MattGodwin** [CraftingStore/Suggestions#389]
**Is your feature request related to a problem? Please describe.**
I find it annoying that the /buy menu can't support hex color codes.

**Describe the solution you'd like**
Add hex colors to /buy menu as they did in essentialsX.

**Additional context**
![image](https://user-images.githubusercontent.com/68249412/90645535-f4ff5000-e22d-11ea-9a3d-fd10eb6ad57c.png)

**Comment by Tim-NL** [comment]
Hi,

It seems like its not possible to add support for HEX colors in the menu's. When we pass give it a hex color, it replaces it with a random color from the original Minecraft colors. 

But we can add HEX support to the chat messages, we have a new version that has support for this, we'll release it in the coming days. 

-Tim
