### ISSUE TITLE
Discord Notification Bug

### ISSUE THREAD

**Issue by Villmarksjenta** [CraftingStore/Suggestions#390]
**Describe the bug**
Discord notification when someone makes a purchase, gives a pressable word (Shop), and on the notification the pressable word sends you to Admin Panel. This also may show the purchase's payment info etc. Members should not be able to press this and possibly see others payment info. 

**To Reproduce**

**Expected behavior**
Wither remove the pressable link, or make an option so you can turn it off/give permissions. 

**Screenshots**

**Platform**
Discord Server linked to Craftingstore website

**Additional context**

**Comment by Tim-NL** [comment]
Hi,

We have disabled the link in notifications. Thank you for the report!

-Tim
