### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Volgeop** [CraftingStore/Suggestions#392]
**Describe the bug**
Hi, this bug appeared in console, I'm not sure why https://pastebin.com/5aREeVC6.

**To Reproduce**
Like I said, I don't know exactly, why it happened. All I know is that anyone can't use /buy command now, so it's not related to menu, I just have this plugin installed on my two backend servers.

**Expected behavior**
This error prob. shouldn't happen.

**Platform**
Minecraft plugin (2.3.0) on Paper 1.16.1, ver 137

**Comment by Tim-NL** [comment]
Hi,

This error means that your server is not able to communicate with our API endpoint. Would you be able to create a support ticket on our dashboard (https://craftingstore.net/admin/support/create) and mention your server IP so we can check if we are blocking it, or something like that? 

-Tim
