### ISSUE TITLE
[GAME BREAKING BUG] Double items coming through store

### ISSUE THREAD

**Issue by Sacha-PvP** [CraftingStore/Suggestions#393]
**Describe the bug**
When a player purchases an item from the store, often times, the item will be doubled after being purchased once. E.G. "Player" purchases 3 keys, they receive 6 .

**To Reproduce**
1) Purchase an item from a store
2) Wait until it is doubled

**Expected behavior**
I expect the item not to be doubled

**Screenshots**
N/A

**Platform**
I believe it occurred on the MC plugin. we are running 1.7.10. 

**Additional context**
N/A

**Comment by Tim-NL** [comment]
Hi,

Can you please create a support ticket regarding this issue from your account? This is not a platform issue, I expect it to be a configuration issue. 

-Tim
