### ISSUE TITLE
Package Lookup is Broken

### ISSUE THREAD

**Issue by Sacha-PvP** [CraftingStore/Suggestions#395]
**Describe the bug**
The package lookup simply does not work. 

**To Reproduce**
1. Go to lookup packages'
2. Select a package
3. Select a timeframe date
4. Wach it not work

**Expected behavior**
Expected to show the purchases of the identified package within the given timeframe

**Screenshots**
https://gyazo.com/8e6fa1d99531e2cc74d10ae06c95faf7

**Platform**
Occured on store

**Additional context**
N/A

**Comment by Tim-NL** [comment]
Hi,

Does this also occur when you do not select a package? And just lookup by timeframe. 

-Tim
