### ISSUE TITLE
"Pay what you want" in translations doesn't work

### ISSUE THREAD

**Issue by Volgeop** [CraftingStore/Suggestions#396]
**Describe the bug**
Hi, I translated my "Pay what you want" string in lang. options, but on my web I can't see it translated. And it should be OK in lang. file https://media.discordapp.net/attachments/422510039916609552/747821797663309905/unknown.png.

**To Reproduce**
1. Translate Pay what you want.
2. See if it's translated.

**Expected behavior**
It should be translated.

**Platform**
CraftingStore

**Additional context**

**Comment by Tim-NL** [comment]
Hi,

The placeholder will now use the correct text. Thanks for your report.

-Tim
