### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Innesity** [CraftingStore/Suggestions#397]
**Is your feature request related to a problem? Please describe.**
My feature request isn't related to a problem. 
**Describe the solution you'd like**
I want a feature that will let us (server owners) to enable/disable the link in discord notification webhook new donation received

**Additional context**
Nope. Hope you will implement this soon, I really need this.

**Comment by Tim-NL** [comment]
Hi,
You can now enable the link once again from the [ Profile -> Notifications ] page. 

-Tim
