### ISSUE TITLE
EDIT modules/topdonator.twig button

### ISSUE THREAD

**Issue by Volgeop** [CraftingStore/Suggestions#398]
**Describe the bug**
Hi, when I click to EDIT button in template for "TOPDONATOR_MODULE.TWIG", then is opened "BUYERS_MODULE.TWIG".

**To Reproduce**
1. Go to Design/Templates/Edit specific template (https://craftingstore.net/admin/twigtemplates)
2. Find modules/topdonator.twig
3. Click on edit
4. Then instead of topdonator module is opened buyers module (but when clicking on it's name, on topdonator module name, it opens normally, just edit button is broken).

**Expected behavior**
It should open right module to edit.

**Platform**
Craftingstore

**Comment by Tim-NL** [comment]
Hi,

The edit button will not redirect you to the correct page as well (will be live in about 15 minutes). 

Thank you for the report!

-Tim
