### ISSUE TITLE
email receipt

### ISSUE THREAD

**Issue by jjj700** [CraftingStore/Suggestions#4]
**Is your feature request related to a problem? Please describe.**
makes your store more professional and customers get proof of payment.

**Describe the solution you'd like**
when the customer buys something, send them an email you have customised saying thank you for buying it and what they have bought like an email receipt

**Additional context**
N/A

**Comment by Tim-NL** [comment]
The mail on payment has been released (for silver+ stores only at this moment), you can enable it from the store settings
(https://www.craftingstore.net/admin/settings/webstore).

The mail template can be edited from the template editor, and this is the default template;
https://raw.githubusercontent.com/CraftingStore/Templates/master/default/emails/receipt.html

~Tim
