### ISSUE TITLE
In the commands are "č" replaced via "?"

### ISSUE THREAD

**Issue by Helomi** [CraftingStore/Suggestions#40]
**Describe the bug**
When you create some kind of message with "č" on the website is replaced via "?".

**Comment by Tim-NL** [comment]
Where do you require these chars? 

~Tim

**Comment by Helomi** [comment]
Its requiered in command for example:
/broadcast Hráč %player% si kúpil VIP
Translated:
/broadcast Player %player% just bought VIP

**Comment by Tim-NL** [comment]
Hello,

The issue has been resolved. 

- Tim
