### ISSUE TITLE
Placeholder {cost} in Discord webhooks

### ISSUE THREAD

**Issue by bobhenl** [CraftingStore/Suggestions#400]
**Is your feature request related to a problem? Please describe.**
Hi, could you please add way to specific also placeholder for {cost}, when I set notifications enabled on Discord in my profile? Only the problem is that these which have access to this room don't see, how much it costs.

**Describe the solution you'd like**
Adding {cost} placeholder to Discord webhook integration (this one in user settings for notifications).

**Comment by Tim-NL** [comment]
Hi,

We've added the {price} placeholder, this will show the price of the payment that was made.

I've added it to the knowledge base as well; https://help.craftingstore.net/books/premium-features/page/discord-payment-notification

-Tim
