### ISSUE TITLE
Modernize the "Checking your browser" gateway

### ISSUE THREAD

**Issue by ZeotYT** [CraftingStore/Suggestions#402]
**Is your feature request related to a problem? Please describe.**
This is a general suggestion to improve the polish and professional appearance of all CloudProtected products (and CraftingStore shops, specifically)

**Describe the solution you'd like**
You guys did an awesome job re-branding CraftingStore recently to look and feel more modern, polished and premium. One area that seems to have been overlooked is the CloudProtected "Checking your browser" gateway. This gateway is automatically used on all CraftingStore shops and I believe a few minor updates to the appearance of this page could modernize it and bring it in line with the rest of the recent CraftingStore re-brand. Perhaps a new modern font (like the new CraftingStore brand font), an update to the loading animation, etc. This gateway is the only part of my shop that still feels "dated" and "cheap" and I'm sure many shop owners would appreciate the quick update. Really appreciate all your great work on the platform recently, keep it up!

**Additional context**
Competitors (like CloudFlare) could be used as a reference/benchmark

**Comment by Tim-NL** [comment]
Hi,

Thanks for your suggestion!

Would you be able to provide some suggestions? In our opinion, the Cloudflare one looks pretty dated, we'd really appreciate some suggestions on this. 

-Tim

**Comment by ZeotYT** [comment]
Sure, no problem! I agree, CloudFlare isn't great either. Here's a quick mockup I made:
![image](https://user-images.githubusercontent.com/4781065/92287234-8d106100-eedf-11ea-90e6-e449476690cf.png)

The font used is Lato:
https://fonts.google.com/specimen/Lato

Also, the CloudProtect logo could spin or bounce to create some movement.

**Comment by ZeotYT** [comment]
![image](https://user-images.githubusercontent.com/4781065/92287284-c052f000-eedf-11ea-839d-437a59879a20.png)

**Comment by ZeotYT** [comment]
![image](https://user-images.githubusercontent.com/4781065/92316560-42204780-efcc-11ea-8e48-e3964827e28c.png)
![image](https://user-images.githubusercontent.com/4781065/92316561-49dfec00-efcc-11ea-87f9-ee37aa836561.png)
Quick side-by-side comparison

**Comment by Tim-NL** [comment]
Hi,

We'd be able to do something like this; https://assetscdn.cloudprotected.net/cloudprotected/test/ddos-loader.html - This is just the raw HTML loader, it will not do any of the checks or redirects.

We've created it based on your design, and CloudFlare's. 

We did not include the checkmark icon for two reasons;
1. We do not want to "endorse" anything by potentially showing it as something that users might see as "verified". 
2. The response should be as small as possible, as this will be returned to thousands of bots/second when we're under heavy attack (this happens a few times a week).

Do you have any feedback for us?

-Tim

**Comment by ZeotYT** [comment]
> Hi,
> 
> We'd be able to do something like this; https://assetscdn.cloudprotected.net/cloudprotected/test/ddos-loader.html - This is just the raw HTML loader, it will not do any of the checks or redirects.
> 
> We've created it based on your design, and CloudFlare's.
> 
> We did not include the checkmark icon for two reasons;
> 
> 1. We do not want to "endorse" anything by potentially showing it as something that users might see as "verified".
> 2. The response should be as small as possible, as this will be returned to thousands of bots/second when we're under heavy attack (this happens a few times a week).
> 
> Do you have any feedback for us?
> 
> -Tim

Hey Tim, that looks fantastic, much more modern than the current loader! I totally understand your point on the checkmark, I didn't really think of that at the time.

As far as feedback goes, I think it could be improved with 2 minor tweaks:
- consider swapping the font for something more sleek, perhaps you could use the exact same font used on the main CloudProtected site, "Source Sans Pro" (https://fonts.google.com/specimen/Source+Sans+Pro)
- to align with standard practice and the 3 dot loading animation, use "Just a moment..." and "redirect shortly..."

But those are just minor nitpicks. Nice work on that!

**Comment by Tim-NL** [comment]
Hi,

I've updated the font on it; https://assetscdn.cloudprotected.net/cloudprotected/test/assets-loader.html
I also added one dot to the message. I did not add the other sentence, because it must not be a 1/1 copy of other services.

Thanks for your clear & constructive feedback, I really appreciate it. 

-Tim

**Comment by ZeotYT** [comment]
> Hi,
> 
> I've updated the font on it; https://assetscdn.cloudprotected.net/cloudprotected/test/assets-loader.html
> I also added one dot to the message. I did not add the other sentence, because it must not be a 1/1 copy of other services.
> 
> Thanks for your clear & constructive feedback, I really appreciate it.
> 
> -Tim

Looks fantastic, excellent job on this! This should be a much appreciated update for CloudProtected customers. This looks better than CloudFlare loader in my opinion...

By the way, just to clarify, the "Just a moment..." is referring to the page title, because the page title also uses 2 dots instead of 3 at the moment ("Just a moment.."). That wasn't meant to be a new sentence, sorry for the confusion!

**Comment by Tim-NL** [comment]
Ah I see, thanks, updated that as well on our local version. We'll look into deploying it shortly.

-Tim
