### ISSUE TITLE
Idea for {amount} placeholder

### ISSUE THREAD

**Issue by Jxliet** [CraftingStore/Suggestions#403]
**Is your feature request related to a problem? Please describe.**
A bit, regarding crate keys. If someone buys 19 keys, it will execute the command 19 times, therefore spamming the chat of the player with "Crate key has been received" because of how most crate plugins work. It'd just spam the chat, and if you have a Donation message, it would send that 19 times/

**Describe the solution you'd like**
Basically, a mode near the "Enable this package" or under it, where you can change it to an item that requires a placeholder in order to work, that placeholder would be {amountbought} or {amount}. The placeholder would read how many packages of that specific package you bought, so if the command to give a single crate key would be **crazycrates give P Mythical 1 {player}**, we could change **1** with **{amount}** so it changes the placeholder into the amount of packages bought and then would only execute the command once.

Example:
I buy 19 crate keys, but instead of it spamming my chat 19 times, it only sends 1 message saying "You have received 19 crate keys". It would help in certain cases where you would be able to buy a package multiple times.

**Additional context**
Old Example:
I buy 19 crate keys, it spams my chat with 19 messages saying I just got a crate key AND it also spams 19 donator messages

My idea for a fix:
I buy 19 crate keys, but because I have the {amount} placeholder aswell as the mode set to execute 1 command only, it sends 1 crate key message and 1 donator message

If this needs any further explanation, I'd be glad to show a picture demonstration on Discord. Juliet#0001

**Comment by Tim-NL** [comment]
Hi,

Thanks for the feature request!

We have implemented it into the package editor, you can enable the feature by setting the option to "on" under the advanced tab. The option you are looking for is: "Run commands once for multiple package payments (you can use {amount} in commands)".

You can then use {amount} in your commands, this will be the number of times the user bought the item.

-Tim
