### ISSUE TITLE
[Feature] New payment gateway for "Micropayment"

### ISSUE THREAD

**Issue by timhed** [CraftingStore/Suggestions#404]
Hi,

I would like to process payments with "Micropayment" in the future. They offer payment via. bank transfer, paysafecard, paypal, and more.

Website:
https://www.micropayment.de/?lang=en

Integration guide for developers: You will find it on their website.

Would be very important for me. Thanks!
Tim

**Comment by Tim-NL** [comment]
Hi,

After looking into this payment method, we've decided to not implement it. 

A few gateways that we offer; PayPal, Stripe, Mollie, and Terminal3. These include almost all payment methods that Micropayment offers. We see no real need for another "global" payment method at this moment. As we already support a few.

-Tim
