### ISSUE TITLE
Payment Description

### ISSUE THREAD

**Issue by ivenassenkamp** [CraftingStore/Suggestions#406]
**Is your feature request related to a problem? Please describe.**
We often have the case that we have events where we raffle off/give away purchasable products. Since we want to have everything around the products in one place, we enter this directly in the store as a new payment, it would be useful if we could add a comment there so that the next person knows how the person came to this "luck".

**Describe the solution you'd like**
An option to set a description when creating a manual payment and or add a description later

**Comment by Tim-NL** [comment]
Hi,

Thanks for your suggestion!

We've added the "notes" box to the manual payment creator.

-Tim
