### ISSUE TITLE
Removing Roles via Discord Actions in Packages Not Working as Expected

### ISSUE THREAD

**Issue by meowsome** [CraftingStore/Suggestions#407]
**Describe the bug**
I have 3 packages that assign and remove roles from Discord. There is 1 role for each package and one general "Donator" role on the Discord server. When purchasing any of the 3 packages, it attempts to assign the general donator role, assign the role specific to the package they're purchasing, and remove the other two package's roles, just in case they've had them before. I've had several users who have purchased from my store report that all roles appear to be added regardless if I have them set to be removed or not. So, they end up with all 4 roles at the same time when they should only receive the general donator role and the role for the package they purchased.

**To Reproduce**
1. Make a package to assign some roles and remove some roles on Discord, none of which the user has on Discord
2. Purchase the package
3. Run the Discord command given in the confirmation email
4. All roles are added to the user, even if they are set to be "Removed" on Craftingstore

**Expected behavior**
The roles that are set to be removed should be removed, even if the user doesn't have them.

**Screenshots**
![image](https://user-images.githubusercontent.com/20958440/93096369-4c001580-f672-11ea-95d7-21cbe8f04313.png)
(The name of this package is "Hydra". the Hydra and general donator roles are supposed to be assigned, and the other two roles belonging to the other two packages are supposed to be removed. However, they all get assigned.)

**Platform**
CraftingStore website

**Comment by Tim-NL** [comment]
Hi,

Thanks for reporting the issue. We have resolved the issue, new claim commands will now respect the option to remove the role, instead of adding them.

-Tim

**Comment by meowsome** [comment]
Thanks for the super speedy response. Unfortunately it doesn't appear to have any changes for me. See attached video.

https://imgur.com/EkLyXWd

**Comment by Tim-NL** [comment]
Hi,

Thank you for the feedback. You are correct, we made the required fixes and tested them on our testing environments, but we never restarted our job workers on the production version. This caused the workers to use old (cached) versions. It should now be resolved. Sorry for the inconvenience. 

-Tim

**Comment by meowsome** [comment]
Awesome, thanks so much.
