### ISSUE TITLE
Add referral data to payment

### ISSUE THREAD

**Issue by TotalBennage** [CraftingStore/Suggestions#408]
Currently, when a customer enters a referral user at checkout, the referral data is only used in a command sent to the Minecraft server.

It would be really useful if this information was included in the transaction history and visible in the payment export .CSV 

Extra points if this is also included in the discord webhook.

**Comment by Tim-NL** [comment]
Hi,

You'll now see the "Referred By" field on the payment show page, the export, and you can use the following placeholder in the Discord notifications: {referredBy}.

Thanks for your suggestion!

-Tim
