### ISSUE TITLE
More details in the Discord Webhook

### ISSUE THREAD

**Issue by TotalBennage** [CraftingStore/Suggestions#409]
Currently, the Discord webhook only states Name, Gateway and Package.

It would be extremely useful if the webhook contained the rest of the information that is gathered during the checkout procedure.  In particular, the amount paid for each package (particularly useful if 'pay what you want' is turned on).

This will allow use of other third party integration via webhook, Zapier etc.

**Comment by Tim-NL** [comment]
Hi,

We added the {price} placeholder, this will be the total payment price for the basket. It is only possible to get the combined price, as no real logic is possible in the Discord notification editor.

-Tim

**Comment by TotalBennage** [comment]
Hi Tim,

Could you add the referral user to the hook also?

**Comment by TotalBennage** [comment]
...also the email address?

**Comment by Tim-NL** [comment]
Hi,

We've added "referred_by", "email", and "timestamp" (unix timestamp) to the webhook.

-Tim
