### ISSUE TITLE
Buy as a gift

### ISSUE THREAD

**Issue by TerrorGamesOff** [CraftingStore/Suggestions#411]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
Players can buy packages for other players like a gift. When you purchase a package you should have "Buy as a gift" option, enabling this option you should enter the nickname of the player you want to give the gift to.

**Additional context**
-

**Comment by Tim-NL** [comment]
Hi,

This feature request already exists !318

We'll update that issue if we implement this.

-Tim
