### ISSUE TITLE
Coupons addition

### ISSUE THREAD

**Issue by Aarpn** [CraftingStore/Suggestions#413]
**Is your feature request related to a problem? Please describe.**
I want it so that I can put the ign of the person who can use this coupon and if they dont use that ign then they cannot use it

**Describe the solution you'd like**
Add a thing to creations of coupon that says IGN: once you put in their ign it will only allow the person whos ign it is to use that coupon

**Additional context**

**Comment by Tim-NL** [comment]
Hi,

You can use gift-cards for this purpose, you can share those with just one user. Coupons are meant for global things and such.

-Tim
