### ISSUE TITLE
Feature suggestion for crafting store

### ISSUE THREAD

**Issue by Kacktide** [CraftingStore/Suggestions#414]
As we know Crafting store is better than tebex from way far I would like to suggest something that will make the CraftingStore handier and more useful.

 First of all, add a package resizing option so you can fit it nicely. Add a table system for packages (more likely for ranks). There will be an option to add a table for the packages (if there are more than 1 packages). You can add rows, column and much other stuff.

Also if possible add featured package module  :)

This is just a suggestion. If you could add it we ALL will highly appreciate it. by far I've found CraftingStore better than tebex or enjin. This is cheap, easy, User-Friendly and THE BEST. That's all I got.

:)

**Comment by Tim-NL** [comment]
Hi,

Thanks for your compliment and suggestions.
"First of all, add a package resizing option so you can fit it nicely. Add a table system for packages (more likely for ranks). There will be an option to add a table for the packages (if there are more than 1 packages). You can add rows, column and much other stuff."
You can do anything you like using the template editor, the HTML/CSS editor is made for stores that want to do things like these. The current grid/list views are good for a large part of the stores, and the ones that want more options, can use the template to do anything they like. So this is already something that you can do. 

"Also if possible add featured package module :)"
Duplicate with #73 - We'll update that issue if we implement it.

-Tim
