### ISSUE TITLE
Add new gateway (Razer Gold) 

### ISSUE THREAD

**Issue by DarrienNN** [CraftingStore/Suggestions#415]
**Add New Gateway Razerpay/gold**
Maybe this will make everyone more easy to purchase something they want in our webstore

**Can you guys add razer gold gateway in craftingstore?? **
Because in my country some of player are still using razerpay/gold to purchase something they want, if add this razerpay/gold maybe i will dont need to manual add payment in craftingstore and set player rank. (Country: Malaysia)

**Comment by Tim-NL** [comment]
Hi,

We only add real payment gateways, Razer Gold seems to be an unnecessary middleman that collects money in exchange for Razer Gold using a normal payment method, and that "gold" can then be used to buy items somewhere else.

This type of payment method is not something we'd consider adding at this point in time.

-Tim
