### ISSUE TITLE
Commands into sales

### ISSUE THREAD

**Issue by LattyPvP** [CraftingStore/Suggestions#416]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add commands into sales, so if a sale is live and someone buys something while the sale is live it will send the command that it has.

**Additional context**

**Comment by Tim-NL** [comment]
Hi,

Thanks for your suggestion.

We have decided to decline this request, as there is no easy way for store owners to configure this. As there are too many variables. Like, what server should be used, and when it should be used.

-Tim
