### ISSUE TITLE
Suggestion/bug

### ISSUE THREAD

**Issue by Hipopotofobia** [CraftingStore/Suggestions#42]
I noticed that when imputing the names of different color wools (ex: BLUE_WOOL) into the item part of the package creator it would not work. It seems that only WOOL is useable. Not sure if this also happens with other items like dyes or not but if this could be fixed/added it would be really helpful.

**Comment by Tim-NL** [comment]
The issue has been resolved in the BETA V2 version of the plugin. 

-Tim
