### ISSUE TITLE
Allow "CustomModelData" when choosing in-game material items.

### ISSUE THREAD

**Issue by VergilPrime** [CraftingStore/Suggestions#420]
**Is your feature request related to a problem? Please describe.**
I'm selling custom skins for existing items to fall in line with Microsoft/Mojangs EULA regarding selling of cosmetic only items or features that don't provide a gameplay advantage. It's a requirement then for the icons in the store to represent these skins.

**Describe the solution you'd like**
Adding a Material CustomModelData (ingame) to both package listings and category listings under the material and amount would be helpful. This should take an integer between 0 and 9999999. This would set the CustomModelData value in the metadata on the item, therefore rendering a different model/image client side so long as the player has a matching item in their resource pack.

**Additional context**
Mock-up made using in-browser dev-tools
![image](https://user-images.githubusercontent.com/1651211/96499972-fc79b000-1202-11eb-8e9c-8b5362c72196.png)
Mock-up made using TrMenu
![image](https://user-images.githubusercontent.com/1651211/96500097-35198980-1203-11eb-8ed6-ce541fa9f0cb.png)

**Comment by Tim-NL** [comment]
Hi,

Thanks for your suggestion.

We have implemented this in the latest version of the plugin, @thijsa has provided you with the plugin through Discord. We'll update it later on all channels. 

-Tim
