### ISSUE TITLE
Category in receipt mail

### ISSUE THREAD

**Issue by EffeDion** [CraftingStore/Suggestions#421]
**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solution you'd like**
A option in the receipt mail that you can add the category of the package the player bought.

**Additional context**
.

**Comment by Tim-NL** [comment]
Hi,

It is, unfortunately, not possible to implement this, as a receipt is a global payment, and that might contain multiple categories. Sorry.

-Tim
