### ISSUE TITLE
Community Goal API request

### ISSUE THREAD

**Issue by markusew** [CraftingStore/Suggestions#422]
**Is your feature request related to a problem? Please describe.**
I'd like this API cause I want to make the community goals visible in game.

**Describe the solution you'd like**
Well basicaly a API for plugins to use and read community goal information and do whatever with.

**Comment by axilirate** [comment]
+1

**Comment by Lorenzostuy** [comment]
Yes add this, we neeeeeeeeeeeeeed this
Literally bought StoreStats for the community goal

**Comment by StevenWintery** [comment]
> Yes add this, we neeeeeeeeeeeeeed this
> Literally bought StoreStats for the community goal

Same here

Please @Tim-NL this would be incredibly useful

We need 2 things for this to work:
1) Able to read  the current number of the goal
2) Able to read the "max amount" of the goal

**Comment by Danieljunek17** [comment]
Bump

**Comment by AlonsoAliaga** [comment]
I think this is a really important feature that should be added.
Would be nice if it's added to plugin API and end point for https requests

**Comment by Tim-NL** [comment]
Hi,

Thanks for the suggestion, we've implemented the "community goals overview" endpoint to our alpha v7 API. 

Documentation: https://docs.api.craftingstore.net/api/community-goals

-Tim

**Comment by HexedHero** [comment]
> Hi,
> 
> Thanks for the suggestion, we've implemented the "community goals overview" endpoint to our alpha v7 API.
> 
> Documentation: https://docs.api.craftingstore.net/api/community-goals
> 
> -Tim

"{"success":false,"message":"At least the Silver plan is required","data":[],"meta":[]}"

Not sure if intended.

**Comment by Tim-NL** [comment]
> > Hi,
> > Thanks for the suggestion, we've implemented the "community goals overview" endpoint to our alpha v7 API.
> > Documentation: https://docs.api.craftingstore.net/api/community-goals
> > -Tim
> 
> "{"success":false,"message":"At least the Silver plan is required","data":[],"meta":[]}"
> 
> Not sure if intended.

Thanks! All my testing accounts are silver, so I did not notice this while testing it. It will work on every plan in about 10 minutes.

-Tim

**Comment by HexedHero** [comment]
Only one of my goals is showing up on the API, the one I added days ago. The two I added just now don't show.

**Comment by Tim-NL** [comment]
Could you create a support ticket please, so we can check at your specific store? Our API is in "alpha" state, as described at the homepage, so issues like these are indeed possible. 

Thanks!

-Tim

**Comment by HexedHero** [comment]
> Could you create a support ticket please, so we can check at your specific store? Our API is in "alpha" state, as described at the homepage, so issues like these are indeed possible.
> 
> Thanks!
> 
> -Tim

Can't reply to the ticket I made but turns out the goals API only updates when you get or add a new payment, it doesn't update on goal creation or deletion.

**Comment by Tim-NL** [comment]
Yeah, I figured, you can reply to it by replying to the mail you got. I'll keep the ticket (not here), and I'll fix it later today. I'll update your ticket when the issue is resolved.
