### ISSUE TITLE
Import payment from another CraftingStore

### ISSUE THREAD

**Issue by sxphirus** [CraftingStore/Suggestions#424]
**Is your feature request related to a problem? Please describe.**
Merging two CraftingStores or moving from one CraftingStore to another is currently impossible, as carrying across data from one to the other can only be done manually (not viable when there are 500+ payments)

**Describe the solution you'd like**
The ability to import payments & the items purchased into another store, if the rank doesn't exist on the new store the user should be able to choose an appropriate rank to replace it with (e.g. a VIP rank doesn't exist on a store so you would be able to select the "iron" rank instead)

**Comment by Tim-NL** [comment]
Hi,

We have looked into this, and this is currently not a feature that we are going to implement.

After looking at the work involved, and the benefit for store owners, we think this is not something worth implementing.

Merging two CraftingStore shops is something that rarely happens, so to spend 10+ hours on developing a feature for this is not worth it in our opinion.

-Tim
