### ISSUE TITLE
Featured Package

### ISSUE THREAD

**Issue by JoshBecconsall** [CraftingStore/Suggestions#425]
**Is your feature request related to a problem? Please describe.**
It'd be good, like buycraft, to see a module for featured packages. You this'd show like any other module but a specific package of choice, maybe it would be cool to see multiple featured packages on one module but in a carousel so they automate every 10-30 seconds. 

**Additional context**
[https://prnt.sc/vabgyj](https://prnt.sc/vabgyj)

**Comment by Tim-NL** [comment]
Duplicate with #73
