### ISSUE TITLE
Theme darkly text(close button) suggestion fix

### ISSUE THREAD

**Issue by Shulkershell** [CraftingStore/Suggestions#427]
**Is your feature request related to a problem? Please describe.**
On theme darkly the close button on a buy item matches similar to the button color meaning dark screens or people with eyesight problems may not be able to see what the button performs

**Describe the solution you'd like**
Change the white text on the close button to a dark contrasting color eg: black or blue 

**Additional context**
![image](https://user-images.githubusercontent.com/58005153/98422694-5217de80-2084-11eb-85e4-ee64f523591a.png)

**Comment by Tim-NL** [comment]
Hi,

Thank you for the report, the issue has been resolved.

-Tim
