### ISSUE TITLE
TimeStamped Commands

### ISSUE THREAD

**Issue by Driftay** [CraftingStore/Suggestions#428]
**Is your feature request related to a problem? Please describe.**
A Feature Request

**Describe the solution you'd like**
Can we get a panel addon so we can see when the commands were issued. Like the time format.

**Additional context**
https://gyazo.com/74174b75b8b9cbd6cb49f8ece39cabbc

But with a timestamp next to it

**Comment by Aarpn** [comment]
100% agree

**Comment by Tim-NL** [comment]
Hi,

Thanks for your suggestion!

We've added the creation date to the commands section of the payment page. It will be live in about 15 minutes.

-Tim
