### ISSUE TITLE
Suggestion (Limiting Packages)

### ISSUE THREAD

**Issue by Hipopotofobia** [CraftingStore/Suggestions#43]
**Is your feature request related to a problem? Please describe.**
Feature/Suggestion

**Describe the solution you'd like**
Add the ability to limit an amount of a package that can be bought per hour/day/month/year per person or globally

**EX:** Limiting key alls to 3 times a day per key all globally

**Comment by Tim-NL** [comment]
Hello,

The feature has been implemented, you can edit/add this in the packages edit/create page. 

-Tim
