### ISSUE TITLE
NamelessMC Integration

### ISSUE THREAD

**Issue by xxnukzxx** [CraftingStore/Suggestions#430]
**Is your feature request related to a problem? Please describe.**
Hi, it is not exactly related to a problem. I'd like for store-wide sales to be able to show on my namelessmc-integrated store page. I was told by support to put in a request here to see if it'd be possible.

**Describe the solution you'd like**
If possible, make the prices for packages update on the namelessmc store if a store-wide sale is active. 

**Additional context**
This is essentially what i'd like each package to look like during a sale:
https://i.snipboard.io/z3aPuN.jpg

**Comment by Tim-NL** [comment]
Hi,

We decided to keep our NamelessMC integration pretty basic, because adding support for something like sales would require a fair bit of work, and we want our NamelessMC integration te be just a "gateway" of sorts.

So we'll have to decline this request.

-Tim
