### ISSUE TITLE
Simple Typo Fix

### ISSUE THREAD

**Issue by noodlelandmc** [CraftingStore/Suggestions#431]
**Describe the bug**

The checkout page has a typo. 
![image](https://user-images.githubusercontent.com/72227742/98841604-5a6e7180-2416-11eb-9de9-7def952a25ec.png)

**To Reproduce**
1. Go to the checkout page after adding an item to the cart

**Expected behavior**

It should be:

 I agree to the CraftingStore Terms Of Service and allow CraftingStore to process my data in this way, and hereby confirm that I'm over the age of 18, or have permission from my guardian.

**Screenshots**

![image](https://user-images.githubusercontent.com/72227742/98841604-5a6e7180-2416-11eb-9de9-7def952a25ec.png)

**Platform**
The platform the problem occurred on. Ex. the CraftingStore website or the Minecraft plugin. 
In case of the Minecraft plugin, please list the details of the environment, such as server type, version.

CraftingStore website

**Additional context**

**Comment by Tim-NL** [comment]
Hi,

Would you be able to create a support ticket for this? I think you are referring to the "\" in the message. This does not seem to happen in our test stores. So it seems to be something we'll have to look into on your store specificly. 

0Tim
