### ISSUE TITLE
New Variables for Discord Payment Notification.

### ISSUE THREAD

**Issue by EffeDion** [CraftingStore/Suggestions#432]
**Is your feature request related to a problem? Please describe.**
Not really, Just something nice for us to keep track of.

**Describe the solution you'd like**
Price and Category added to variables for discord payment notifications. 
https://help.craftingstore.net/books/premium-features/page/discord-payment-notification

**Additional context**

**Comment by Tim-NL** [comment]
Hi,

We've added the {price} placeholder.

The category is not possible, because not all packages are from the same category. A payment contains multiple packages, and can thus have multiple categories.

-Tim
