### ISSUE TITLE
Add Payment Gateways to Taiwan

### ISSUE THREAD

**Issue by gstio86** [CraftingStore/Suggestions#433]
**Is your feature request related to a problem? Please describe.**
Need to add payment methods to Taiwan, which would make the platform highly compatible and thus reach more taiwan customers

**Describe the solution you'd like**
Most of our players do not have a credit card or paypal, most of which are achieved by going to a convenience store to pay on their behalf
The most common collection platform in Taiwan is Ecpay, which supports the methods I mentioned above
I tried Tebex and DonationStore, but they never added any gateway to Taiwan, so I was very disappointed
Hope this is my last chance, if you need me to test, you can contact me

[Ecpay](https://www.ecpay.com.tw/Service/API_Dwnld) 

**Additional context**
Ecpay only needs the user to provide MerchantID, HashKey, HashIV
Developers can check the API doc they provide
1.API & Example : https://github.com/ECPay
2.Doc : https://www.ecpay.com.tw/Content/files/ecpay011EN.pdf

**Comment by Tim-NL** [comment]
Hi,

We've looked into this payment method, and this is currently not something that we can implement.

The main reasons are;
1) We cannot read their documentation, thus it will be very hard to implement this.
2) We do not really implement local payment methods, we only really implement global ones, like PayPal, or Stripe. 

Sorry about this.

-Tim
