### ISSUE TITLE
Manual Payments not working for RUST

### ISSUE THREAD

**Issue by EffeDion** [CraftingStore/Suggestions#434]
**Describe the bug**
When making a manual payment and using the UUID or Playername the payment isnt working.

**To Reproduce**
1. Payments > Manage
2. Create Payment
3. When you are on that page you got an Ingame Name. But that name counts as a Minecraft Username so when using the username it will grab the minecraft UUID to execute the commands.
4. No real error it just doesnt work. 
[Crafting Store] Executing Command: oxide.usergroup add 490da12ab03c41c0a6298de66e8f5bbd vip
Thats what it outputs in console ^

**Expected behavior**
Either using the Steam64ID for the command or the correct username ( ID preffered because if there are multiple players with the same username it wont work )

And then the command should run like normally.
For example:
oxide.usergroup add 76561199003679693 vip

**Screenshots**
Dont really need to iguess.

**Platform**
Oxide

**Additional context**
.

**Comment by Tim-NL** [comment]
Hi,

When I open the manual payment page on a Rust store, then it will ask me for the Steam64 ID. And fetching the UUID only happens on Minecraft stores, not on Rust ones. 

Are you sure that you have a Rust store? You can check that by going to the stores section on the right top.

-Tim

**Comment by EffeDion** [comment]
Yep i am 100% sure its a RUST store.


It looks like this but its asking me for steamid64 aswell which i enter but
i need to enter Ingame Name aswell with the manual payment. And its getting
my UUID from minecraft from my IngameName and its skipping the SteamID64
Maxudus Rust Owner Gold

Op wo 18 nov. 2020 om 13:21 schreef Tim Kwakman <notifications@github.com>:

**Comment by EffeDion** [comment]
[image: image.png]


Here its asking for Ingame Name on the top and in the command it looks like
its grabbing the UUID from that username from Minecraft.

Op wo 18 nov. 2020 om 16:08 schreef EffeDion <blackdionblade@gmail.com>:

**Comment by Tim-NL** [comment]
Thanks!

The issue has been resolved.

-Tim
