### ISSUE TITLE
Sale not showing in the "Featured package" module

### ISSUE THREAD

**Issue by Zettovec** [CraftingStore/Suggestions#435]
**Is your feature request related to a problem? Please describe.**
Sort of... Sale of a package should be visible in the module.

**Describe the solution you'd like**
I would like to see the sale (eg. ~~9.99~~ 8.32 EUR) in the "Featured package" module on the right side of the site.

**Additional context**
This feature can be fantastic for featuring packages that are in the sale, because at the moment, you see just the normal price and the sale is visible only after you click.

**Comment by Tim-NL** [comment]
Hi,

Thank you for your, well bug/feature mix report!

The feature has implemented, it will now show the old price, and the new sales price.

-Tim
