### ISSUE TITLE
GIFT-CARD page need Buyer, Date and Link to invoice(transaction) listed.

### ISSUE THREAD

**Issue by 2ic** [CraftingStore/Suggestions#437]
**Is your feature request related to a problem? Please describe.**
When you have 50+ Gift-cards issued it's almost impossible to manage it or find which is related to whom and when it was purchased.

**Describe the solution you'd like**
Would be nice to have a buyer and a link to the transaction (as a purchase date) at the GIFT-CARD page for each Gift-Card listed.

**Additional context**
![image](https://user-images.githubusercontent.com/74799262/99860111-0f640500-2b60-11eb-8225-efe71f6031b5.png)
*sample gift-card code..

**Comment by Tim-NL** [comment]
Hi,

Thanks for the suggestion.

It is now possible to see the linked payment, if the card has one.

-Tim
