### ISSUE TITLE
Do not explode all categories when REMOVE or DUPLICATE a package

### ISSUE THREAD

**Issue by 2ic** [CraftingStore/Suggestions#439]
**Is your feature request related to a problem? Please describe.**
Its so frustrating when I duplicate or remote a package WHOLE packages list explodes.. 
I just wanted to work in one single category.. when you expect to have hundreds of packages this is a pain!

**Describe the solution you'd like**
Do not explode all categories. Keep them {ARROW DOWN} closed. Keep {ARROW UP} open only category I REMOVE or DUPLICATE package in.

**Additional context**
EDIT package and going back to previous page doesn't explode all categories and keep the working category open.. dunno if this helps. UPDATE PACKAGE explodes all categories again.

**Comment by Tim-NL** [comment]
Hi,

I'm not sure what you are referring too exactly here, would you be able to clarify this with some screenshots? Thanks!

-Tim

**Comment by Tim-NL** [comment]
Hi,

Thanks for the suggestion!

The packages page will not persist its up or down state.

-Tim

**Comment by 2ic** [comment]
you're awesome
