### ISSUE TITLE
HTML Code in text box modules.

### ISSUE THREAD

**Issue by BenProPlayz** [CraftingStore/Suggestions#44]
Hello,

As stated in the subject my request is to allow HTML code in text box modules. This will allow users to put images, widgets, linkbacks, sponsors, discord, or anything else they would like in their shop. I am sure many people would really appreciate this feature. Thank you for taking my request into consideration.

Best Regards,

BenProPlayz

**Comment by Tim-NL** [comment]
Hello,

You can now use HTML in the box, it's limited to basic HTML like <b>, you won't be able to do change the CSS though this. You need custom templates for that. 

-Tim
