### ISSUE TITLE
Missing an "e" in "Chang your in-game name"

### ISSUE THREAD

**Issue by 2ic** [CraftingStore/Suggestions#440]
**Describe the bug**
missing an "e" in 

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/74799262/99865249-78ef0e00-2b76-11eb-8f7b-65ae7ce222bd.png)
![image](https://user-images.githubusercontent.com/74799262/99865279-ae93f700-2b76-11eb-911b-5bae533f603b.png)

**Platform**
CraftingStore website default template

**Additional context**

**Comment by Tim-NL** [comment]
Hi,

Thanks for all suggestions/bugs you've reported so far.

The typo has been resolved in the default language pack. You can also update the language texts to anything you like from [ Settings -> Language ].

-Tim
