### ISSUE TITLE
Edit Gift Card

### ISSUE THREAD

**Issue by LattyPvP** [CraftingStore/Suggestions#444]
**Is your feature request related to a problem? Please describe.**
Edit Gift Cards

**Describe the solution you'd like**
Make it so you can edit Gift Cards, so you all made it so you can duplicate them but another thing would be to edit them so you can like edit the price, etc..

**Additional context**
![image](https://user-images.githubusercontent.com/42073925/99884386-ed1fc500-2bfb-11eb-803b-68c0c6e1d912.png)

**Comment by 2ic** [comment]
+1 here on this. Issue with Gift-cards happen all the time. Being able to change balance on it would be great,

**Comment by Tim-NL** [comment]
Hi,

This is not something that we can allow, it is not allowed to modify gift-cards in most countries. Thus this is not something we'll allow.

-Tim

**Comment by LattyPvP** [comment]
So we aren't allowed to change the balance on like a duplicated Gift Card? Because like we can create a template gift card so like certain packages or whatever and we duplicate that then we can just change the price on it so we won't have to keep selecting the packages on the gift cards when making them.
