### ISSUE TITLE
A way to link {uuid} to a Gift-card no. So a player can keep same Gift-card code

### ISSUE THREAD

**Issue by 2ic** [CraftingStore/Suggestions#445]
**Is your feature request related to a problem? Please describe.**
A way to link {uuid} to a Gift-card no. So a player can keep same Gift-card code or multiple Gift-card codes.

**Describe the solution you'd like**
Upon login on website: instead of entering Gift-card code to validate balance: it shows right away what player has
![image](https://user-images.githubusercontent.com/74799262/99885849-d0888a80-2c05-11eb-836c-e0d5b148a01c.png)

I would personally prefer a Gift-card unique code so a player could refill it. Maybe entering his own Gift-card code on checkout for refill?

**Additional context**
It would add a more dynamic feel to the shop.

**Comment by Tim-NL** [comment]
Hi,

I think this would not be very secure, and anyone can just enter any user name they like. There is no real verification that we can use to validate someone's name without making the login process lots harder.

-Tim
