### ISSUE TITLE
add a little comment line to a manually created Gift-card

### ISSUE THREAD

**Issue by 2ic** [CraftingStore/Suggestions#447]
**Is your feature request related to a problem? Please describe.**
Manually created Gift-cards have no reference.
 
**Describe the solution you'd like**
add a little comment line to a manually created Gift-card.. just for follow ups.

**Additional context**
![image](https://user-images.githubusercontent.com/74799262/99892421-b325e180-2c42-11eb-9b92-a7f7ea6a2091.png)

**Comment by LattyPvP** [comment]
+1 This would be very helpful and make it easier to know who gift cards belong to when you have a lot of them.

**Comment by TheMonDon** [comment]
+1 thanks

**Comment by pustinek** [comment]
This would really be a welcoming feature to have +1

**Comment by Tim-NL** [comment]
Hello,

Thanks for the suggetsion!

This has been added to the creation process of gift cards.

-Tim
