### ISSUE TITLE
On package DUPLICATE : package icon is removed in -copy package

### ISSUE THREAD

**Issue by 2ic** [CraftingStore/Suggestions#448]
**Describe the bug**
On package DUPLICATE : package icon is removed in -copy package

**To Reproduce**
1. Go to 'webstore/packages'
2. Click on 'DUPLICATE'
3. Click on ''EDIT" on -copy package
4. See error : missing package icon

**Expected behavior**
package icon copied

**Screenshots**
![image](https://user-images.githubusercontent.com/74799262/99895267-c5f5e180-2c55-11eb-9743-23b15dfb983e.png)

**Platform**
CraftingStore website, default template; Rust plugin. 

**Additional context**

**Comment by Tim-NL** [comment]
Hello,

Thanks for the report, package icons will now get copied over correctly. They were not, because removing the original package would also remove the image. Now the images are separate from the packages, so it will only remove them when all packages that have them, no longer exist.

-Tim
