### ISSUE TITLE
Package icon should be shown centered

### ISSUE THREAD

**Issue by 2ic** [CraftingStore/Suggestions#449]
**Describe the bug**
Package icon not centered 

**To Reproduce**

**Expected behavior**
Package icon should be shown centered

**Screenshots**
![image](https://user-images.githubusercontent.com/74799262/99896011-a7461980-2c5a-11eb-9062-94721c4b9910.png)

**Platform**

**Additional context**

**Comment by Tim-NL** [comment]
Hi,

The image is indeed not centered, as most images that are uploaded are squares. 

If you do not want to use the default layout, you can use a custom template, or modify the behavior by creating a template based on the default one.

-Tim

**Comment by 2ic** [comment]
Do you mind telling me where I can "modify the behavior" ? Thanks in advance

**Comment by Tim-NL** [comment]
Sure, you can modify the HTML of the category.twig file. Some HTML/CSS skill is required for this.

**Comment by 2ic** [comment]
> Sure, you can modify the HTML of the category.twig file. Some HTML/CSS skill is required for this.

You don't say. I'll give it a try hoping I wont break something vital. Feels like heart transplant by a clueless highschooler (oh yeah I dissected a pig heart once). lmao

**Comment by 2ic** [comment]
Solution: 

<img class="img-responsive" src="{{ package.picture }}"><br/>

replace with:

<img class="img-responsive" style="display: block; margin-left: auto; margin-right: auto;" src="{{ package.picture }}"><br/>
