### ISSUE TITLE
Store Sales (possible ??) Bug and Feature Requests

### ISSUE THREAD

**Issue by Exophobias** [CraftingStore/Suggestions#45]
**Is your feature request related to a problem? Please describe.**
Yes, its related to your new update to Sales and Coupons

**Describe the solution you'd like**
The price of a package will be crossed out and beside it will be the new price after the sale AND there will be a read ribbon saying 'Sale' or '% Sale' or whatever in the top right/left a corner of each package if its individual package sales. If its a category sale then a message at the top of the category saying the sale. Something along those lines.

**Additional context**
The red ribbon like [this](http://prntscr.com/kltccr) (http://prntscr.com/kltccr)

**Comment by XpcAdam** [comment]
I think this is an okay idea but it isn't really something urgently needed! Also you could just put that ribbon in your images yourself with very little effort.

**Comment by Exophobias** [comment]
The sales thing is kind of more urgent because they don't know that the sale is on. Unless I say it is

**Comment by XpcAdam** [comment]
i guess but just make your own graphics and put it in the description of the category
