### ISSUE TITLE
Option to enable side modules with "Page" other than Homepage.

### ISSUE THREAD

**Issue by 2ic** [CraftingStore/Suggestions#450]
**Is your feature request related to a problem? Please describe.**
Right now when you open "Page" other than Homepage you don't have side modules visible anymore.

**Describe the solution you'd like**
Option to enable side modules with "Page" other than Homepage.

**Additional context**

**Comment by KristianP26** [comment]
You can do that by editing html code of your store.

**Comment by Tim-NL** [comment]
Hi,

@KristianP26 is correct, it is possible to do this by modifying the HTML.

-Tim
