### ISSUE TITLE
on package DUPLICATE or REMOVE. Keep me at the same window location.  

### ISSUE THREAD

**Issue by 2ic** [CraftingStore/Suggestions#451]
**Is your feature request related to a problem? Please describe.**
on package DUPLICATE or REMOVE, I get moved way UP at the beginning of Category; its a constant
scrolling down to get back to -copy package. 

**Describe the solution you'd like**
on package DUPLICATE or REMOVE. Keep me at the same window location.  

**Additional context**
it's hyper annoying when you have to create batches of items in a large category... DUPLICATE scroooooooool down DUPLICATE scroooooooool down DUPLICATE scroooooooool down DUPLICATE scroooooooool down

**Comment by Tim-NL** [comment]
Hi,

The behavior you are describing is correct, that is how the browser handles reloads. With the current set-up (of not using Javascript to load the page). There is no good way to resolve the issue.

I recommend you to use the collapse feature, to limit the packages/categories that you see.

-Tim
