### ISSUE TITLE
Make DUPLICATED package status Disabled from the start.

### ISSUE THREAD

**Issue by 2ic** [CraftingStore/Suggestions#452]
**Is your feature request related to a problem? Please describe.**
I was surprised to see that DUPLICATED package status was "Enabled" by default. It's a mess when you work
on multiple items at once because after DUPLICATE you have to EDIT and UPDATE those one by one just to :
![image](https://user-images.githubusercontent.com/74799262/99910132-60880c00-2cba-11eb-9165-d85a560045ff.png)

**Describe the solution you'd like**
Make DUPLICATED package status Disabled from the start.

**Additional context**
How it should look like after DUPLICATE:
![image](https://user-images.githubusercontent.com/74799262/99910169-94fbc800-2cba-11eb-9591-106c0f8e7a2e.png)

**Comment by Tim-NL** [comment]
Hi,

It will take the status from the package that it is duplicating, changing this behavior would be strange, as it won't be a copy then.

-Tim

**Comment by 2ic** [comment]
that's a bummer.. you know you're already adding - copy so technically speaking it's not a copy...
Trying really hard here lol
