### ISSUE TITLE
a way to DUPLICATE multiple packages at once and/or whole Category with Packages

### ISSUE THREAD

**Issue by 2ic** [CraftingStore/Suggestions#453]
**Is your feature request related to a problem? Please describe.**
can't DUPLICATE multiple packages at once and/or whole Category.

**Describe the solution you'd like**
a way to DUPLICATE multiple packages at once and/or whole Category with Packages

**Additional context**
**extremely** useful for multiple servers and editing process overall

**Comment by 2ic** [comment]
I think it's already requested at #426

**Comment by Tim-NL** [comment]
Duplicate with #237 & #426

**Comment by 2ic** [comment]
1 sec to be precise! I'm that fast :) lol
