### ISSUE TITLE
Console delivery execution confirmation or at least date and time of delivery in Commands tab

### ISSUE THREAD

**Issue by 2ic** [CraftingStore/Suggestions#455]
**Is your feature request related to a problem? Please describe.**
Partial orders delivery. Items to be delivered in Queue for hours. I have no way knowing WHEN missing items were delivered.

**Describe the solution you'd like**
Console delivery execution confirmation or at least date and time of delivery in Commands tab

**Additional context**
something like this?
![image](https://user-images.githubusercontent.com/74799262/99991968-b4125c80-2d83-11eb-81ae-870e12364eda.png)

**Comment by Tim-NL** [comment]
Hi,

It will now show the updated at date, so you can see when the latest change happened, this might be; Processed, Processing again, or initial.

-Tim
