### ISSUE TITLE
Add to backet from packages page. No more "More info". Keep buyer on same page (category). No more scrolling back.

### ISSUE THREAD

**Issue by 2ic** [CraftingStore/Suggestions#457]
**Is your feature request related to a problem? Please describe.**
I asked my players for a feedback on server shop and biggest issue is the "add to cart" function is very tedious.
Right now when you want to add package(s) into cart: 
1. click on "More info"
2. click on "Buy now"
3. click on "add to backet" + it moves you into your backet page for some reason.
4. find your way back to same shop category page you just left... scrooool to where you left from...
5. rinse and repeat to add more packages... (try to do that for 10+ packages... ) 

**Describe the solution you'd like**
1. click on "add to backet"
2. scroll to next wanted package.. "add to backet"

**Additional context**
This is how it should look like; no more "More info".. if buyer want to have "More info" he clicks on package name or icon; or both.
No need to have BUY on "More info" popup page. Make it POP and close on a click elsewhere (or click on "Close" will do) 
(buyer stays on same place at the shop page <- very important)
![image](https://user-images.githubusercontent.com/74799262/100370824-e23aab00-2fd4-11eb-8dee-4c895cf921a4.png)

**Comment by Tim-NL** [comment]
Hi,

Thanks for the suggestion.

I believe that most of these are already possible, you can replace the "More info" button with a "buy now" button that will link them to the package page (this is required, for the username). 

We cannot remove all steps, because those are required for getting information. We are not planning tom implement such big change to our platform.

-Tim

**Comment by 2ic** [comment]
anything I can do to prevent Buyer to : "+ it moves you into your backet page for some reason"
this was the biggest annoyance I got as feedback.
