### ISSUE TITLE
Ability for players to choose what server they get there product on on checkout

### ISSUE THREAD

**Issue by jnx-02** [CraftingStore/Suggestions#458]
**Is your feature request related to a problem? Please describe.**
Owning a bungeecord server but when players buy a crate for example it will give it to them on all servers, I want to make it so players can choose which server to get there crates on.

**Describe the solution you'd like**
Ability for players to choose what server they get there product on on checkout

**Additional context**

**Comment by 2ic** [comment]
I found a way around that by setting different packages for specific servers. You have an option on package creation to specify what server it goes to. Still +1 from me on your request; it's good to have options..

**Comment by Tim-NL** [comment]
Hi,

Thanks for the suggestion!

We implemented support for this a few days ago. It is now possible to let the user select on what server they want to run the commands. They can select it on a package by package basis. You can configure it at the "advanced" tab.

-Tim
