### ISSUE TITLE
Store Name in Notification Mail

### ISSUE THREAD

**Issue by EffeDion** [CraftingStore/Suggestions#463]
**Is your feature request related to a problem? Please describe.**
Yes/No Its not really a problem but it would be a pretty helpfull feature

**Describe the solution you'd like**
The store name added in the notification mail. At the moment its hard to see from which store the mails are coming if you have 2+ stores.

**Additional context**

**Comment by Tim-NL** [comment]
Hi,

Thank you for your feature request!

The store name has been added to the mail, it will be live in about 15 minutes.

-Tim
