### ISSUE TITLE
New Commands

### ISSUE THREAD

**Issue by elkoyofficial** [CraftingStore/Suggestions#464]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I have to check donations of certain players. It would be amazing to type a command in-game and it would list everything they have purchased in chat. 
It would also be great if we could have like a top 10 donators with the amounts they've donated.

**Describe the solution you'd like**
/craftingstoretop to view the top 10 donators and /craftingstore checkdonations <player> to see how much an individual has donated and what that player has purchased.

**Additional context**

**Comment by Tim-NL** [comment]
Hi,

Top donators;
You can use PlaceholderAPI - https://www.spigotmc.org/resources/placeholderapi.6245/
```
%craftingstore_donator% -> 5 recent donators (MinecraftName: Amount spent this month)
%craftingstore_donator_1% -> Top donator (MinecraftName: Amount spent this month)
%craftingstore_donator_2% -> Second top donator (MinecraftName: Amount spent this month)
%craftingstore_donator_3% -> Two after top donator (MinecraftName: Amount spent this month)
%craftingstore_donator_4% -> Three after top donator (MinecraftName: Amount spent this month)
%craftingstore_donator_5% -> Four after top donator (MinecraftName: Amount spent this month)
```

As for the list of things a player bought; 
This is not possible to get, as it would be too heavy to store this for every user on your server. 

If the player wants to see all their payments, they can do so from the CraftingStore dashboard.

-Tim
