### ISSUE TITLE
Gift cards enabled only for specific packages/ categories

### ISSUE THREAD

**Issue by Sv3tr1k** [CraftingStore/Suggestions#466]
**Is your feature request related to a problem? Please describe.**
It is not a problem but a gift cards enabled only for specific categories/ packages would be highly appreciated
**Describe the solution you'd like**
Add gift cards that will be only available for specific packages/ categories
**Additional context**

**Comment by Sv3tr1k** [comment]
EDIT: I meant those gift cards that are automatically generated after purchasing package

**Comment by 2ic** [comment]
> 
> 
> EDIT: I meant those gift cards that are automatically generated after purchasing package

#446 I think it's the same request as mine... still waiting on it.

**Comment by Tim-NL** [comment]
Hello,

It is indeed, I'll close this one. 

P.S. this is a suggestions board, we implement new suggestions when we think they are of value to our platform. So it is correct that you are "still waiting". Because adding something here is not a guarantee that it will get added, because it is a feature request. Sometimes it can take months before we implement or reject a feature. You can read more about this in the readme.

-Tim

**Comment by 2ic** [comment]
> 
> 
> Hello,
> 
> It is indeed, I'll close this one.
> 
> P.S. this is a suggestions board, we implement new suggestions when we think they are of value to our platform. So it is correct that you are "still waiting". Because adding something here is not a guarantee that it will get added, because it is a feature request. Sometimes it can take months before we implement or reject a feature. You can read more about this in the readme.
> 
> -Tim

Hi Tim, I don't think this is a new feature per-Se; we have all those options already available on manual "gift-card creation"; this option is just missing out of "package gift-card creation". It would add more depth to packages creation.

**Comment by Tim-NL** [comment]
It is a new feature, as it does not exist now. We did not add this option in here on purpose, it is not an error or something that was forgotten.

**Comment by 2ic** [comment]
ok. I figured it was a forgotten thing, thanks
