### ISSUE TITLE
Payment methods

### ISSUE THREAD

**Issue by AyzrixYTB** [CraftingStore/Suggestions#467]
Hello, I have a problem with the means of payment. The sites through which we can go do not answer anything ... I therefore suggest adding the paysafecard API, and the Paypal Visa API to pay by credit card without having a paypal account.

**Comment by Tim-NL** [comment]
Hi,

Paysafecard: You can use Mollie for this, we use them for our Paysafe payments as well.
Credit card: You can use Stripe for credit card payments.

P.S. Please use the format for the type that you are using in the next suggestion you add.

-Tim
