### ISSUE TITLE
Purchase order email confirmation must be complete. Not cut-off.

### ISSUE THREAD

**Issue by 2ic** [CraftingStore/Suggestions#468]
**Is your feature request related to a problem? Please describe.**
players receive mail order confirmation for their order with list of packages cut-off and not well presented
![image](https://user-images.githubusercontent.com/74799262/101371017-45033080-3878-11eb-92be-8f89e6cc8bde.png)
more often than not players don't remember if they purchased something or not and cut-off email confirmation
fall short in-here because they then contact admin with: "can you tell me if I purchased this and this and this..."

**Describe the solution you'd like**
mail order confirmation **must** **contain all relevant order confirmation**: including all packages purchassed
in a clear format. Price paid per package would be great too; some package can go on sale and have price changed.
It's always easier to manage when purchaser can confirm by himself what. when, how much spent... etc.. by himself.

**Additional context**
![image](https://user-images.githubusercontent.com/74799262/101372043-74ff0380-3879-11eb-8c0a-3b9f7d627a2c.png)

**Comment by Tim-NL** [comment]
Hi,

Thanks for the report.

The issue has been resolved, the reason for it being cut off, was related to the database not expecting names of this size, most of the times, users just buy some packages. Not so many that it would be more than 255 characters. We changed the way they are stored.

-Tim
