### ISSUE TITLE
Need data on to expire commands in queue and processed through Payments/commands..

### ISSUE THREAD

**Issue by 2ic** [CraftingStore/Suggestions#469]
**Is your feature request related to a problem? Please describe.**
I have no way to know if expire commands (package. advanced: expire after X min/h/days...) are processed.

**Describe the solution you'd like**
Show not only processed commands but also to expire commands with related date and time.
Ability to cancel some Pending commands would be great to have too,

**Additional context**
![image](https://user-images.githubusercontent.com/74799262/101375073-f906ba80-387c-11eb-93dc-2b5835c2b1e5.png)

**Comment by Tim-NL** [comment]
Hi,

We do not have this data, it will become available when the commands are queued. So we cannot show this.

-Tim

**Comment by 2ic** [comment]
I think I didn't make myself clear: you do have this data because your server sends on-expire commands.
![image](https://user-images.githubusercontent.com/74799262/101376073-2142e900-387e-11eb-8f6f-a666960a0605.png)

**Comment by Tim-NL** [comment]
You did make yourself clear, but we do not have this data available. It will become available when the command gets queued, as I replied above. 

-Tim

**Comment by 2ic** [comment]
" It will become available when the command gets queued,"

queued or processed?

if its queued: is it possible to see those to be processed commands in-time?
if it's only available when processed: will it appear on original payment #confirmation ?

**Comment by Tim-NL** [comment]
It will become available when the command gets queued. But that does not make much difference, because the command is processed within a few minutes.

Both will appear on the commands list.

-Tim

**Comment by 2ic** [comment]
thanks Tim. cheers

**Comment by 2ic** [comment]
#470 

> 
> 
> It will become available when the command gets queued. But that does not make much difference, because the command is processed within a few minutes.
> 
> Both will appear on the commands list.
> 
> -Tim

#470
