### ISSUE TITLE
Payments/Manage/View/Commands doesn't show all processed commands.

### ISSUE THREAD

**Issue by 2ic** [CraftingStore/Suggestions#470]
**Describe the bug**
Payments/Manage/View/Commands doesn't show all processed commands.

**To Reproduce**
1. Create a package with expire after XX minutes
2. Buy package and wait for expire command to process
3. go to Payments/Manage/View/Commands
4. Only initial command will show

**Expected behavior**
Initial and on expire commands to be shown.
Ideally to show: on expire commands in QUEUE (to be processed) with an option to cancel those (if needed) and changed to
"Processed" when done so.

**Screenshots**
package expire after 10mins and initial/expire commands:
![image](https://user-images.githubusercontent.com/74799262/101793260-9824ef80-3ad3-11eb-858b-def2bd73234b.png)
![image](https://user-images.githubusercontent.com/74799262/101792886-382e4900-3ad3-11eb-832b-bd3fc99820e8.png)

console commands process:
(10:01:00) | [CraftingStore] Executing Command: pm XXXXXXXXXXXXXXXXXXXXXXX Initial command process
(10:01:00) | PM to 2IC: Initial command process
(10:13:00) | PM to 2IC: expiry command process
(10:13:00) | [PrivateMessages] [PM]Server Console->2IC:expiry command process

in-game commands process:
![image](https://user-images.githubusercontent.com/74799262/101793435-cb677e80-3ad3-11eb-89dd-f3d8902346dc.png)

Payments/Manage/View/Commands:
![image](https://user-images.githubusercontent.com/74799262/101793575-f3ef7880-3ad3-11eb-8a37-8ed8945e2929.png)

**Platform**
Rust platform with CraftingStore website with CraftStore OXIDE plugin. 

**Additional context**
This is major. At this moment (unless I'm mistaken plz correct me) I have noway to see "to be processed commands" anywhere. They are somewhere.. out there. But I got no control to Cancel, Re-send, get information When those should process (This one is very important), etc.. over those whatsoever.

**Comment by Tim-NL** [comment]
Hi,

Thanks for the report! 

It will (from this point on) show all commands, every type is linked to the payment now. Including expiry commands.

-Tim
