### ISSUE TITLE
Add Serbian/Croatian/Bosnian/Montenegrin translation of CraftingStore's Terms

### ISSUE THREAD

**Issue by konfix** [CraftingStore/Suggestions#471]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'd like to contribute by adding Serbian/Croatian/Bosnian/Montenegrin* translation of CraftingStore's Terms confirmation. All those languages are very very similar (we can all understand each other). 

- Serbian language is officially written in both Latin & Cyrillic alphabets. Dialect of Serbian lang. is also spoken in Montenegro, but since 2007. less than 35% of people there speak their own version, called Montenegrin (it's just politics, Montenegrin isn't fully recognized as a language worldwide)

1. This would be Serbian translation:
"Slažem se sa Uslovima Korišćenja servisa CraftingStore, i dopuštam CraftingStore-u da obrađuje moje podatake na načine 
navedenim u njima, i potvrđujem da imam preko 18 godina, ili dozvolu roditelja/staratelja."
"Слажем се са Условима Коришћења сервиса CraftingStore, и допуштам CraftingStore-у да обрађује моје податке на начине наведним у њима, и потврђујем да имам преко 18 година, или дозволу родитеља/старатеља"

2. This would be Croatian translation:
"Slažem se sa Uvjetima Korištenja usluge CraftingStore, i dopuštam CraftingStore-u da obrađuje moje podatke na načine navedenim u njima, i potvrđujem da imam preko 18 godina, ili dozvolu roditelja/skrbnika."

3. This would be Bosnian translation:
"Slažem se sa Uslovima Upotrebe servisa CraftingStore i dopuštam CraftingStore-u da obrađuje moje podatke na načine navedenim u njima, i potvrđujem da imam više od 18 godina, ili dozvolu roditelja/staratelja."

- Adding those translations will help the community a lot, because some people from ex Yugoslavia don't understand English very well.

**Additional context**
//

**Comment by Tim-NL** [comment]
Hi,

Thanks for your suggestion!

We've added them to the site, you can now select these at the language configurator.

-Tim
