### ISSUE TITLE
Add more variables with steam id formats

### ISSUE THREAD

**Issue by KristianP26** [CraftingStore/Suggestions#473]
Hello,
It will be good if you add variables with different formats of steamid.
I need variable what will return me this format of steamid:  STEAM_1:0:79989426

There are functions what will transform steamid from one type to another one.

`function toCommunityID($id) {
        if (preg_match('/^STEAM_/', $id)) {
            $parts = explode(':', $id);
            return bcadd(bcadd(bcmul($parts[2], '2'), '76561197960265728'), $parts[1]);
        } elseif (is_numeric($id) && strlen($id) < 16) {
            return bcadd($id, '76561197960265728');
        } else {
            return $id; // 76561198120244580
        }
    };
    function toSteamID($id) {
        if (is_numeric($id) && strlen($id) >= 16) {
            $z = bcdiv(bcsub($id, '76561197960265728'), '2');
        } elseif (is_numeric($id)) {
            $z = bcdiv($id, '2'); // Actually new User ID format
        } else {
            return $id; // We have no idea what this is, so just return it.
        }
        $y = bcmod($id, '2');
        return 'STEAM_1:' . $y . ':' . floor($z); // STEAM_1:0:79989426
    };

    function toSteamID_NULL($id) {
        if (is_numeric($id) && strlen($id) >= 16) {
            $z = bcdiv(bcsub($id, '76561197960265728'), '2');
        } elseif (is_numeric($id)) {
            $z = bcdiv($id, '2'); // Actually new User ID format
        } else {
            return $id; // We have no idea what this is, so just return it.
        }
        $y = bcmod($id, '2');
        return 'STEAM_0:' . $y . ':' . floor($z); // STEAM_0:0:79989426
    };

    function toUserID($id) {
        if (preg_match('/^STEAM_/', $id)) {
            $split = explode(':', $id);
            return $split[2] * 2 + $split[1];
        } elseif (preg_match('/^765/', $id) && strlen($id) > 15) {
            return bcsub($id, '76561197960265728');
        } else {
            return $id; // [U:1:159978852]
        }
    };

    function toSteamID_NO_STEAM($id) {
        if (is_numeric($id) && strlen($id) >= 16) {
            $z = bcdiv(bcsub($id, '76561197960265728'), '2');
        } elseif (is_numeric($id)) {
            $z = bcdiv($id, '2'); // Actually new User ID format
        } else {
            return $id; // We have no idea what this is, so just return it.
        }
        $y = bcmod($id, '2');
        return '' . $y . ':' . floor($z); // 0:79989426
    };`

**Comment by Tim-NL** [comment]
Hi,

Thanks for your suggestion. 

You can now use the placeholder: {steam_id}
This will be the normal ID.

-Tim
