### ISSUE TITLE
Minecraft account name ban

### ISSUE THREAD

**Issue by SkyProX** [CraftingStore/Suggestions#474]
I have a problem that if I ban a username from the store page I get this text "We would not create a shopping basket for you, please try again later. If this issue persists, contact CraftingStore.net" although I should receive an text about the "That user has been banned from this store page." (If I have typos, then I apologize)

**Comment by Tim-NL** [comment]
Hi,

Thanks! We are now showing the correct error message when errors get back from our dashboard, like the ban message.

-Tim
