### ISSUE TITLE
Web Hooks Extension

### ISSUE THREAD

**Issue by KristianP26** [CraftingStore/Suggestions#476]
**Is your feature request related to a problem? Please describe.**
Not a problem, but it will make better use of third parties

**Describe the solution you'd like**
Adding more webhooks variables

TransactionID
External Transaction ID (if there is difference between TransactionID)
Steam Username

**Comment by Tim-NL** [comment]
Hi,

Thanks for your suggestion.

We've added the following;
- transactionId: This is our transaction ID, you'll also see this one on our dashboard.
- externalTransactionId: This is the transaction ID from the payment provider (if they have it). For example, for PayPal this is their transaction ID.
- username: The same thing as mc_name, but it has a better name. The steam name will be in both of these. The steamid64 is in the uuid field.

-Tim
