### ISSUE TITLE
Latin America Stores, gateways, defeating tebex

### ISSUE THREAD

**Issue by dabou0** [CraftingStore/Suggestions#478]
**Is your feature request related to a problem? Please describe.**
We would like to ask you guys to add MercadoPago and Pagseguro gateways, they are very famous in latin america and since you guys offer way cheaper plans with more advantages than tebex, is going to be very famous, since latin america countries are third world countries tebex is very expensive, tebex won't add this gateways (they have only pagseguro), that's your advantage, having what they don't (price and gateways), you could easily beat tebex on latin america, add mercadopago firstly to assure you have what they don't and then pagseguro.

My discord is SuperRats#9764

**Comment by Tim-NL** [comment]
Duplicate with #381 - Please watch that issue for updates.

-Tim
