### ISSUE TITLE
Proper Variables like enjin and tebex offer

### ISSUE THREAD

**Issue by thewickening** [CraftingStore/Suggestions#479]
**Is your feature request related to a problem? Please describe.**
I cannot have proper store automation with variables. For example create a pokemon, when they add to cart, it can ask yes which would increase the cost by x amount, or no and it will do nothing.

**Describe the solution you'd like**
For example create a pokemon, when they add to cart, it can ask yes which would increase the cost by x amount, or no and it will do nothing.

**Additional context**
Here is a screenshot of how it works in other places.
https://gyazo.com/c112f062311e982b52c9ba6fadab73f4

Then the command it would execute under the package is this, ({legend} {shiny} {level} {nature} {gender} {size} {ball} are all variables.)
pokegive {username} {legend} {shiny} {level} {nature} {gender} {size} {ball}

**Comment by Tim-NL** [comment]
Hi,

Better late than never.

We implemented updates for the variables system. It now supports this "dropdown" mode, as well as some other methods.

Required changes to template (when not using the default):
https://github.com/CraftingStore/Templates/commit/969a41713137e941d8ba2aba8bab3ae5630e7b52

-Tim
