### ISSUE TITLE
Can't see multiple pages when using "look up"

### ISSUE THREAD

**Issue by ElytraPvP** [CraftingStore/Suggestions#480]
Heya i'm trying to see who has used a specific coupon so i can add up money made from it but if i click on "lookup" and insert the name of the coupon it gives me this 
![image](https://user-images.githubusercontent.com/53577866/103235955-4a194400-493b-11eb-83be-bf2d1f0461ae.png)
There is no page option at the bottom so i can't see all of them

**Comment by Tim-NL** [comment]
Hi,

Thanks for your suggestion (or bug report, not sure exactly). 

It will now show pagination for none-item specific packages (like coupons).

-Tim
