### ISSUE TITLE
Higher package description limit

### ISSUE THREAD

**Issue by bobhenl** [CraftingStore/Suggestions#481]
**Is your feature request related to a problem? Please describe.**
Hi, I wanna suggest more characters in package description text box. I've already reached limit probably, cause when I add there few more characters, then I can't add more and I can't even copy it (it's empty when I copy it). 

The problem is, that I need to add there more text (features and new things to my biggest rank), but I can't...

**Describe the solution you'd like**
More allowed characters count in package description.

**Additional context**
Add here to description of package more characters please
![image](https://user-images.githubusercontent.com/18662086/103420865-bb563280-4b99-11eb-8761-ef28c4bb2ebd.png)

My actual words count
![image](https://user-images.githubusercontent.com/18662086/103420985-50f1c200-4b9a-11eb-9df7-2820edd2588d.png)

With html output:
![image](https://user-images.githubusercontent.com/18662086/103420953-27d13180-4b9a-11eb-9f7a-5ee4cefb0cd1.png)

https://pastebin.com/uK8gwEhA -> text, you can try add yourselves few more characters

Broken words count:
![image](https://user-images.githubusercontent.com/18662086/103420982-4afbe100-4b9a-11eb-93d5-8ab150d87f4f.png)

**Comment by Tim-NL** [comment]
Hi,

What character limit would be enough for your use-case?

-Tim

**Comment by bobhenl** [comment]
Hi, I'm not really sure, cause it's the highest rank and everything I add to lower rank is added to the highest too, so not sure, you may could increase about 1/4 more? So html maybe to 20k characters, but may normal characters to 12,5k for ex.

**Comment by Tim-NL** [comment]
Hi,

I've checked our end, and the description limit is set to 40k already.

Please make sure that you are looking at the correct value.

-Tim

**Comment by bobhenl** [comment]
Hi TIm could you please try it in your editor and add for ex. text here? https://pastebin.com/ass1HnEN It stops after few characters. It's package description
![image](https://user-images.githubusercontent.com/18662086/103493064-7cd9a580-4e2f-11eb-8f5e-ed638973fa12.png)
![image](https://user-images.githubusercontent.com/18662086/103493065-7e0ad280-4e2f-11eb-9134-3f0cd6b8d3f8.png)

**Comment by Tim-NL** [comment]
Hi,

Thanks! I was checking the backend, but there is also a limit built into the editor itself. It has been raised as well now. Please check in about 15 minutes if you can enter your content now.

-Tim

**Comment by bobhenl** [comment]
Yeah worked thanks
