### ISSUE TITLE
Custom/Ingame Currency

### ISSUE THREAD

**Issue by owlman5126** [CraftingStore/Suggestions#483]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like a hook with essentials or a database (database is preferred) that would give users credit based on what they have in MC

**Additional context**
would hook in through plugin and plugin would commutate to webstore.

**Comment by Tim-NL** [comment]
Hi,

CraftingStore is a donation platform, not an in-game shop. If you want an in-game shop, then you can use a menu plugin like DelexeMenu's, and set "click price" to the item. 

-Tim
