### ISSUE TITLE
MercadoPago Argentina

### ISSUE THREAD

**Issue by Asensito** [CraftingStore/Suggestions#484]
**Is your feature request related to a problem? Please describe.**

From Argentina you cannot use Paypal (due to a government restriction) and 90% of the population uses MercadoPago, that would attract all the owners of servers from this country to the platform.

**Describe the solution you'd like**
Implement this means of payment in order to use the service.

**Additional context**
I am willing to provide Mercadopago accounts enabled for testing and use my platform silver plan.

**Comment by Tim-NL** [comment]
Hi,

This feature request already exists here #381 - We might look into MercadoPago later. We spend days of work on implementing PagSeguro a few weeks ago, but we might also look into MercadoPago at a later stage. 

-Tim
