### ISSUE TITLE
Discord messages translation not working

### ISSUE THREAD

**Issue by dabou0** [CraftingStore/Suggestions#485]
**Describe the bug**
Discord messages translation not working, ive translated the whole store and its working fine, only the discord area is not working.

**To Reproduce**

**Expected behavior**
The discord messages to be translated

**Screenshots**
![image](https://user-images.githubusercontent.com/34607217/104606343-6bc63b00-565e-11eb-99d3-ee81248fefe4.png)
![image](https://user-images.githubusercontent.com/34607217/104606447-81d3fb80-565e-11eb-8893-4703a93cdf05.png)

**Platform**
CraftingStore website

**Additional context**
Im using the default template

**Comment by Tim-NL** [comment]
Hi,

Thanks! The translations have been fixed, it will work in about 10 minutes (the time it takes to deploy to our servers).

You'll need to re-enter them at the language section, about 4 of the items had this issue. Thanks for the report!

-Tim
