### ISSUE TITLE
Make it more clear that ticking "paypal" at checkout also supports credit/debit

### ISSUE THREAD

**Issue by KickSquareMC** [CraftingStore/Suggestions#490]
Lots of people try to buy something with credit/debit, but think only paypal is possible because there's only an option for "Paypal" (even though there is a big "pay with credit/debit" button once you click paypal)

Does that make sense?

**Comment by Tim-NL** [comment]
Hi,

You can rename the button to anything you like from [ Settings -> Language ]. You don't have to leave it at "PayPal". You can change it.

P.S. Read the readme file (https://github.com/CraftingStore/Suggestions). You are not using the template, our rule is that issues will be closed when you do not use it.

-Tim
