### ISSUE TITLE
Edit Duplicated Gift-Cards

### ISSUE THREAD

**Issue by LattyPvP** [CraftingStore/Suggestions#492]
**Is your feature request related to a problem? Please describe.**
Edit Duplicated Gift-Cards

**Describe the solution you'd like**
Allow us to edit duplicated gift-cards, because I can create a pre-made gift-card with the correct settings I would like on it but when I want to duplicate and changed the price I can't and have to redo the whole gift-card.

**Additional context**

**Comment by Tim-NL** [comment]
Hi,

In most countries, it is not allowed to modify gift-cards, thus we do not allow changing them. We are not planning on changing it for that reason, sorry.

-Tim

**Comment by LattyPvP** [comment]
But it is Minecraft? It would be nice to change the price of a gift card instead of having to remake all the settings
