### ISSUE TITLE
Add remove all feature in the Pending Payment

### ISSUE THREAD

**Issue by TGxSlayer** [CraftingStore/Suggestions#493]
It took plenty of time to remove those transactions because a lot of players keep spamming the purchase manually button a lot of times and I need to remove those transactions one by one.

**Comment by Tim-NL** [comment]
Hi,

Your feature request is not using the templates, as required by our rules; https://github.com/CraftingStore/Suggestions/blob/master/README.md

Please modify the issue, and notify us when it complies. 

-Tim
