### ISSUE TITLE
Reordering commands

### ISSUE THREAD

**Issue by Pokes303** [CraftingStore/Suggestions#497]
**Is your feature request related to a problem? Please describe.**
I have to change a lot of commands order in a package tab, but the only way it can be done is deleting every command until getting to the one I want and creating another time all the commands

**Describe the solution you'd like**
I would like to move commands order. For me, i think the best solution would be reordering commands like the youtube's playlist system (Where you can hold and drop with the mouse the video that you want in the right place), or two buttons, one to set it up and another to set it down.

**Additional context**
![imagen](https://user-images.githubusercontent.com/24766260/106042634-9ba12400-60dd-11eb-8df0-8b7df06c9c7a.png)
Maybe here, on the left corner

**Comment by Tim-NL** [comment]
Hi,

Thanks for the suggestion!

You can now re-order the commands. There is no obvious button to drag & drop, but you can drag them by holding them and placing them into the right position.

-Tim
