### ISSUE TITLE
[Feature Request] - Add a test server button when configuring the server.

### ISSUE THREAD

**Issue by level42ca** [CraftingStore/Suggestions#50]
It would be nice to have a test server button, where users could simply click a button on the admin portal, and it would broadcast a message or custom command in Minecraft chat.

**Comment by Tim-NL** [comment]
Hi, 

We added a "test" button at the index page located here: https://craftingstore.net/admin/servers
It will send the command "CraftingStore test received!" to your server. 

-Tim

**Comment by level42ca** [comment]
This works an absolute treat. Thank you!
