### ISSUE TITLE
SFTP support for templates

### ISSUE THREAD

**Issue by pustinek** [CraftingStore/Suggestions#503]
**Is your feature request related to a problem? Please describe.**
I always found it difficulty to create/maintain templates on Tebex and now on crafting store since the on site editor for CSS/HTML/Twig is not very useful when navigation + the lack of intellisense support. So I was always used VSCode to edit files locally and then copied everything to the browser editor.

**Describe the solution you'd like**
Just having a SFTP access to my templates and their files. This feature would enable theme developers to almost instantly sync files from local storage to the server (WinSCP). Giving the ability for developers to use all the features that a dedicated editor like VSCode provides.

**Comment by Tim-NL** [comment]
Hi,

Templates are not real files, they are values in a database. We do not have "webhosting packages" for every user. There is no SFTP server, or access possible in any way. 

So this is not something that we can support.

-Tim
