### ISSUE TITLE
Skrill implementation

### ISSUE THREAD

**Issue by Innesity** [CraftingStore/Suggestions#505]
**Is your feature request related to a problem? Please describe.**
No, this feature request is not related to a problem, but it's related to a miss feature.

**Describe the solution you'd like**
I'd like to be able to use Skrill as a payment gateway for our servers.

**Additional context**

**Comment by w41k3r26** [comment]
Please implement Skrill, really need it. Paypal is eating my head with the extreme exchange rates and charges.

**Comment by Tim-NL** [comment]
Hi,

We can currently not implement Skrill, check my comment in #298.

-Tim
