### ISSUE TITLE
{username} placeholder in Manual Payment Gateway

### ISSUE THREAD

**Issue by IrineuMC** [CraftingStore/Suggestions#506]
**Add a username placeholder on the Manual Payment Gateway**
Examples: {username} or {name} or similar
Objective: Inform the nick that the user has placed and/or forward the username to another page automatically

**Comment by Tim-NL** [comment]
Hi,

You can use these placeholders; https://help.craftingstore.net/books/general/page/what-placeholders-can-i-use 

P.S. You are not using the correct format. As per the rules in our readme (https://github.com/CraftingStore/Suggestions/blob/master/README.md) I've closed the issue.

-Tim

**Comment by IrineuMC** [comment]
No, no command placeholder, placeholder for Manual Payment Gateway

and sorry for not using the correct issue format

**Comment by Tim-NL** [comment]
Hi,

This is not possible to do, the payment system dealing with the manual payment is not aware of the username. So it cannot show it. The manual payment method is designed for things like manual bank transfers. Where you can enter your bank account & a reference to you can find it. It's not meant to show the username in those messages.

-Tim

**Comment by IrineuMC** [comment]
Oh ok, thanks!
