### ISSUE TITLE
Community goal command bug

### ISSUE THREAD

**Issue by Niko302** [CraftingStore/Suggestions#507]
**Describe the bug**
the commands in the community goal module.
It seems like it is encoding special characters after trying to update it.

**To Reproduce**
1. Go to 'communtiy goal'
2. Click on 'add command'
Create input the following command
https://pastebin.com/XFFzMs5z

**Expected behavior**
The input to stay the same.

**Screenshots**
The changed command after clicking update.
https://cdn.discordapp.com/attachments/422510039916609552/806595873290977310/cmds.PNG

**Platform**
CraftingStore website

**Comment by Tim-NL** [comment]
Hi,

The issue has been resolved, it was caused by a security measure. It only affected your view, the server would have executed the correct commands.

-Tim
