### ISSUE TITLE
Cumulative Categorys

### ISSUE THREAD

**Issue by j19mes** [CraftingStore/Suggestions#509]
**Is your feature request related to a problem? Please describe.**
When creating  a cumulative category it would be nice if you could make it calculate on the price it is currently instead of the price it was bought for so it is easier for server owners to create rankups for ranks for example.

**Describe the solution you'd like**
A option for cumulative category's to be based on current prices not price bought for.

**Additional context**
N.A

**Comment by Tim-NL** [comment]
Hi,

This is not something that we can support, the cumulative category feature is made to discount the amount that the user already paid. Discounting the amount its currently worth is another thing all together, that we're not looking into supporting. Sorry.

-Tim
