### ISSUE TITLE
Module: Show the most recently joined users

### ISSUE THREAD

**Issue by AndreMorise** [CraftingStore/Suggestions#510]
**Is your feature request related to a problem? Please describe.**
Right now, you're able to list recent donations. It would be beneficial to also have another module for listing the users that most recently joined the server itself.

**Describe the solution you'd like**
The new module to "Show the most recently joined users' could have forced limitations, such as only checking the server for this information every 5 minutes (shorter or longer). There could be a limit in place for how many users can be displayed in this list, either hard-coded or changeable via the module settings.
- Optional: Link that directs to the user on MCUUID or an equivalent platform (or allows you to copy this information). 
- Optional: Display the donation tier / rank of the user (if applicable)
- Optional: There could also be an admin panel integration for this, which allows you to do more things with the context surrounding each user

**Additional context**

![image](https://user-images.githubusercontent.com/22132985/107154185-92b31c80-693f-11eb-92cf-eb9c003e2c05.png)

**Comment by Tim-NL** [comment]
Hi,

CraftingStore is a donation platform, we do not keep track of players that join a specific server, I'm sure that there are other systems that can monitor players. But we only process donations.

We do not have this data, and there is no reason for us to have that data, we don't need it to process payments for a specific server. So this is out-of-scope for CraftingStore.

Thanks for taking the time to write your suggestion tho!

-Tim
