### ISSUE TITLE
Expansion on module creation

### ISSUE THREAD

**Issue by RyderBelserion** [CraftingStore/Suggestions#511]
**Is your feature request related to a problem? Please describe.**
It's not related to a problem.

**Describe the solution you'd like**
Instead of piling the modules on one side of the page which scrolling gets tedious, Have an option on module creation to choose which side of the page it will go on i.e right or left.

**Additional context**

**Comment by Tim-NL** [comment]
Hi,

You can move modules where you like on our Silver plan. Our template editor allows you to modify the HTML & CSS, so you have full control over where items are located, you can even write logic (using the Twig template engine).

-Tim
