### ISSUE TITLE
Multiple Currencies and User Control

### ISSUE THREAD

**Issue by w41k3r26** [CraftingStore/Suggestions#512]
1. It is quite annoying when players are in different nations and it's difficult for them to make a conversion from google or so. 
2. Sometimes I need to make changes or fix ranks/subscriptions to users and there since there is no user database or account login I cant really change any packages or make changes without triggering the global announcement.
 
Solution: Provide different currency options for each user, and if necessary can also have per user account which can cache the currency type and more control over users packages.

Addition reference can be taken from WHMCS control panel or namelessmc which allows users to create an account and then manage it.

**Comment by Tim-NL** [comment]
Hi,

This suggestion has come up some times, but we are not planning on supporting it. We do currently not want to track exchange rates between currencies, and possibility sell something for more/less depending on what happens with specific currencies. Its up to the payment providers like PayPal to take care of that.

So this is not something that we want to support at this point in time.

-Tim
