### ISSUE TITLE
Condition to execute global command

### ISSUE THREAD

**Issue by pustinek** [CraftingStore/Suggestions#517]
**Is your feature request related to a problem? Please describe.**
Global command are currently always ran when the package is purchased with no options to format them for different categories. 
For instance, I have a category of ranks when purchased would send a differently formatted global command (alert) than other category packages.

**Describe the solution you'd like**
A simple input condition that would be checked before the command gets executed. It could either be JavaScript format or Regex. 
![regex_support](https://user-images.githubusercontent.com/21089157/107849430-6b56c680-6dfb-11eb-99d4-68b898e5d483.PNG)

![image](https://user-images.githubusercontent.com/21089157/107849379-2a5eb200-6dfb-11eb-86eb-7a710582fe40.png)

**Additional context**
I think an implementation where the user is able to manually write up the condition is the way to go, since it's way more flexible than just dropdown selection for category/server/etc...

**Comment by Tim-NL** [comment]
Hi,

You can do this from the packages themselves, you can select exactly on what server, what command should run, per package.

The global commands, as the name implies, are global commands that will run globally. It is limited by design. If you need to run specific commands, then you can add them to your packages directly. Global commands should not be used for that.

-Tim

**Comment by pustinek** [comment]
I understand that you guys are trying to keep it simple.

But I still think it's too limited. Because for instance I have a global command that is executed to alert players that a package was bought, but I have a singe package where I wish for the message to be different. 
With the current implementation I will have to notify users with two alert messages and if that is done multiple times a day, users will probably start asking why the spam messages.
And dropping the Global Command feature for these things would be too time-consuming if we decide to change a single part of the message.

It's a feature that could easily be opt-out by default and not used if not required by users. But just having the option would make a massive difference for edge cases like this.
I might be alone in requesting a feature like this, so I understand the decision for denying it, but I find it really frustrating when features like these are missing.

Thank you,
Pustinek

**Comment by Tim-NL** [comment]
Hi,

Global commands are just that, global commands. They are meant to be global commands that run globally. It would be confusing if you can do the same thing at two locations. There is no need for it. 

You can do what you want already, but you'll have to do it on the package level, so you are not missing a feature here. 

-Tim

**Comment by pustinek** [comment]
I can't seem to find the option to opt a package out from the global-command feature, if that is what you meant ?

**Comment by Tim-NL** [comment]
Hi,

You can create specific commands per package, if you do not want a global command, then you can add the alert to your packages. You can modify it for every package that you have. The global commands feature is only for commands that you want to run everywhere. If you want commands to run for specific packages, or not being the same, then you'll have to configure them at the package level.

-Tim

**Comment by pustinek** [comment]
Understand that, that's why I find it very limiting, cuz I can't cover edge cases like this, but have to either remove my global commands feature and move the alert message to all my packages or live with having two alert messages sent with some packages (one via global command and the other via package command).

I'll just go with two messages system for one of the package just to make it easier to maintain in the long run.
Thanks for the fast replies 💯
