### ISSUE TITLE
Global commands to run once per cart and not per package in cart

### ISSUE THREAD

**Issue by Maxitotito** [CraftingStore/Suggestions#518]
**Is your feature request related to a problem? Please describe.**
The 'global commands' runs as many times as packages are in the cart of the buyers

**Describe the solution you'd like**
Make the 'global commands' run once for every cart bought

**Additional context**
What is happening now: buyer buys 2 packages in one cart, one of bucket of water and one of dirt, global commands saying thanks runs twice
What I would like to happen: buyer buys 2 packages in one cart, one of bucket of water and one of dirt, global commands saying thanks runs once

**Comment by Tim-NL** [comment]
Hi,

You're correct, after looking into this, I also think that this is not the correct behavior. This has been corrected, it will now run once per basket.

Thanks for your report!

-Tim
