### ISSUE TITLE
Feature request for expire packages

### ISSUE THREAD

**Issue by Sikatsu** [CraftingStore/Suggestions#519]
**Is your feature request related to a problem? Please describe.**
On my webstore I sell Patreon in packages of 30, 90 and 180 days. Most of the players prefer this above an actual subscription.
When for example they wanna buy more days while their current one still lasts, it will remove their patreon on the expire date of the first payment they did.

**Describe the solution you'd like**
It would be nice if players for example buy 30 days, and they wanna buy another 30, 90 or 180 days, it will stop the expire command from running from their previous package.

It could be another setting to the category section:
![image](https://user-images.githubusercontent.com/5664135/107952796-83b11780-6f9a-11eb-9c98-c17074a87027.png)
''Should expire commands be stopped/renewed if another package from this category is bought?''

If it's unclear on what I mean, please let me know. Open for other solutions too.

**Comment by pustinek** [comment]
Hey,
They way I implemented this was using the LuckPerms permission plugin on my server. When the player purchases his rank I just give them the permission temporarily for the time they purchased with the `accumulate` feature that LuckPerms offers.

**Command example:**
`lp user {player} permission settemp group.vip+ true 30d accumulate`

**Comment by Tim-NL** [comment]
Hi,
Thanks for the report/suggestion!

We made a change to the default behavior of how it handles these, but it is not fully what you need.

When someone buys the same item now, it will renew the original one (or the last one that is still active) - So it won't run the expiry commands. But this won't work for packages spread over a category. It will only work if you renew the same package before it expires.

I suggest you use the method @pustinek provided if you want to have this over multiple packages in the same category. That is a little too specific for us to implement as a general feature.

-Tim
