### ISSUE TITLE
sub category

### ISSUE THREAD

**Issue by jjj700** [CraftingStore/Suggestions#52]
**Describe the bug**
if you disable a sub category it still shows up in the drop down menu

**To Reproduce**
if you disable a sub category it still shows up in the drop down menu

**Expected behavior**
people see things they shouldnt

**Screenshots**
not needed
**Platform**
web

**Additional context**
N/A

**Comment by Tim-NL** [comment]
Hello,

This issue has been fixed.

-Tim
