### ISSUE TITLE
Tips for Minecraft Bedrock servers

### ISSUE THREAD

**Issue by EvilDevil1175** [CraftingStore/Suggestions#521]
A suggestion would be to put a plugin for those of us who use the Minecraft Bedrock platform and that when a player bought something the commands are executed when the player is online 1 week ago I put That the commands are given when the player is online and when a player made the purchase automatically the commands were given I would like the commands to be executed when the player is online

**Comment by Tim-NL** [comment]
Hi,

The suggestion does not follow our rules as described in the readme (https://github.com/CraftingStore/Suggestions/blob/master/README.md). So as described there, we'll close it.

-Tim
