### ISSUE TITLE
Flexible Currency

### ISSUE THREAD

**Issue by Gilthunderx** [CraftingStore/Suggestions#522]
Please add a feature that enables the buyer to choose its desired currency, this is very helpful when your server is catering players all around the globe.

This helps players that are willing to buy ranks to navigate and understand the server ranks pricing.

**Comment by Tim-NL** [comment]
Hi,

The suggestion does not follow our rules as described in the readme (https://github.com/CraftingStore/Suggestions/blob/master/README.md). So as described there, we'll close it.

-Tim
