### ISSUE TITLE
Package In-Game Name command Placeholders. Like {package_name} but including formatting

### ISSUE THREAD

**Issue by scerstt** [CraftingStore/Suggestions#524]
**Is your feature request related to a problem? Please describe.**
With the current {package_name} placeholder, it's an unformatted text output, so to effectively use this and acheive formatting, you have to manually enter the package name with formatting when broadcasting a message for example.

**Describe the solution you'd like**
I'm requesting a new placeholder to be made for commands, something like {package_name_ig} (Package name in-game) where it takes the formatting you've set in the, in-game section of a package.

**Additional context**
Simplify your users package creation

**Comment by Tim-NL** [comment]
Hi,

Thanks for your suggestion, you can now use the placeholder {ingame_package_name}. This will be either the in-game name field, and if that field is not set, it will be just the normal name.

-Tim
