### ISSUE TITLE
Add a Support Chat integration

### ISSUE THREAD

**Issue by IrineuMC** [CraftingStore/Suggestions#526]
**Is your feature request related to a problem? Please describe.**
There is no problem, but it would be nice to be able to resolve the buyer's doubts directly through the webstore

**Describe the solution you'd like**
Adds a integration of support chat

**Additional context**
Examples of support chats to integrate:
https://crisp.chat/
https://tidio.com/

**Comment by Tim-NL** [comment]
Hi,

With our silver plan, you can load in any javascript file you like. So you can also load any of those services. So this is already possible.

-Tim
