### ISSUE TITLE
Including usernames in custom payment method requests

### ISSUE THREAD

**Issue by Cyclize** [CraftingStore/Suggestions#528]
**Is your feature request related to a problem? Please describe.**
I'm using a custom payment gateway that stores customer names per transaction. I'd like to have CraftingStore include usernames/IGNs in the custom payment method request. I couldn't find a way to easily retrieve usernames/IGNs by their email.

**Describe the solution you'd like**
Add `username` to `user` in custom payment method requests.

**Additional context**
Have the request looking like the one below.
```
{
  "type": "PENDING", // Status enum: PAID, PENDING, CHARGE-BACK
  "transactionId": "DUMMY-DUMMY-DUMMY-DUMMY", // Transaction ID
  "currency": "USD", // Currency
  "user": {
    "identifier": "1234567", // Internal identifier (basket ID)
    "username": "Dummy", // Client username
    "email": "dummy@craftingstore.net" // Client email
  },
  "package": {
    "name": "Example package", // Combined package name
    "notes": null, // Optional notes, not used on CraftingStore currently
    "price": 900 // Money amount in cents
  },
  "webhook": {
    "failedUrl": "https://example.craftingstore.net/failed", // URL to redirect the user to on failure (payment cancel/error)
    "successUrl": "https://example.craftingstore.net/success" // URL to redirect the user to on success
  }
}
```

**Comment by Tim-NL** [comment]
Hi,

It is not possible for us to include the Minecraft name in this payload. This is generated by our payment system (not by CraftingStore).

The information provided here should only be used to redirect the user to the correct payment location, it should not show anything specific to the user, like their in-game name. It contains the information necessary for creating the payment. We'll take care of processing the commands after you confirm that the payment was completed.

-Tim
