### ISSUE TITLE
API Endpoint to Top-up a gift card

### ISSUE THREAD

**Issue by pustinek** [CraftingStore/Suggestions#529]
**Is your feature request related to a problem? Please describe.**
I own a Minecraft server where the plan is to reward players for voting/playing/referring through gift-cards on the store via API endpoints. Currently, the only possibility is to create new gift cards, but this gets can get messy with every time he hits a certain threshold I would have to create a new gift card for the user and this makes it hard for them to keep track of the balance and even removes the possibility to purchase anything more than their max-worth gift card (can't stack).

**Describe the solution you'd like**
A new PUT endpoint through API to top up the gift card would enable to make a clean solution where only one gift card per user is created for server related rewards.

`PUT https://api.craftingstore.net/v7/gift-cards/:id`

**Additional context**
I was looking at an issue that was raised by another  user (#444) where the gift card can't be edited, but I believe toping it up shouldn't cause the described issue, because it's only giving the player more balance and not taking it away, right ?
Tebex have this feature implement [here](https://docs.tebex.io/plugin/endpoints/gift-cards).

I hope this feature can get implemented, because I have a big project planned based on this feature and without it, I'm kinda screwed 

Thank you.

**Comment by Tim-NL** [comment]
Hi,

I agree, topping up gift-cards would not cause any issues. We've implemented the feature, can you can check the documentation here: https://docs.api.craftingstore.net/api/gift-cards - It will work the same as the Tebex link you provided.

Thanks for the suggestion and for taking the time to look through the other issues.

-Tim
