### ISSUE TITLE
Disabled categories showing up in nameless integration

### ISSUE THREAD

**Issue by Tatzoo** [CraftingStore/Suggestions#531]
**bug:**
Disabled categories still show up in Namelessmc Craftingstore module

**Screenshots**:

Craftingstore in website:
![firefox_inXcnGp5Mh](https://user-images.githubusercontent.com/78931787/110946708-81df3780-833f-11eb-8b4b-a5208bbf9279.png)

The disabled category that shouldn't show up in the picture above:
![firefox_Ugub4heVTR](https://user-images.githubusercontent.com/78931787/110946728-89064580-833f-11eb-8bac-3915cb17d949.png)

**Comment by Tim-NL** [comment]
Hi,

Thanks for your report!

This will resolve the issue: https://github.com/CraftingStore/NamelessMC-CraftingStore/releases/tag/1.5
If you re-save any of your categories and click "Sync" within the NamelessMC interface, you'll no longer see the disabled categories.

-Tim
