### ISSUE TITLE
Symbols Support for Minecraft Usernames in Manual Payment

### ISSUE THREAD

**Issue by arashi14** [CraftingStore/Suggestions#533]
**Is your feature request related to a problem? Please describe.**
Yes, Manual Payment doesn't let Minecraft Usernames to have symbols like "*".

**Describe the solution you'd like**
I suggest to add symbols support for Minecraft Usernames in Manual payment because some servers use Geyser as their plugin and Geyser players or what you call bedrock players have prefix like "*" symbol. I would love it if the manual payment let minecraft usernames have those symbols. Thank you!

**Additional context**
![image](https://user-images.githubusercontent.com/19740277/111305776-54bdbc80-8692-11eb-836c-bc36b339c80d.png)

**Comment by Romvnly-Gaming** [comment]
this!

**Comment by Sexy-Jura** [comment]
Yes this is needed

**Comment by Tim-NL** [comment]
Hi,

Thanks for the feedback/suggestion!

The manual payment option will now allow names that start with either a + or a *.

-Tim
