### ISSUE TITLE
Manual Payments

### ISSUE THREAD

**Issue by JayJ-Dev** [CraftingStore/Suggestions#536]
Ability to select more than one package in a manual payment.

Just say that someone, or multiple people had one a giveaway or something, or you need to give multiple packages away, it would jsut be easier to be able to select more than one package in the Manual Payment section.

**Comment by Tim-NL** [comment]
Hi,

Your issue does not follow our rules as specified in the readme - https://github.com/CraftingStore/Suggestions

Please make sure that you follow our rules.

-Tim

**Comment by JayJ-Dev** [comment]
^ it was in the right format, i just removed the prompt/question

**Comment by Tim-NL** [comment]
Could you please add it back, and let me know? After it is back to the correct format, I can re-open the issue.

**Comment by JayJ-Dev** [comment]
I opened a new issue about 5 min ago.
