### ISSUE TITLE
Manual Payments

### ISSUE THREAD

**Issue by JayJ-Dev** [CraftingStore/Suggestions#537]
**Is your feature request related to a problem? Please describe.**
Ability to select more than one package in a manual payment.

**Describe the solution you'd like**
Just say that someone, or multiple people had one a giveaway or something, or you need to give multiple packages away, it would just be easier to be able to select more than one package in the Manual Payment section.

**Additional context**
None

*my last request was int he right format, i jut removed the prompt/questions*

**Comment by Tim-NL** [comment]
Hi,

You are now able to select up to five (5) packages when creating manual payments. Thanks for the suggestion!

-Tim
