### ISSUE TITLE
Default product box size in webstore

### ISSUE THREAD

**Issue by wumptrax** [CraftingStore/Suggestions#539]
The product boxes have different sizes. Depending on the name and price (see image below)
- https://i.imgur.com/VvqZfKH.png

I would suggest that there is a fixed size for the boxes. Would look a lot cleaner.

Example:
```
col-md-4{
 min-height: 7em;
}

**Comment by Tim-NL** [comment]
Hi,

You can modify this on our Silver plan, we offer full control over the template. It is meant to change the height itself depending on the items in there. If you do not like the default behavior, then you can change it. 

-Tim
