### ISSUE TITLE
Coupon code API 

### ISSUE THREAD

**Issue by jumbo1907** [CraftingStore/Suggestions#54]
The only thing I really need is to create a coupon code with a web page endpoint.

Thanks

**Comment by Tim-NL** [comment]
The implementation of the API for coupon creation has been added. We are still working on API documentation, but for now:

https://api.craftingstore.net/v4/public/coupon/create

Auth: Beaner header, it expects a server token.
Method: POST

**Post data:**
couponName: Name of the coupon
couponType: 1 is amount, 2 is percentage
maxUses: Max times the coupon may be used, 0 for unlimited.
startTimestamp: Unix timestamp when the coupon must be available. 
endTimestamp: Unix timestamp when the coupon must be unavailable.

As said, the API documentation will become available later, but this should suffice. 

- Tim

**Comment by jumbo1907** [comment]
Thanks a lot!
