### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Innesity** [CraftingStore/Suggestions#540]
**Is your feature request related to a problem? Please describe.**
It's a feature request related to a miss feature.

**Describe the solution you'd like**
Add a way to see on which server a player bought a package. I want to be able to at the commands tab where a command have been succesfully executed and where not. 

**Additional context**

**Comment by Tim-NL** [comment]
Hi,

Thanks for your suggestion!

You can now see on what server a specific command has been executed (at the commands tab of the payment).

-Tim
