### ISSUE TITLE
Extra Options for Variables [Feature Request]

### ISSUE THREAD

**Issue by FrontierPixelmon** [CraftingStore/Suggestions#541]
**Is your feature request related to a problem? Please describe.**
No problem.

**Describe the solution you'd like**
Need more options for variables.

**Additional context**
Would like extra options for variables.
As of now it is very user error friendly, would help to add more options such as "dropdowns", "notebox", etc...

![image](https://user-images.githubusercontent.com/76575430/113907816-6b3fcb00-979b-11eb-8a4b-8ef535e494b5.png)

**Comment by Tim-NL** [comment]
Hi,

This feature request already exists, thus I'm closing this specific issue.

-Tim
