### ISSUE TITLE
Best Feature Requests

### ISSUE THREAD

**Issue by Lizardz** [CraftingStore/Suggestions#543]
**Personalized Timezones**
For someone like me who is in the United States, it's very annoying to have my daily statistics get reset at 5:00 PM (local time) since the counter runs off of Crafting Store's London based timezone. Please give us a webstore setting to choose our timezone!

**Resend Packages**
I can not believe this isn't a thing already, but let us specify which packages to re-run! 99.9% of servers that will use this feature do NOT want to re-run all packages.

**Comment by Tim-NL** [comment]
Hi,

Please check the rules in; https://github.com/CraftingStore/Suggestions

1) Every issue should use the correct template.
2) Do not combine multiple suggestions into the same issue.

You can either update this one to follow the rules and message here so I can re-open it. Or you can create two new ones.

-Tim
