### ISSUE TITLE
Discounts | Idea 

### ISSUE THREAD

**Issue by Rodaviva29** [CraftingStore/Suggestions#544]
Good morning.

The implementation consists of a system of Coupons and Sales involved with certain players, that is, when creating a coupon a specific player would be specified for that coupon to be exclusive to that player, the same could happen with sales but the suggestion and the main focus is on the implementation in the copuns system for specific players.

**Comment by Tim-NL** [comment]
Hi,

We have gift-cards for this, these are for specific players and have a fixed amount that will be used until its empty.

You can also create coupons with a 1-time use limit.

P.S. I'll close this issue regardless, as it does not follow the rules for templates as described here: https://github.com/CraftingStore/Suggestions

-Tim
