### ISSUE TITLE
Higher description character limit

### ISSUE THREAD

**Issue by bobhenl** [CraftingStore/Suggestions#548]
**Is your feature request related to a problem? Please describe.**
Hi, my problem is related to my product page. I cannot add there more info like commands etc. due to the limit of characters.
![image](https://user-images.githubusercontent.com/18662086/115126916-e3e02c00-9fd2-11eb-9eb3-d7a327689657.png)

**Describe the solution you'd like**
I would suggest a higher limit for package descriptions.

**Comment by Tim-NL** [comment]
Hi,

The package limit has been increased to 60.000 characters.

-Tim
