### ISSUE TITLE
Gateway fees

### ISSUE THREAD

**Issue by M4T14SG4M3R** [CraftingStore/Suggestions#55]
**Is your feature request related to a problem? Please describe.**
Feature request

**Describe the solution you'd like**
Add gateway fees like if i choose to pay with paygol i will need to pay extra $2 (the $2 extra is configured by the craftingstore owner)

**Additional context**
For example i set a $2 fee on the paymentwall gateway, any user that choose to pay with paymentwall they will need to pay extra $2

**Comment by TheIronMinerLv** [comment]
Would like to see this too, only with % of original price. Like with ... gateway you need to pay 20% more for a package.

**Comment by Tim-NL** [comment]
Hello,

The feature has been implemented, you can find this in the gateways tab. 

You can choose to have a fixed amount or a percentage of the total. 

-Tim
