### ISSUE TITLE
[FEATURE REQUEST] Google Analytics support for webstore

### ISSUE THREAD

**Issue by Romvnly-Gaming** [CraftingStore/Suggestions#551]
**Is your feature request related to a problem? Please describe.**
I can't use Google Analytics on my web store! There's no option that I can see that enables this support.

**Describe the solution you'd like**
Add Google Analytics support to the Engagement tab! It would be amazing to know how many hits my web store is getting.

**Additional context**
N/A, couldn't find good Google Analytics background.

**Comment by Tim-NL** [comment]
Hi,

You can load any custom blocks, like Google Analytics in your template on Silver and up. We do not support custom scripts/template editors on the free plan.

-Tim
