### ISSUE TITLE
Add legals links in the footer

### ISSUE THREAD

**Issue by Diamax10** [CraftingStore/Suggestions#552]
**Is your feature request related to a problem? Please describe.**
To add "Mollie" as payement gateway, Mollie forces the site to have "Legals", "Terms of use" and "Terms of sale" in the footer of all pages.

**Describe the solution you'd like**
The feature is really simple, just add 3 pages, one for Legals, a second for "Terms of use" and another for "Terms of sale", and add links in the footer.

**Comment by Diamax10** [comment]
Yes Mollie is already on CraftingStore but they need 3 legals pages in the footer.

**Comment by Tim-NL** [comment]
Hi,

Thanks for the suggestion! We just added these to the footer in our default template.

We also added an Impressum to it.

-Tim
