### ISSUE TITLE
A suggestion for Crafting Store!

### ISSUE THREAD

**Issue by JakeSquid** [CraftingStore/Suggestions#553]
Hey there as apart of your store you should add a "Custom" section to intergrade with categories, like for example you add it to a category and then for a rank it would be like

Pick a name: {name}

Choose addon perks
{Example 1} $5 (Would be a check box here)
{example 2} $3 (checkmark)

You can add them to the rank and next time if you wanted to upgrade the addons boxes you can connect all via your username, so it will show what you have bought and what you haven't.

And for example if you wanted to change the name it would allow you for a small cost.

Then for commands you would use like
Commands to execute: lp create group &7[{custom colour}{name}&7] {custom colour}
Like that and it would add perks on if said user selected and payed for them.

For custom colour it would be like this after selecting name: 
Select your colour:
Relate to this colour guide to help you choose please add &(number/letter) or it will not work.

You would also be able to change this at any time for a price, or for example it would be a check box thingy but you can only select 1 at a time then that would intergrade with commands executed too. 

If you need a better description my dm's are always open on discord @JakeSquid#0001

**Comment by Tim-NL** [comment]
Hi,

After looking into this, we've decided to not implement it. Our variables feature does allow most of this, but the way that is described would be out-of-scope, as it would make the process of creating a package very complex. Sorry.

-Tim
