### ISSUE TITLE
Dragonpay Gateway

### ISSUE THREAD

**Issue by Kryzstein** [CraftingStore/Suggestions#555]
**Is your feature request related to a problem? Please describe.**
Is it possible to add dragonpay, Dragonpay is one of the easiest online payment method here in South East Asia.
https://www.dragonpay.ph/ is their website.

**Describe the solution you'd like**
If its possible to implement, if not its ok.

**Comment by Tim-NL** [comment]
Hi,

After looking into the payment method, we decided to not add support for it. We are currently focussing on the larger ones.

Thanks for the suggestion!

-Tim
