### ISSUE TITLE
[Suggestion] Payment Methods

### ISSUE THREAD

**Issue by w41k3r26** [CraftingStore/Suggestions#556]
**Is your feature request related to a problem? Please describe.**

Yes, the problem is that there is a dire lack of payment gateways in the crafting store. Although the integration with the available gateways is flawless and absolutely loveable, the only 2 major gateways that is PayPal and Stripe are not available in many countries.

**Describe the solution you'd like**
There are a few solutions to it but the best ones that come to my mind are:
> 1. Put **Custom payment method,** in a less costly plan, maybe Silver or Gold, and you can put custom menu builder and stuff in the Platinum plan. If you allow more payments in, clients will be able to get more to buy higher packages automatically.
> 2. Get more payment gateways such as skrill, which i know is not currently possible as you already said that in a closed thread, but there are other gateways too such as google pay, 1checkout, and authorize.net.

**Additional context**
It's just a bit annoying to see that just to get payment done I need to pay EUR 25/month. I had almost planned to move to tebex only because of the wider payment options but then thought of making a feature request. I love crafting store and don't wanna move, i invited many of my friends but they cannot join due to lack of payment options and the custom payment option being in such a costly plan.

**Comment by Tim-NL** [comment]
What payment methods would you like to see? (You named "Google Pay", "1checkout", and "authorize.net". 

But what would be the preferred one? 

We currently offer 8 payment methods, and the ability to create your own on the Platinum plan. That is not a "dire lack of payment gateways" in my opinion. 

We can take a look at adding new ones for sure.

-Tim

**Comment by w41k3r26** [comment]
Google Pay and Wise are the two best payment methods that anyone could offer, I am unsure about wise.com integration but Google Pay would be much appreciated.

**Comment by Tim-NL** [comment]
It seems like Google Pay is not something that we can support. After looking through their documentation, I noticed that it isn't an actual gateway. Rather, it's a bridge between the user and the payment method. 

So a user can pay through Google Pay, and they'll handle the process with Stripe for example (the start of the payment). They do not handle giving back any information to us, we'd still have to create a "Stripe" integration in this example. 

And wise.com seems to be pretty much the same as Stripe (cards/bank transfer). So I do currently not think that this would provide much extra payment methods.

-Tim

**Comment by w41k3r26** [comment]
Can you check for Razorpay? https://razorpay.com/
