### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by jonzmuda** [CraftingStore/Suggestions#557]
What would really push your website over others like Tebex would be better templates. Not just basic templates but seriously good ones. For example you are given the option to use a template or start from scratch if you choose use a template it gives you a list and you check off all the features you want. For example say you want ranks on your server you can auto config them with LuckPerms you just choose the name and price and you can customize anything else you want. Say you want Dynmap to show up on your website, check off the box and it will show up. Say you want a support area with live people to answer questions or a robot you can check it off.

**Comment by Tim-NL** [comment]
Hi,

CraftingStore is a donation platform, not a CMS. Our template editor is pretty extensive, you can write code logic (https://twig.symfony.com/doc/3.x/) and do pretty much anything you want with it. 

What you are asking about has nothing to do with the template, what you are describing is a Minecraft website, but we're a donation platform. Things like Dynamap, support tickets, chat, etc. should not be here.

P.S. You are not using the required issue template.

-Tim
