### ISSUE TITLE
Change terms of service page title 

### ISSUE THREAD

**Issue by MinecollYT** [CraftingStore/Suggestions#559]
**Is your feature request related to a problem? Please describe.**
I want to translate it into my language

**Describe the solution you'd like**
Currently it displays "StoreName | terms" but it would be cool if it uses the name given(e.g. Terms of Service) in the language settings. 

**Additional context**
https://discord.com/channels/410794577386274822/422510039916609552/841658705573314591

**Comment by Tim-NL** [comment]
Hi,

The title will now use the one configured at [ Settings -> Language ]. You may need to re-save the language page.

-Tim
