### ISSUE TITLE
Giftcard Balance Module Request

### ISSUE THREAD

**Issue by Busuku** [CraftingStore/Suggestions#56]
**Describe the solution you'd like**
I would like a Module you get a box on your store, where you can add your Giftcard code, and then you can see the balance of the giftcard (Like what Cubecraft has.)

**Additional context**
None

**Comment by Tim-NL** [comment]
Hello,

We implemented the gift-card module. If you are using any custom template, you need to adjust it to work; 
https://github.com/CraftingStore/Templates

-Tim
