### ISSUE TITLE
Virtual Currency

### ISSUE THREAD

**Issue by OwlmanMC** [CraftingStore/Suggestions#563]
A clear and concise description of what the problem is. I would like to have a points system on my server that players would earn by playing and the points they have would be a Virtual Currency that players could spend.

**Describe the solution you'd like**
I would like a virtual Currency feature that could be updated through a in-game command or connect to a database hosted by the user.

**Additional context**
If you need more let me know.

**Comment by MinecollYT** [comment]
I think this is a task for a third party plugin

**Comment by OwlmanMC** [comment]
I didn't know there are third party plugins. Also do they work with the free plan?

**Comment by MinecollYT** [comment]
No, but I mean you have to pay a developer or develop a plugin yourself that gives you a virtual currency that is stored somewhere. And then players could buy gift cards with their points, there is an API for creating them. 

It's not exactly what you want or/and meant, but I don't think a virtual points system would fit into craftingstore.

**Comment by OwlmanMC** [comment]
Ok thanks for clarifying.
