### ISSUE TITLE
Payment Lookup

### ISSUE THREAD

**Issue by EffeDion** [CraftingStore/Suggestions#567]
**Is your feature request related to a problem? Please describe.**
Yes, Currently when you give someone the Payment role, He doesnt have full access to all payments. He cant use lookup and isnt able to create payments.

**Describe the solution you'd like**
Fix the Payment role being able to use lookup. And make them able to create manual payments.

**Additional context**
.

**Comment by Tim-NL** [comment]
Hi,

Thanks for the report!

I confirmed that the lookup did not work, this has been corrected. And manual payments already worked, I also confirmed this on a test store.

-Tim
