### ISSUE TITLE
Use a category as the home page

### ISSUE THREAD

**Issue by hawkfalcon** [CraftingStore/Suggestions#568]
**Is your feature request related to a problem? Please describe.**
Since I have a shop with only a couple of categories, the home page seems like it’s unnecessary. 

**Describe the solution you'd like**
I would like to be about to set a category to be the home page instead. 

**Additional context**
Similar to how Patreon works

**Comment by Tim-NL** [comment]
Hi,

Thanks for your suggestion!

You can now select a category to use as the homepage from here: https://dash.craftingstore.net/admin/settings/webstore

-Tim
