### ISSUE TITLE
Material amount not showing up in-game

### ISSUE THREAD

**Issue by levtey** [CraftingStore/Suggestions#570]
Items' material amounts are not showing up in the in-game GUI

**Expected behavior**
Items should reflect the amounts set on the site

**Screenshots**
![image](https://user-images.githubusercontent.com/60494179/120392083-d95cc600-c2e4-11eb-9065-ea79f15ecb23.png)
![image](https://user-images.githubusercontent.com/60494179/120392122-e4aff180-c2e4-11eb-8007-a0981fdaba27.png)

**Platform**
1.16.5 Purpur-1151

**Comment by Tim-NL** [comment]
Hi,

Thanks for the report, as @thijsa already provided you with the updated .jar, we'll consider this resolved. We expect to release the updated version to the world in the coming days. 

-Tim
