### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by XXAOS** [CraftingStore/Suggestions#572]
So I was messing with the in-game GUI setting for my packages the other day and tried using the cost placeholder in the name of the item but it doesn't work. It would be amazing if it was one day added in the future and would make my in-game shop look a little more appealing. Also with an option to remove the decimal points so its a bit smaller Ex: 100 instead of 100.00

**Comment by Tim-NL** [comment]
Hi,

Your issue does not follow our rules - https://github.com/CraftingStore/Suggestions/blob/master/README.md

Therefore I'm closing it, as described.

-Tim
