### ISSUE TITLE
Bug with text going off screen

### ISSUE THREAD

**Issue by ErnGr** [CraftingStore/Suggestions#573]
**Describe the bug**
The top information of your order goes off the black box

**To Reproduce**
https://parduotuve.mckaktusas.com/     (on your phone)
Pirkinių Krepšelis
The top
The descriptions off order go off screen

**Expected behavior**
For the descriptions to not go off screen (off black box)

**Screenshots**
![image](https://user-images.githubusercontent.com/83455302/120638073-59676500-c478-11eb-899d-9607cd55d494.png)
**Platform**
The platform the problem occurred on. Ex. the CraftingStore website or the Minecraft plugin. 
In case of the Minecraft plugin, please list the details of the environment, such as server type, version.

**Additional context**

**Comment by Tim-NL** [comment]
Hi,

The alternative would be that the table is scrollable so it stays inside the screen.

In my opinion, this would be worse for the user experience, and the store is meant to be used on PC in most cases. So we decided to not change the current (default) behavior. 

![AYxTGJApH7](https://user-images.githubusercontent.com/6275800/124458527-5e784680-dd8d-11eb-9cd2-dc0aedf2e0ad.png)

-Tim
