### ISSUE TITLE
ALL items quantities reset to 1 when applying coupon code.

### ISSUE THREAD

**Issue by 2ic** [CraftingStore/Suggestions#574]
**Describe the bug**
ALL items quantities reset to 1 in shopping basket when applying coupon code. Regular complaints from players. Not everyone realizes the quantities reset to 1 (why would they?), complete transaction and then complains on discord on missing items in-game. 

**To Reproduce**
1. add multiple items with different quantities in the shopping basket
2. apply coupon code
3. all different quantities reset to 1

**Expected behavior**
make it simple, stupid and expected human behavior: players shop for items, add different quantities in the shopping basket. apply coupon. pay. enjoy in-game. Making it backwards as in: apply coupon 1st and then change quantities doesn't work with new players and always require a chat how weird it is. Best comment I got: "my quantities wont reset on amazon when I use coupon code". Yeah...

**Screenshots**
![before and after applying coupon](https://user-images.githubusercontent.com/74799262/120924840-a9763f80-c6a3-11eb-87b1-c8ef10eb65f0.png)

**Platform**
CraftingStore website or the Rust plugin.

**Comment by Tim-NL** [comment]
Hi,

It will only reset quantities if the items are marked as "restricted", meaning that they belong to some kind of special calculation. For example, when they are in a category with "Cumulative packages" enabled, or other player-specific checks. 

This is currently not something that we can resolve without redoing the basket system.

-Tim

**Comment by 2ic** [comment]
It will only reset quantities if the items are marked as "restricted"

![basic package](https://user-images.githubusercontent.com/74799262/120925678-a67d4e00-c6a7-11eb-8e38-ba315f1e027d.png)

**Comment by Tim-NL** [comment]
It is how we call it internally, it is not a setting. It will check if the specific package requires anything special, it will reset the quantity boxes at this moment. We'll have to re-create the basket system from the ground up to resolve that. We did not support quantity at all in the past, and it was not designed with that in mind (In the beginning it was not even designed with a basket in mind) that is why these "annoying" bugs are in there. Re-creating something as complex as the basket system may cause issues, and will take a long time. So we haven't started on that just yet. But it is for sure something that we'll get onto in the future.

-Tim

**Comment by 2ic** [comment]
thanks appreciate that. cheers
