### ISSUE TITLE
[Feature Request] Let players select Server for the purchase.

### ISSUE THREAD

**Issue by sacrilegebr** [CraftingStore/Suggestions#577]
In the Package Editor, under Basics you're required to chose 'Servers', but if you set more than one I assume that the commands for this package will be executed one time each server.

On Minecraft Servers like ours with multiple nodes would be great to have a checkbox with the option "Selectable" or something of this kind.

When marked the player purchasing the package will have to chose from a DownDrop on wich server this purchase will be executed, sending the commands directly to that node.

This will give admins/owners a simple way to create a multi-node shop instead of having to make something like "Parent Category(server)>Category1>Packages" and repeat/edit everything multiple times on each change.

Examples:
![imagem_2021-06-12_012304](https://user-images.githubusercontent.com/71997119/121764772-c46e0700-cb1c-11eb-85d1-1f980af9b5c1.png)

(Select your Server)
![imagem_2021-06-12_012530](https://user-images.githubusercontent.com/71997119/121764811-1adb4580-cb1d-11eb-9c15-81cae319ee17.png)

**Comment by Tim-NL** [comment]
Hi,

This has been implemented. You can now enable "User selects server where commands run (selected servers in the basic tab will be shown". This will add a selector to the package page. The servers selected for the package will be used.

Thanks for your suggestion!

-Tim
