### ISSUE TITLE
[Issue] Subscriptions not working as subscriptions, but as one-time payments

### ISSUE THREAD

**Issue by TalonPhoenix** [CraftingStore/Suggestions#579]
**Describe the bug**
I currently have 10 users that bought my subscription package on CraftingStore, and while the Payment Lookup shows that they purchased it, one ONE of the users (the first user to subscribe) appears in the subscriptions list. It has been 5 days since the second one subscribed, but him and all subscribers afterwards do not appear as subscribers.

I also checked in PayPal, only the first user is appearing as a subscriber, the others are one-time payments. This is a huge issue, that's not how it's intended to work. They should not be going through as one-time payments

**To Reproduce**
1. Compare subscriptions list with a lookup of users that bought the subscription package.

**Expected behavior**
Every user who bought the subscription package (and didn't cancel), should appear in the subscriptions list. The initial subscription should also go through as a subscription payment in PayPal, not as a one-time payment.

**Screenshots**
https://i.imgur.com/Ed0quaN.png
(Subscriptions page on top, Payment Lookup page below)

**Platform**
The CraftingStore website

**Additional context**
I did verify that the package is still set to renew every 1 month.

**Comment by Tim-NL** [comment]
Hi,

When the player tries to buy an item, it will give them two options: Buy or Subscribe.

If they just buy it, they'll get the item as a one-off, and it will run the expiry commands after the set period.

And if they click subscribe, it will renew automaticlly. 

If you do not want that, then you can simply remove the buy now button from the template editor, so only the subscribe button is showing for those kinds of payments.

-Tim
