### ISSUE TITLE
Billing details extraction to a custom gateway

### ISSUE THREAD

**Issue by Leyji** [CraftingStore/Suggestions#580]
**Is your feature request related to a problem? Please describe.**
We need detailed buyer information for custom gateway, such as full name, complete address etc, not just identifier ID as this info is mandatory by gateway we need to use - GoPay.

**Describe the solution you'd like**
Either directly within JSON call (preferably) or via separate API request.
We need a way to extract buyer's details from shop, not just user "identifier", but full info all info provided via shopping cart details.

**Comment by Tim-NL** [comment]
Hi,

When billing details are enabled, we'll now add the information to the user object.
https://help.craftingstore.net/payment-gateways/custom-payment-method-gateway

The documentation shows the names of the fields.

Thanks for your suggestion!

-Tim
