### ISSUE TITLE
Documentation page has formatting issues

### ISSUE THREAD

**Issue by UncleThaodan** [CraftingStore/Suggestions#582]
It's not really a bug, so i'm foregoing the template.

The formatting on [https://help.craftingstore.net/general/what-placeholders-can-i-use/](https://help.craftingstore.net/general/what-placeholders-can-i-use/) is broken.

![image](https://user-images.githubusercontent.com/49715681/122938312-efedbe80-d372-11eb-8c13-06b52cba01cc.png)

**Comment by Tim-NL** [comment]
Hi,

Thanks for the report, should be good now; https://github.com/CraftingStore/craftingstore-docs/commit/17fc9bcd518c0664cb1f3011a414698a0d88d759 

-Tim
