### ISSUE TITLE
Translate the message of accepting the Terms of Service to PT-BR

### ISSUE THREAD

**Issue by ubanning** [CraftingStore/Suggestions#583]
**Is your feature request related to a problem? Please describe.**
No, I just want to suggest a translation

**Describe the solution you'd like**
Translate message: "I agree to the CraftingStore Terms of Service and allow CraftingStore to process my data in this way, and hereby confirm that I am over the age of 18, or have permission from my guardian."
to Portuguese
I already translated to make everything easier for you <3
Translation for PT-BR -> Eu concordo com os Termos de Serviço da CraftingStore e permito que a CraftingStore processe meus dados e, além disso, confirmo que tenho mais de 18 anos ou tenho permissão dos meus responsáveis.

**Additional context**
Translation for PT-BR -> Eu concordo com os Termos de Serviço da CraftingStore e permito que a CraftingStore processe meus dados e, além disso, confirmo que tenho mais de 18 anos ou tenho permissão dos meus responsáveis.

**Comment by Tim-NL** [comment]
Hi,

The translation has been added, thanks!

-Tim
