### ISSUE TITLE
Categories in Categories

### ISSUE THREAD

**Issue by EffeDion** [CraftingStore/Suggestions#584]
**Is your feature request related to a problem? Please describe.**
Not really but it would be a pretty good feature to have added in order to make stores a bit more clear.

**Describe the solution you'd like**
Being able to put a categorie inside of another categorie with a max stack of 3 ( So if you open 1 categorie you get the dropdown and within that one you can get 1 more dropdown. ) The current version does for sure work but the way we have our packages setup it can get ALOT in a pretty small list.

https://effedion.nl/img/Nv7AfvS.png
That way the list is getting pretty long and it would be good to be able to split them into EU and US servers. Problem now is that we have multiple categories with a bunch of packages per servers in there.
https://effedion.nl/img/2Fz6yXX.png

This isnt always optimal as it takes up alot of space and the list is unnecessarily long.

**Additional context**
.

**Comment by Tim-NL** [comment]
Hi,

Sorry, but we won't be able to support sub-sub categories. Due to the small number of stores that would benefit from this, and the complexity of implementing this into the category editor & stores, we decided to not implement this.

-Tim
