### ISSUE TITLE
"Lumen" color schema, but in dark mode

### ISSUE THREAD

**Issue by KickSquareMC** [CraftingStore/Suggestions#586]
The "Lumen" color schema looks really nice with the font and button design and everything, but it makes my eyes burn. Maybe add something with similar design but in dark mode?

**Comment by Tim-NL** [comment]
Hi,

The color schemes are default schemes from Bootstrap. We have our template editor for this, so you can do anything you want with the style.

We are not planning on implementing specific style changes that can be achieved with the template editor. Sorry.

-Tim
