### ISSUE TITLE
Work with Plan

### ISSUE THREAD

**Issue by MinecollYT** [CraftingStore/Suggestions#588]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
It would be cool if some CraftingStore Statistics would be visible in the Plan dashboard.
Link to Plan: https://www.spigotmc.org/resources/plan-player-analytics.32536/

**Additional context**
-

**Comment by Tim-NL** [comment]
Duplicate with #550

Closed as per our rules.

-Tim
