### ISSUE TITLE
More Stripe payment methods.

### ISSUE THREAD

**Issue by SleepingLaura** [CraftingStore/Suggestions#598]
**Is your feature request related to a problem? Please describe.**
Yes, Stripe has a payment option called "Sofort", but you can't select it on the CraftingStore site.

Sofort payment method on Stripe's dashboard:
![](https://fallencdn.xyz/u/gv040dfg.png)

**Describe the solution you'd like**
I would like to see Sofort being added to the payment methods for Stripe.

**Additional context**
Stripe payment methods availible on the CraftingStore site:
![](https://fallencdn.xyz/u/r4b71lzo.png)

**Comment by Tim-NL** [comment]
Hi,

Thanks for your suggestion

Sofort has been added to the list, you should be able to see it within 15 minutes. 

-Tim
