### ISSUE TITLE
Sponge Plugin API Events

### ISSUE THREAD

**Issue by MastefChief** [CraftingStore/Suggestions#6]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to see if possible for the DonationRecievedEvent to be added to the spongle plugin api so i can implement it into my servers plugin.

**Comment by Tim-NL** [comment]
We've added a event that gets called for the sponge version; net.craftingstore.sponge.events.DonationReceivedEvent

You can download the latest version here;
https://cdn.cloudprotected.net/craftingstore/dl/CraftingStore.jar

~Tim
