### ISSUE TITLE
100% Off Coupon

### ISSUE THREAD

**Issue by Craftymatt2** [CraftingStore/Suggestions#60]
**Is your feature request related to a problem? Please describe.**
No, it's not a problem, it's just something id like to see implemented.

**Describe the solution you'd like**
The ability to increase discount percentages to above 99.99% to 100% so I can give out free codes in giveaways.

Also in one error message, you say must be between 0-99.99
and one that says above 95%

**Additional context**
http://prntscr.com/l5owze

**Comment by Tim-NL** [comment]
Hello,

You can now create coupons with a hundred percent discount. 

-Tim
