### ISSUE TITLE
Remove Discord Role on Chargeback

### ISSUE THREAD

**Issue by Epic980** [CraftingStore/Suggestions#600]
**Is your feature request related to a problem? Please describe.**
Chargeback protection for Discord Roles. As for rust stores. I use roles to give permissions in my rust server.

**Describe the solution you'd like**
if someone charges back i want the discord role to be removed

**Additional context**

**Comment by Tim-NL** [comment]
Hi,

Thanks for your suggestion!

You can now select "Chargeback" as one of the options for Discord commands.

-Tim
