### ISSUE TITLE
Stripe - SEPA payment method

### ISSUE THREAD

**Issue by SleepingLaura** [CraftingStore/Suggestions#602]
**Is your feature request related to a problem? Please describe.**
Yes, Stripe has a payment option called "SEPA", but you can't select it on the CraftingStore site.

**Describe the solution you'd like**
I would like to see SEPA being added to the payment methods for Stripe.

**Comment by Tim-NL** [comment]
Hi,

The SEPA Direct method has been added. Thanks for the suggestion. 

-Tim
