### ISSUE TITLE
Option to change the currency on the store.

### ISSUE THREAD

**Issue by SleepingLaura** [CraftingStore/Suggestions#603]
**Is your feature request related to a problem? Please describe.**
People often ask what the price is in USD or other currencies since there is no option to change it on the site.

**Describe the solution you'd like**
An option to select your currency on the store sites so players can view the prices in their currency.
For example:
![image](https://user-images.githubusercontent.com/82168365/127649159-d69d5154-8bf3-46ec-a8a6-eccba807d083.png)

**Comment by EffeDion** [comment]
Would love this to, But doubt this would be possible as i suggested it before. Its hard for them to keep up with the constant changing currency values.

**Comment by Tim-NL** [comment]
Duplicated with #525

Closed.

-Tim
