### ISSUE TITLE
Once paid templates

### ISSUE THREAD

**Issue by alexxdevv** [CraftingStore/Suggestions#604]
**Describe the solution you'd like**

Add pre-created templates that are one-time payment, these templates would only be paid once and would always be available even with the basic plan and would be available in an official section of CraftingStore as if it were a default template. You could buy as many as you want; For example: Design > Templates > Premium Templates (not custom)

**Comment by Tim-NL** [comment]
Hi,

Thanks for your suggestion.

We won't implement this one, the reason that templates are on our premium plans, is because they require more resources to host, serve, and add the ability to change them. A one-time fee won't suffice. 

-Tim
