### ISSUE TITLE
Customizable Discord Claim Command

### ISSUE THREAD

**Issue by EffeDion** [CraftingStore/Suggestions#606]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Make the !craftingstore:claim command for Discord customizable with Premium plans. Pretty sure this would be a thing that is possible and im guessing ALOT of stores would like this as you can remove the current watermark on almost all the places apart from TOS on checkout. And this command just sometimes looks kind of cheap if you ask me.

**Additional context**
.

**Comment by Tim-NL** [comment]
Hi,

Thanks for the suggestion! 

The feature has been implemented. But using Slash commands; https://help.craftingstore.net/premium-features/custom-discord-slash-command/

The old command (!craftingstore:claim) will get removed in the coming months, as verified Discord bots won't be allowed to read chat messages anymore when they are not required to. So we cannot look for those old commands.

-Tim
