### ISSUE TITLE
Emojis

### ISSUE THREAD

**Issue by alexxdevv** [CraftingStore/Suggestions#607]
**Describe the solution you'd like**

Add support emojis on "category names"

**Comment by Tim-NL** [comment]
Hi,

After validating, we've concluded that you can already use emoticons inside the name. But they have to be emoticons with a length of at most 3 bytes. So some emojis are not supported, but most will work. 

The changes required to support all of them require database changes that might have a far-reaching impact on our service during the transition. So we decided to not take that risk. Sorry.

-Tim
