### ISSUE TITLE
In-Game Currency as a payment gateway

### ISSUE THREAD

**Issue by JohnB17** [CraftingStore/Suggestions#612]
**Is your feature request related to a problem? Please describe.**
I have a non-profit server, so the store is all in-game currency,

**Describe the solution you'd like**
I would like in-game currency to be a separate payment gateway

**Comment by Tim-NL** [comment]
Hi,

Would you be able to explain what you mean exactly? We already support virtual currency, but it is not related to the online store.

-Tim
