### ISSUE TITLE
Access a Custom Variable on the Payments tab at PENDING status.

### ISSUE THREAD

**Issue by kdanidev** [CraftingStore/Suggestions#613]
**Is your feature request related to a problem? Please describe.**
Well, not a problem, just would be a great addon for me. I would need this to verify a code which the user wrote in BEFORE I Accept the payment.

**Describe the solution you'd like**
At the Pending Payments tab a box where I can see the custom var input

**Additional context**
-

**Comment by Tim-NL** [comment]
Hi,

Thanks for the suggestion.

This is unfortunately not something that we can implement, pending payments do not include this information (we do also not have this information). It resides inside our payment system (separate from CraftingStore). And is only actually provided to CraftingStore after it is accepted (we'll notify the payment system that it may process it).

-Tim
