### ISSUE TITLE
Checkout - Don't show gateways if there's only 1 enabled payment gateway

### ISSUE THREAD

**Issue by SleepingLaura** [CraftingStore/Suggestions#614]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
If there's only 1 enabled payment gateway, don't show the button to select the gateway.
Instead just remove the button, because it's a useless step if there is only 1 payment gateway.

**Additional context**
What it currently looks like:
![image](https://user-images.githubusercontent.com/82168365/129778491-3197a760-0bf1-4d96-8d30-0d105e40fe6f.png)

What I would like:
![image](https://user-images.githubusercontent.com/82168365/129778565-825b3ad0-efcb-4b25-9c44-516624cb0505.png)

**Comment by Tim-NL** [comment]
Hi,

This is something that you can do yourself from the template editor (replace the buttons with the code below);

```<input type="hidden" name="gateway" value="stripe">```

I believe that this will cause more harm than good, we get a lot of tickets about a lot of things like these that look clear, but will cause confusion. And as this is something that can be added without any intervention from our side, I think its best to not make changes like these a default.

-Tim
