### ISSUE TITLE
Individual item links

### ISSUE THREAD

**Issue by Jorc0** [CraftingStore/Suggestions#618]
**Is your feature request related to a problem? Please describe.**
I think would be great adding an option to be able to get share links from individual items

**Describe the solution you'd like**
Just that, i dont know how would that be done

**Comment by Jorc0** [comment]
When you create a package, would be great having the possibility to get a link of that specific package instead only the category.


> Hi,
> 
> Could you clarify what you mean? What kind of share links?
> 
> -Tim

**Comment by Tim-NL** [comment]
Hi,

You already have this, all packages have this. You can take the URL from the URL Bar in your browser when viewing a package on your store.

-Tim
