### ISSUE TITLE
Sub-Category Ordering 

### ISSUE THREAD

**Issue by jjj700** [CraftingStore/Suggestions#62]
**Is your feature request related to a problem? Please describe.**
When you have a set order you want the sub-category drop down to be in but you cant set it.

**Describe the solution you'd like**
i would like it so you can order sub category like you can order category and packages

**Additional context**
make it so all you have to do is move them along to switch it.https://gyazo.com/cd28044885b66f606136ad42e99a0f39

**Comment by Tim-NL** [comment]
Implemented.

It is now possible to re-order sub-categories. We modified the editor to support dragging the sub-categories inside their section.

-Tim
