### ISSUE TITLE
Coinbase Commerce Integration to accept Crypto Payments

### ISSUE THREAD

**Issue by Leonardo-Fiori** [CraftingStore/Suggestions#620]
**Is your feature request related to a problem? Please describe.**
Nope, not directly. The only way to accept crypto as a payment is using Terminal3, that integrates in turn with Coinbase Commerce. The fact is that Terminal3 applies a very high fee and doesn't pay you in crypto.

**Describe the solution you'd like**
Add Coinbase Commerce integration to support crypto payments. It's easier for server owners since there is zero chargeback risk, and it supports the crypto world which we are hearing a lot about especially about game tokens and cryptos.

**Additional context**
https://commerce.coinbase.com/

**Comment by Shybella** [comment]
This is a must

**Comment by Tim-NL** [comment]
Hi,

Thanks for the suggestion! Coinbase has been implemented, you can now use it directly.

https://help.craftingstore.net/payment-gateways/how-to-set-up-coinbase

-Tim

**Comment by Shybella** [comment]
Holy. This is amazing

**Comment by Tim-NL** [comment]
Hi,

Not all gateways support per-package limiting, if it is not there, it will simply be enabled on all packages. 

There is an open feature request about adding manual payments to the per-package gateways section, so we do plan on adding all the missing ones; Manual, Pagseguro, coinbase, etc.

-Tim

**Comment by Leonardo-Fiori** [comment]
@Tim-NL we received our first donation with coinbase! All fine, money received, except that the transaction does not appear on my craftingstore panel, and the user hasn't received anything yet, because no commands got schedules, and no transaction was received on craftingstore's end.

I triple checked and I did everything correctly following this guide https://help.craftingstore.net/payment-gateways/how-to-set-up-coinbase/

Something seems to not be working, the transaction wasn't registered

**Comment by Tim-NL** [comment]
Hi,

Could you create a ticket on our dashboard? And are you able to share the payload that they provided (if you can see that at your Coinbase dashboard) in that ticket?

-Tim

**Comment by Tim-NL** [comment]
Not sure, but please create a ticket, Github issues are not the place for this. 

-Tim
