### ISSUE TITLE
Custom text input on Checkout page

### ISSUE THREAD

**Issue by Jorc0** [CraftingStore/Suggestions#621]
Give customers the possibility to give us a text we ask for:
I dont really know how to explain this but i made an example
![image](https://user-images.githubusercontent.com/48130077/132950992-b12ac82d-f867-43af-ba61-38b4a7c585c5.png)

**Comment by Tim-NL** [comment]
Hi,

You can use variables for this, you can even use it in your commands.
https://help.craftingstore.net/premium-features/custom-variables

-Tim
