### ISSUE TITLE
Rank Vouchers

### ISSUE THREAD

**Issue by HotProtato** [CraftingStore/Suggestions#622]
Please find a way to account for rank vouchers. What I mean by this, is allow in game rank vouchers to be used and allow players to upgrade their rank, rather than us having to create a payment entry that never technically happened. It only messes up the "Last month" "Last 24 hours" and "Last week" charts having payments that never happened.

**Comment by Tim-NL** [comment]
Hi,

CraftingStore is not aware of in-game items that were bought. You can only do upgrades on items that were bought through CraftingStore.

Having CraftingStore also check any permission plugin, on all servers that are connected, is out of scope. 

P.S. Please use the right format for future suggestions if you create any, as we will close them for not following our rules as stated in the readme of this repository.

-Tim
