### ISSUE TITLE
Mobile mode

### ISSUE THREAD

**Issue by Deeptanil** [CraftingStore/Suggestions#627]
**Is your feature request related to a problem? Please describe.**
I think there should be a Mobile mode for the websites since it's a common feature and makes it look bad after putting in so much work to make it look as good as we can. Mobile mode is where the page looks likemit should even on mobile. 

**Additional context**
I think it should have the feature built in for free.

**Comment by Tim-NL** [comment]
Hi,

Could you clarify this, please? The stores are already mobile-ready.

-Tim

![1PIMhquZV4](https://user-images.githubusercontent.com/6275800/135629919-21666c87-024b-4429-b712-2d47b1478aba.png)

**Comment by Deeptanil** [comment]
No but if I put an image, it doesn't resize it correctly!
It goes Outta the screen.

**Comment by Tim-NL** [comment]
Hi,

You can either upload a smaller image, or give it a "img-responsive" class using the HTML editor when loading images on the page. 

The behavior you are describing is how the page works by default if you do not set specific height/width attributes or classes (that do the same thing).

-Tim
