### ISSUE TITLE
Get all data when exporting

### ISSUE THREAD

**Issue by RafaSojo** [CraftingStore/Suggestions#628]
**Is your feature request related to a problem? Please describe.**

When you export the payment data, the buyer's address is not complete. Only "Address Line One", "Zip Code" and "Country" appear in the billing details. It would be great to also include "City", "State" and "Address Line Two".

**Describe the solution you'd like**
In some cases this information is required and is not exported. It would be enough to add one more field to the csv resulting from exporting the purchases.

**Additional context**
No additional context

**Comment by Tim-NL** [comment]
Hi,

Could you please;
- Clarify what extra field you require? 
- Modify the issue to use the right template as required; https://github.com/CraftingStore/Suggestions

I have closed the issue for now, as stated at the link above: `Issues without a template will be closed.`

**Comment by RafaSojo** [comment]
Sorry, I deleted the template but I put things as indicated. @Tim-NL

**Comment by RafaSojo** [comment]
I just edited it to fit the template.

**Comment by RafaSojo** [comment]
Only "Address Line One", "Zip Code" and "Country" appear in the billing details. It would be great to also include "City", "State" and "Address Line Two".

**Comment by Tim-NL** [comment]
Hi,

Thanks for the suggestion!

The extra values are now added to the export.

-Tim
