### ISSUE TITLE
Coupon command placeholder

### ISSUE THREAD

**Issue by gommzystudio** [CraftingStore/Suggestions#629]
**Is your feature request related to a problem? Please describe.**
I can‘t add a coupon placeholder to a command like {coupon}

**Describe the solution you'd like**
The placeholder should include the coupon. If no coupon was used, then set it to „none“

**Comment by Tim-NL** [comment]
Hi,

Thanks for your suggestion!

Two placeholders have been added:
`{coupon}`: Will be the coupon or nothing when empty.
`{coupon_none}`: Will be the coupon or N/A when empty.

Please do be careful, as player gift-cards are also using the coupon field. So try not to broadcast :)

-Tim
