### ISSUE TITLE
Bulk Buy

### ISSUE THREAD

**Issue by jjj700** [CraftingStore/Suggestions#63]
**Is your feature request related to a problem? Please describe.**
Players want to buy multiple of 1 item and they all want different amounts.

**Describe the solution you'd like**
make it so they can change the quantity they buy at the checkout.

**Additional context**
Current: https://gyazo.com/a4e440b862c48f313e36489f42199288
What we want: https://gyazo.com/d7446151d580aaabe9538082be82f164

**Comment by Tim-NL** [comment]
This suggestion is already suggested here: #14. 

-Tim
