### ISSUE TITLE
Coupon Sales for certain checkout options

### ISSUE THREAD

**Issue by Monjiigames** [CraftingStore/Suggestions#630]
Hello Tim,

I wanted to request a feature whereby if a user purchases packages through a certain payment option (let's say Stripe over Paypal) they get a % off. I'm not a developer of any sort so do let me know if this is not possible 

Many thanks.
Monjii

**Comment by Tim-NL** [comment]
Hi,

Please modify the issue to use the right template (check the readme: https://github.com/CraftingStore/Suggestions). 

As per our rules, I'll close the issue until this issue complies with our rules.

-Tim
