### ISSUE TITLE
Pull top donators list with API

### ISSUE THREAD

**Issue by CatkinFox** [CraftingStore/Suggestions#631]
**Is your feature request related to a problem? Please describe.**
It is not possible to pull a list of your servers top donors using the API

**Describe the solution you'd like**
I would like to see the API added too to include an endpoint to allow me to pull a list of the top donators of my store as a JSON file. This will allow lots of opportunities to use this information in different ways, such as featuring these users on a webpage off the store.

**Additional context**
For our servers website we have a front facing site that lets users read about us, see server status and other information.

We'd like to create a page specially to feature our top donators. Unfortunately we can only do this on our store page and we'd like to display this on the main site.

**Comment by Tim-NL** [comment]
Hi,

Thanks for the suggestion!

We've added an API endpoint that can fetch the last 25 weekly or monthly players (because this is a pretty expensive call to make in terms of database access): 
https://docs.api.craftingstore.net/api/payments

-Tim
