### ISSUE TITLE
Stripe Bug

### ISSUE THREAD

**Issue by leojohnssson** [CraftingStore/Suggestions#632]
**Describe the bug**
When appling Stripe as an payment gateway you are able to choose what sort of payment method the customers will be able to use. (example Card = Visa, Mastercard). But the payment method "Klarna" that Stripe support is not visible on CraftingStore so you can't add Klarna as an payment method through Stripe because the "Klarna" option is not visible when adding Stripe to the payment gateway on CraftingStore.

**To Reproduce**
1. Go to 'Payments'
2. Click on 'Gateways'
3. Scroll down to 'Stripe'
4. Click on 'Set-up Stripe'
5. Scroll down to 'Methods'
6. Here is the error, "Klarna" is not there.

**Expected behavior**
The option of the method "Klarna" should be visible and be clickable to activate Klarna through Stripe.

**Platform**
CraftingStore with Stripe

**Comment by Tim-NL** [comment]
Hi,

Thanks for the report.

Klarna has been added, and you can also select the "Dashboard" option, that will use all payment methods that you have enabled in your Stripe account.

-Tim
