### ISSUE TITLE
Sales/Coupons: Commands

### ISSUE THREAD

**Issue by itslukemango** [CraftingStore/Suggestions#634]
**Is your feature request related to a problem? Please describe.**
I'd like to see the ability to run commands specifically during sales or for used coupons.

**Describe the solution you'd like**
I'd like it to be similar to how Tebex's works you can set an amount they have to hit for the command to run, or just for any purchase made using that sale or coupon. This is good for servers that want to give players a bonus reward for spending X amount during a sale.

**Additional context**
Nope!

**Comment by Tim-NL** [comment]
Hi,

Thanks for your suggestion!

We do have "Community Goals": https://help.craftingstore.net/features/community-goals
You can set specific commands to run when a specific amount has been reached for specific set of packages that you can choose. 

As this does satisfy the first solution you provided, I'll consider this suggestion as "Implemented". If the community goal feature does not help you, feel free to reply.

-Tim
