### ISSUE TITLE
Hide money values for different team roles

### ISSUE THREAD

**Issue by L0thric-HM** [CraftingStore/Suggestions#638]
**Is your feature request related to a problem? Please describe.**
No, it's not.

**Describe the solution you'd like**
The role **designer** can only have access to the template; but that doesn't mean he won't have access to the main page (Dashboard) either. The values can be easily blurred, it would completely solve the problem.

**Additional context**
Nothing extra. Sorry for not understanding the previous requirements.

**Comment by Tim-NL** [comment]
Hi,

The issue does not use the right template as explained in the readme file. Thus I'll close the issue. Please modify it so it follow our rules, and comment so we can open it again.

-Tim

**Comment by L0thric-HM** [comment]
**Is your feature request related to a problem? Please describe.**
No, it's not.

**Describe the solution you'd like**
The role designer can only have access to the template; but that doesn't mean he won't have access to the main page (Dashboard) either. The values can be easily blurred, it would completely solve the problem.

**Additional context**
Nothing extra. Sorry for not understanding the previous requirements.

**Comment by Tim-NL** [comment]
Hi,

Only roles with the "statistics overview" permission can now view the information at the dashboard. The designer role does not have this.

Thanks for the suggestion! 

-Tim

![7vYQU7Znt4](https://user-images.githubusercontent.com/6275800/152222569-da29fd2f-5c00-4886-8ffb-ad81c8a4fdd6.png)
