### ISSUE TITLE
Per-package paymeny method

### ISSUE THREAD

**Issue by TheIronMinerLv** [CraftingStore/Suggestions#64]
Hello,

It would be awesome if I could select with what gateway(s) it is possible to purchase ... package. In a such way more premium packages would get sold with gateways with less fees = more income.

**Comment by Tim-NL** [comment]
Hi, 

How would gateways work with multiple packages in the basket? 

Lets say we have:
VIP, only PayPal is allowed. 
VIP+, all gateways allowed. 

And I add them both to my shopping basket. 

What gateways should be unlocked? 

-Tim

**Comment by TheIronMinerLv** [comment]
I suppose only paypal. It probably wouldn't allow to mix different payment methods (vip2 paypal + vip3 paygol), this idea is from Buycr*ft, you can look it up there..

**Comment by Tim-NL** [comment]
Hi,

It's now possible to select the gateway through the package edit page.

-Tim
