### ISSUE TITLE
Payment Gateway Stripe Additions

### ISSUE THREAD

**Issue by SingularityIO** [CraftingStore/Suggestions#640]
**Is your feature request related to a problem? Please describe.**
We run multiple SEA Servers that requirement payment gateways for their Region, unfortunately with the current setup it's not possible

**Describe the solution you'd like**
Currently Stripe has the ability to incorporate Alipay/Wechat Pay, however due to restrictions they can't be enabled on the store, i'm not sure if this is an issue with Craftingstore or the gateway it's self, however Stripe have said it's not an issue on their end but CraftingStores, is this possible to be looked into? as a good 25% of our donations come from the SEA region which unfortunately right now we're not generating 

**Additional context**
No Additional information.

**Comment by Tim-NL** [comment]
Hi,

Thanks for your suggestion.

You should be able to select "WeChat Pay" at [ Payments -> Gateways ] in about 10 minutes. Could you check if that works for you? Stripe added that method to the supported list not that long ago, so we did not have it in ours.

-Tim

**Comment by SingularityIO** [comment]
I can definitely see WeChat Pay now, much appreciated, covers most of our Chinese players :D, What's the chances of AliPay as well? as that's mostly used by our larger Korean player base and is quite high in demand, from what Stripe said, it should be available
