### ISSUE TITLE
Higher Package Character Limit

### ISSUE THREAD

**Issue by EffeDion** [CraftingStore/Suggestions#643]
**Is your feature request related to a problem? Please describe.**
Somewhat yes, Im having to remove alot of spaces in order to fit the full package name quite a couple times.

**Describe the solution you'd like**
add 4 or preferably 8 extra characters to the limit.

**Additional context**
-

**Comment by Tim-NL** [comment]
Hi,

The limit has been raised, the names should now fit.

-Tim
