### ISSUE TITLE
The possibility to higher the in-game price. 

### ISSUE THREAD

**Issue by Americaantje** [CraftingStore/Suggestions#645]
**Is your feature request related to a problem? Please describe.**
In my server it's easy to earn the coins. So it would be nice if we could ask a higher price for some roles. (1.000.000+ for example).

**Describe the solution you'd like**
The ability to higher the price up to 1.000.000+.

**Additional context**

**Comment by Tim-NL** [comment]
Hi,

Thanks for your suggestion.

The limit has been raised to `999999999`. That should be sufficient for almost every economy, even ones that are drowned in inflation ;)

-Tim
