### ISSUE TITLE
Add packages directly to basket

### ISSUE THREAD

**Issue by thekdub** [CraftingStore/Suggestions#647]
**Is your feature request related to a problem? Please describe.**
Currently to add a package to your basket you have to click `More info`, scroll to the bottom of the package info, click `Buy now`, and then you get another page with the same package info you just viewed and an `Add to basket` button.

**Describe the solution you'd like**
Add an `Add to basket` button below/next to the `More info` button for each package, allowing users to add them directly to their cart from the package list.

Additionally, removing the extra page of the package's details would be nice as it's redundant. I understand having the page exist for direct linking to the package, but for navigating the webstore, it seems unnecessary. The `Buy now` button in the initial package info popup could be changed to `Add to basket` instead.

**Additional context**
Screenshot of `Add to basket` button implemented on package display (grid view): 
![image](https://user-images.githubusercontent.com/12961363/146869577-ed6cf424-60e1-468b-b903-a2fe9439577f.png)

Screenshot of `Add to basket` button implemented on package display (list view):
![image](https://user-images.githubusercontent.com/12961363/146869507-3811301d-af87-4436-adf9-b4077ded5e88.png)

Screenshot of `Add to basket` button implemented on package info popup:
![image](https://user-images.githubusercontent.com/12961363/146869768-feaa2560-0f74-4732-be47-251ebcfb4382.png)

**Comment by Tim-NL** [comment]
Hi,

Thanks for the suggestion.

If you'd want you can technically do this already. If you have a basic store that does not require all features you can do it like this;

You can put the <form> from the package page directly in the category.twig template. But a lot of features will break. The server selector won't work, the steam login won't work, the variables feature won't work, etc. The extra page might be redundant for basic packages, but it is required for some core functionalities to work. 

If you only have basic packages this way will work with pretty minor changes to the template. But as it will cause confusion, this is not something that we'd want as a default.

-Tim
