### ISSUE TITLE
Add input area labels to shopping basket page

### ISSUE THREAD

**Issue by thekdub** [CraftingStore/Suggestions#648]
**Is your feature request related to a problem? Please describe.**
Currently, there are no labels on input areas on the basket page, aside from the placeholder text within text boxes.

**Describe the solution you'd like**
Add labels to input areas to improve page readability.
While not absolutely necessary, I find they improve the appearance of the page, and make navigation much easier.

**Additional context**
Example of the shopping basket page with input labels added:
![image](https://user-images.githubusercontent.com/12961363/146870145-ca4db1bc-e92a-48bb-a8eb-d67a8d89232d.png)

For reference, here's the shopping basket page without input labels (as it current is):
![image](https://user-images.githubusercontent.com/12961363/146870226-cd14166b-7255-41c4-bc23-482f434089c9.png)

**Comment by Tim-NL** [comment]
Hi,

Thanks for your suggestion.

To me it sounds redundant to have those there as the same thing is already said in the text itself. 

I think this is something that is up to individual store owners, and with our Silver plan anyone has the ability to add them if they want, so this is not something that we will implement as a default (changing defaults like those is already pretty annoying for existing stores that get extra text in (possibly) the wrong language).

-Tim
