### ISSUE TITLE
Support for RCon for vanilla servers

### ISSUE THREAD

**Issue by ImTiara** [CraftingStore/Suggestions#65]
**Is your feature request related to a problem? Please describe.**
Well the only problem i find with the current solution is that vanilla servers wont be able to use CraftingStore at all but only spigot / bukkit etc will.

**Describe the solution you'd like**
To select/enable this feature you should do it in the categories "Servers", "Edit my server" or "Create new server" options. Once the option is selected you should be able to put in the host address, RCon port & the RCon password.

In the "Packages" category once you create a new package or editing a package, A option called "RCon" can replace the "Commands" tab where you can choose what commands to be executed through rcon.

**Additional context**
I think this idea would attract more customers (such as me) to use CraftingStore.
Thank you for reading and i hope this feature will be implemented very soon

**Comment by Tim-NL** [comment]
Hi, 

We build in RCON, you can now select this per server. You can add (or edit) a server and set it's connection type to "RCON". It will show the IP/port/pass fields. It won't send the commands over the normal system when this is enabled. 

-Tim
