### ISSUE TITLE
Spice the cyborg theme up.

### ISSUE THREAD

**Issue by RyderBelserion** [CraftingStore/Suggestions#654]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Cyborg theme is the dark mode I'd like to have however, There is a few oddities....

General text across the board on Module Headers, Navbar, Module subtext etc. The hex color it currently is right now is #888888. Could be nicer to have a lighter color!

The navigation bar is solid black which just doesn't match the rest.

The close button on packages could have a darker text to it...

**Additional context**
No

**Comment by Tim-NL** [comment]
Hi,

We offer the ability to modify the HTML & CSS on silver and up, you can make any change you desire.

-Tim
