### ISSUE TITLE
1 time purchase bypass

### ISSUE THREAD

**Issue by ReneRuts** [CraftingStore/Suggestions#662]
**Describe the bug**

I tried with some settings to make sure that if you buy A for example you can't buy it anymore but you can still buy B. But when I went to the cart via B, A was still in it and I could delete B, which means that it's not 1 time purchase.

with quick enough clicking I can manage to have 2 in there at once again even though I may only buy one in a life time.

**To Reproduce**
1. Go to package settings
2. Add multiple different things
3. Add that you can only buy it once on every package
4. on package 2 you add that you must have package 1
5. on package 3 you add that you must have package 1 AND 2 and so on
6. then add a custom payment with your username and that you bought package 1 and 2
7. then try to add package 1 and/or 2 in basket
8. then an error should pop-up because you can only have it once
9. THEN retry step 7 and 8 multiple times
10. After a few tries you will see that you have package 1 or 2 AND 3 inside your basket.
11. now remove package 2 and you can buy package 1 again.

**Expected behavior**
The item that you already bought should not appear in the basket to be able to rebuy it because it's a one time thing.

**Screenshots**
1.  The proof of already having package 1 --> https://gyazo.com/1e91ef290787ffcf0bc262cc42b50a6b
2.  The settings of package 1, 2 AND 3 --> https://gyazo.com/97ebf7cd8f0d812c3519eb99ef902dca
                                                              --> https://gyazo.com/55de4f28194b40e7ba8e51a314839a18
                                                              --> https://gyazo.com/f6e971e77dcfe2c72f10d657d963d1b0
3.  The proof of both packages being inside the basket --> https://gyazo.com/83544f4ceb05306051581d8a6ef188ab

**Platform**
PC, windows 10, using microsoft edge.

**Comment by Tim-NL** [comment]
Hi,

Thanks for the report!

There will always be ways to get a "limited" package into the basket (like: Having open another browser with another basket). But to make sure that this won't be an issue in the future, it will now check this again when the user actually clicks checkout. If they have invalid packages, it will reject their basket (annoying, but this should only happen when the package should not be there in the first place).

-Tim
