### ISSUE TITLE
Influencer Referral Codes at Checkout

### ISSUE THREAD

**Issue by ZepsiZola** [CraftingStore/Suggestions#664]
**Is your feature request related to a problem? Please describe.**
In order to get an Influencer to do a partnership with a server, the Server Owner has to negotiate for a price that best fits both the Influencer and the Server Owner's wants. On top of that, once you've negotiated for one price with one Influencer, there's no guarantee that you will be able to agree on the same price with another Influencer. On top of that, you also have to remember that the price of partnerships also varies based on the size of the Influencer. On top of that, you have to understand that some Influencers may have more subscribers, but get less views or if the Influencer's audience isn't exactly the type of people to join a Minecraft server. So, you have to try and adequately estimate how much money you'll make from each and every separate Influencer that you make a deal with. This is a tedious and frustrating routine that puts me off making deals with Influencers.

It's also a risky procedure since the Server Owner is typically expected to pay up front and there's no guarantee that deal will be profitable.

Even if you do strike a 'fair price' on the deal, the influencer can easily just take your money and make a lackluster video that doesn't really portray the server in the best way possible. Influencers are in no way incentivized to make a good video on your server.

**Describe the solution you'd like**
My suggestion is a feature where a customer can voluntarily enter in an "Influencer Code" at checkout which causes the respective Influencer to receive a portion of the profit.

So it would happen like this...
1. Server owner contacts Influencer offering portion of profits from players that use the Influencer's "Influencer Code" in the store.
2. Influencer makes video/post featuring the server.
3. Influencer mentions "If you go to this server and feel like buying something, enter in code "KENNY" at checkout and I get a portion of the money. By doing this you would not only get cool stuff in the server, but you'd also be supporting me as a Youtuber".
4. Audience of that video goes to the server and plays there.
5. Some of the audience buys something from the store.
6. Server gains players and makes money. Youtuber makes money from server as well.

**Additional context**
I remember Fortnite doing a thing like this where Gaming Streamers and Youtubers would play the game on Stream and also promote their "Creator Code" and they would get a portion of the money from their audiences purchases of V-Bucks. Obviously that worked out pretty well for them.

This would make it so much easier to do partnerships with different Influencers because the amount they get paid from the partnership is directly related to how many views they get on that video. Also it would allow a Server Owner to "mass produce" advertising because they can contact a large and diverse range of influencers and offer them all the same exact deal. With this method, I could keep my playerbase filled to the brim with a constant stream of new players because there are hundreds of small/medium Minecraft Influencers who have sizeable audiences, but don't necessarily make much from ad revenue. For small Minecraft Influencers, this deal could likely be the most money they've made directly from videos since it would pay significantly more than ad revenue.

This would also require that the store correctly handles these purchases and is able to split the money up and direct it to both the Server Owner and the Influencer at the same time. If that's not entirely possible, you could simply just make it so that the Server Owner gets all the money initially but they can see how much money they owe the Influencer in the store's backend and they are automatically invoiced by CraftingStore each week to pay up the owed money and then CraftingStore acts as the trusted 3rd party middleman by paying the Influencer. If that's not possible, then you could just make it so that the Server Owner can see how much they owe the Influencer in the backend and take it upon themselves pay the Influencer their money.

I think this is a really good idea for a feature since it would not only make promoting the server easier, but it would also make it easier to keep a server profitable and sustainable, because if the server starts to run low on players, the Server Owner can just do another round of Influencer Partnerships and have lots of new players almost instantly.

This feature also allows the Server Owner to have no capital at risk when they do a partnership since both parties only make money _after_ the Influencer promotes the server.

It also causes the Influencer to be incentivized to promote the Server in most favorable way so that they can get the highest amount of their audience playing on the server and using their code in the store.

The more I keep writing about this, the more I realize why it's such a genius feature. There are so many benefits. It would make paid promotions a much less risky endeavor and, as a result, make it easier to quickly build a large player-base.

Also I don't think any of the other Minecraft server store sites have this feature, so if you implement this, you'd be the only ones  on the market to do it. This would also allow you to control a larger portion of the market. Plus, you could make it a feature that only premium users of Craftingstore have access to, causing you guys to make more money from people upgrading to premium.

Please give some feedback on whether you think you'll do this feature or not, because I'm really eager about this and if you're not gonna implement it then I'll pursue executing in some alternative way.

**Comment by Tim-NL** [comment]
Hi,

Thanks for your extensive request. 

Unfortunately this is not something that we can implement in a way that would be useful. 

Payments are all between the buyer and the store owner - They never reach our accounts, this is by design.

If we'd have to invoice store owners we'd have to chase after the money. There are a lot of risks for all parties;

If we'd invoice the store owner:
- If they don't pay us, we wou'd have to correct our bookkeeping or send someone after them (like a debt collector)
- YouTubers of server owners that do not pay through our system would not get anything. And because it's our system, it opens us up to be liable for the money they are owed.
- We cannot just payout a YouTuber, you cannot just take money from a business account and pay it to a person (as far as I understand). There are legal requirements.

If the store owner would pay it themselves:
The same things applies, and you'd be back where you started without any system like this.

It's just too big of a risk for us, and the YouTubers to have such a system, as we do not process the actual money, it's all between the buyer and the seller. We do not take cuts or anything like that.

-Tim
