### ISSUE TITLE
Statistics packages

### ISSUE THREAD

**Issue by Bubenik1** [CraftingStore/Suggestions#67]
So if people buy multiple things at once, it get stored as 1 package in the statistics. For example they bought a rank, claimblocks and keys then the statistics will see that as one package.

It would be cool if statistics count everything as it's own package, so you can easly see what you've sold and how many.

**Comment by Tim-NL** [comment]
Hi,

Thank you for the report! We added a new range selected and optimized the code for the statistics system. This included fixing the issue you are describing. 

We are converting our database to support this change as we speak, the stats should  be correct in one hour. 

-TIm
