### ISSUE TITLE
Different Currencies Displays for Different Customers

### ISSUE THREAD

**Issue by SpookyKipper** [CraftingStore/Suggestions#676]
**Is your feature request related to a problem? Please describe.**
Nope, I just came up an idea of a suggestion.

**Describe the solution you'd like**
I hope that there will be a button that we can click and change the local currency display (Like my default store is HKD but one customer will be USD while displaying), but it won't change the currency while checkout. Like USD Display customers will see it as HKD on PayPal.

**Additional context**
Screenshot: https://i.imgur.com/gx1LDCk.png (Captured from InvadedLands Store, It's tebex but I want it to be added on CraftingStore as I'm not satisfied with Tebex)

**Comment by Tim-NL** [comment]
Hi,

Closed as it's a duplicate with #525 

-Tim
