### ISSUE TITLE
Support Symbols in searching Minecraft Names

### ISSUE THREAD

**Issue by ExEndV2** [CraftingStore/Suggestions#681]
**Is your feature request related to a problem? Please describe.**
I want to search for a geyser player which has symbol "*" prefix, and it doesn't let me to search the history of that player. 

**Describe the solution you'd like**
I would like symbols like "*" be supported in that case.

**Additional context**

Images:
Searching for a name:
![image](https://user-images.githubusercontent.com/19740277/172440290-0006e8b1-63bf-436f-afda-0815d5d7cb4e.png)

Error Output:
![image](https://user-images.githubusercontent.com/19740277/172440391-a0c6cd1e-4e95-49a6-9d0c-607ada15dc0c.png)

**Comment by Tim-NL** [comment]
Hi,

Thanks for your report, you can now use all characters in there, this limitation is very odd with all the new game types that we added over time.

-Tim
