### ISSUE TITLE
Global Commands - minimum spend.

### ISSUE THREAD

**Issue by pacificminer** [CraftingStore/Suggestions#685]
**Describe the solution you'd like**
Tebex offers to run global commands when a minimum spend has been reached. This allows you to setup a promotion where the player has to spend X amount to receive bonus rewards. For example, spend 30 euro in the store in a single payment and get whatever is configured in the global command as a bonus reward.

![image](https://user-images.githubusercontent.com/24826002/173209210-e403b580-ff6d-4760-ac08-8847bf0eaabc.png)

**Comment by Tim-NL** [comment]
Hi,

Thanks for the suggestion!

You can now enter a minimal amount for global commands. 

-Tim

**Comment by pacificminer** [comment]
Amazing work. Thank you!

Den tir. 21. jun. 2022 kl. 14.13 skrev Tim Kwakman ***@***.***
