### ISSUE TITLE
Recipt Numbers

### ISSUE THREAD

**Issue by AceNetAW** [CraftingStore/Suggestions#686]
We would like to give our users quality recipts and need an option to sort them in the emails, so we suggest an option like "recipt numbers".

People who used CraftingStore should be able optionally add the context like "{recipt.number}" as an optionally placeholder.
so in the email the number is generated that the recipt are (payments number = recipt number).
So when the 450th User buy an package and got the email, it should send automatically this one with the custom placeholder like "Recipt number: 0450" or anything.

**Comment by Tim-NL** [comment]
Hi,

Emails with a payment confirmation are only for the user, so they can see their items and request their data as required per the GDPR.

They are not invoices, and such, will not get an invoice number.

-Tim
