### ISSUE TITLE
Discord bot custom name / logo / status

### ISSUE THREAD

**Issue by EffeDion** [CraftingStore/Suggestions#687]
**Is your feature request related to a problem? Please describe.**
No not really.

**Describe the solution you'd like**
Be able to make the discord bot have a custom name, logo & status.

**Additional context**
.

**Comment by Tim-NL** [comment]
Hi,

The feature has been implemented, thanks for the suggestion!

See this article: https://help.craftingstore.net/premium-features/custom-discord-bot/

-Tim
