### ISSUE TITLE
Server Status Module Version Support

### ISSUE THREAD

**Issue by thekdub** [CraftingStore/Suggestions#688]
**Describe the bug**
The 'Server Status' module breaks when attempting to check the status of older Minecraft servers.

**To Reproduce**
1. Go to 'Design' -> 'Modules'
2. Create a new 'Server Status' module
3. Set the IP address / Hostname and Port to that of an older Minecraft server (e.g. Tekkit Classic which uses Minecraft 1.2.5)
4. Save the module
5. View the store
6. An error displays in the browser JS console indicating that it "Cannot read properties of undefined (reading 'online') in store.js:105; additionally, no information about the server is displayed in the module box.

**Expected behavior**
The module should provide an accurate count of players online as reported by the targeted server, as well as the online status of the server.

**Screenshots**
![image](https://user-images.githubusercontent.com/12961363/174459279-9ac7ba58-f298-495a-acb2-1c147f97e591.png)
![image](https://user-images.githubusercontent.com/12961363/174459281-a9df7c3d-99f0-4ad8-8787-d5f390726f97.png)

**Platform**
CraftingStore website

**Additional context**
More information on handling previous version server list ping data can be found here: https://wiki.vg/Server_List_Ping

**Comment by Tim-NL** [comment]
Hi,

The status is fetched using an external service, and as such we have no control over how it handles older versions. Considering that those versions are not supported, we will not look into resolving this specific issue, sorry.

-TIm

**Comment by thekdub** [comment]
Found this: https://docs.mcstatus.io/routes/status

Tested and working with 1.2.5 and 1.17.1, so it should support every version of Minecraft. I'd recommend switching the external service used to this one.

**Comment by Tim-NL** [comment]
Hi,

Seems like a highly unreliable service: https://uptime.mcstatus.io/ - As per their own status page. So that won't be a service that we are going to use.

-Tim
