### ISSUE TITLE
Coupons do not work for multiple item quantities

### ISSUE THREAD

**Issue by Zenya4** [CraftingStore/Suggestions#69]
Title says it all. I’m not sure if it’s fixed yet but Tim told me to create a report here. More info in the video https://streamable.com/50ywl . Thanks in advance!

**Comment by Tim-NL** [comment]
Hello,

Is this still on-going? I can't re-produce the issue.

-Tim

**Comment by Zenya4** [comment]
Yes, it is still an on-going issue, unfortunately :(

Is there any more info or data I can provide to aid you in solving this?

**Comment by Tim-NL** [comment]
Are you using any custom templates on your store? 

-Tim

**Comment by Zenya4** [comment]
By custom templates do you mean custom backgrounds and stuff? I'm on the Free plan but a few things are modified (like background, some text, etc)

**Comment by Tim-NL** [comment]
Hi,

The issue is now resolved. If you're using a custom template, check out this article: https://help.craftingstore.net/books/others/page/custom-template-new-basket-format. 

If you're on the default one, it will just work.

-Tim
