### ISSUE TITLE
Coupon Creation with the Java API

### ISSUE THREAD

**Issue by Dante5657** [CraftingStore/Suggestions#691]
**Is your feature request related to a problem? Please describe.**
So basically we are running a sub server that allows players to collect a currency and withdraw coupons with it. But we have to fill the coupons system manually with coupons we create through the website which takes a lot of time considering we need to generate tens of coupons every day.

**Describe the solution you'd like**
This could easily be sorted by adding a java API method to create coupon items, That gives you the code when you click on it (Or any other way that's convenient) (This requires the API to create the code and add it to the coupons database as well)

**Comment by VergilPrime** [comment]
Doing this via command (say in console) seems like it would be very useful.
