### ISSUE TITLE
Include Billing Details in HTTP POST after purchase

### ISSUE THREAD

**Issue by collectVood** [CraftingStore/Suggestions#692]
**Is your feature request related to a problem? Please describe.**
Upon purchase for legal reasons we are required to send our clients an invoice. Without having the billing details in there, we cannot really properly work with the data and generate an invoice in our systems (billing details are required to be included on the invoice).

**Describe the solution you'd like**
When the HTTP POST is sent, include billing details in the POST if enabled by the Webstore.

**Comment by Tim-NL** [comment]
Hi,

The new JSON based webhook system has been added: https://help.craftingstore.net/premium-features/webhooks/

You'll have to write your own JSON (to make it work with pretty much any system), and the data should be verified using a hmac that you have to check with the shared secret to verify that the request is coming from us. Or if you point it to something like a Slack webhook, then that is safe enough in some sense, as the webhook URL contains some kind of secret in the URL that nobody will guess. 

-Tim
