### ISSUE TITLE
Imported Transactions using Package Price for Cumulative Pricing

### ISSUE THREAD

**Issue by thekdub** [CraftingStore/Suggestions#698]
**Describe the bug**
When importing transactions, rather than using the imported payment price for cumulative pricing, instead the package price is used. This is inconsistent with the expected function of cumulative pricing, where prices are reduced by the amount paid, not the original package price.

**To Reproduce**
1. Create a category of cumulative packages
2. Import transactions which are mapped to those packages, where the transactions have differing amounts paid from the package prices
3. View the webstore as one of the imported transaction users
4. See a discrepency between amount paid vs amount deducted.

**Expected behavior**
Cumulative pricing should use the amount paid for imported transactions, not the package price.

**Screenshots**

**Platform**
CraftingStore Website

**Additional context**

**Comment by Tim-NL** [comment]
Hi,

The behavior described is expected. A payment might contain multiple packages, and we only get the ID's in the CSV so there is no way to see what package has what price. So we have to use the prices that you configured at the dashboard.

-Tim
