### ISSUE TITLE
!Giftcard not working properly!

### ISSUE THREAD

**Issue by DyrhoThomas** [CraftingStore/Suggestions#7]
There are huge issues with giftcard, will set new balance to last cost and stuff. make it able to pay part of the total costs and pay the other part through paypal or so.

**Comment by Tim-NL** [comment]
If you gift-card does not have enough funds, it will allow the player to pay the remaining amount with PayPal for example. 

And can you explain the issue in more detail, I'm not sure what issues you're facing. 

~Tim

**Comment by DyrhoThomas** [comment]
Just tried it again, when I add a giftcard with not sufficient money left, it won't use it but it won't return any error message.
When I bought a package for 2,99 euro with a 19,99 euro giftcard, on my overview it says my total amount left is 2,98999 and a lot of nines, which should be 17 euro if I'm correct. I guess it just takes the amount you payed and then that will be your total amount left.. So now players can technically buy whatever they want as long as it is cheaper as previous bought item and lower as your original amount

**Comment by Tim-NL** [comment]
I tested this multiple times, and this is not happening from here. Can you provide the package ID's you tried, and the payment ID of this payment? You can find this information in the URL bar.

~Tim

**Comment by Tim-NL** [comment]
The issues regarding giftcards are now fully fixed. I implemented multiple safe-guards, and tested them for a long time. 

~Tim
