### ISSUE TITLE
Placeholders

### ISSUE THREAD

**Issue by Hackuou** [CraftingStore/Suggestions#71]
More player specific placeholders %player_amountspent% this will show the total amount a player has spent at the store, maybe a %player_amountlastspent%.
%player_package the current highest package of the player.
A few others other people or you might come up with as well but that's a start, maybe when they bought the package etc.

**Comment by Tim-NL** [comment]
Sorry for the delay.

Unfortunately, we will have to decline this request. This player-specific data would require the plugin to know everything about every online player. Storing all this information on the Minecraft server would be a lot of data for big servers.

-Tim
