### ISSUE TITLE
Random problems with xsolla

### ISSUE THREAD

**Issue by TheIronMinerLv** [CraftingStore/Suggestions#76]
Hello. I have been using xsolla with Craftingstore for a few months now. But there are sometimes some issues with purchase for few customers. 

It seems like xsolla "hates" their username or something as if they use any other username, everything works. They are not banned or whatnot on xsolla side, I already checked.

A customer sent me this, same error was for others too: https://i.imgur.com/vB14PH1.jpg

Could you help somehow? Thanks.

**Comment by Tim-NL** [comment]
Hello,

Can you share some of the names that failed?

-Tim

**Comment by TheIronMinerLv** [comment]
Hi,

Here a one that doesn't work with xsolla: **Podrinkis**

I'll edit in some others too in a moment.

**Comment by TheIronMinerLv** [comment]
Bump

**Comment by Tim-NL** [comment]
Sorry for the delay.

We are unable to reproduce the problem, is this still persisting? 

-Tim

**Comment by TheIronMinerLv** [comment]
If I will receive another report of this, I'll reopen this.
