### ISSUE TITLE
Can't set limit on yearly package

### ISSUE THREAD

**Issue by M4T14SG4M3R** [CraftingStore/Suggestions#78]
**Describe the bug**
I tried to set a limit for the packages called "Unban ()", so a player can only buy it one time, but it doesn't work, when i click on update package it reloads the page and the limit is on 0 again, it happens with the global limit and user limit, it only happen with the yearly limit

**To Reproduce**
1. Select a package
2. Try to set global or player limit to Yearly
3. Click on save package
4. It will reload the page instead of updating the package

**Expected behavior**
It should set the yearly buy limit for that package but it sets to 0 (unlimited)

**Platform**
CraftingStore

**Comment by Tim-NL** [comment]
Hi, 

The issue has been resolved.

-Tim
