### ISSUE TITLE
Team Account A Way To Go More In-depth With Permissions

### ISSUE THREAD

**Issue by Hipopotofobia** [CraftingStore/Suggestions#79]
Currently when adding a team member to the panel they have full access automatically and there is no other option, like limited or custom.

My suggestion is that you add pre-set roles like moderator, admin, manager, etc. Which each have their own abilities that are limited. Also maybe a Custom role so that the owner of the panel can set certain perms only to that specific person.

This was stated by Tim-NL on July 24, but wanted to add a bit more to that and bump it up a bit as it would be very useful.

~ Thanks, Hipo

**Comment by TheMonDon** [comment]
I came here to say I wanted to have this feature, but I guess you already have. Please tim? Soon ;)

**Comment by Tim-NL** [comment]
Merged with #24
