### ISSUE TITLE
Ability to cancel package in game.

### ISSUE THREAD

**Issue by MisterZet** [CraftingStore/Suggestions#8]
Hello, I saw this feature on SaicoPvP. Where someone buys something out of the store, they write: /redeem in game, then they can accept it or cancel. This would be really useful & good for people incase they didn't bought it & someone else bought it for him. Because that happens much for Youtubers.

**Comment by Tim-NL** [comment]
This is something that can be implemented in-game in one of your own plugins, instead of calling a "group set" command, you can call your own plugin that will ask the player. However, I think this may be a great feature, I'll look into adding this to the platform, thank you!

~Tim

**Comment by MisterZet** [comment]
Wait, you can cancel it through out plugin? when someone pays where the money is hold? I know paypal can hold money for 30 days, then it's automatically canceled, I think that's how it works in SaicoPvP

**Comment by Tim-NL** [comment]
I don't think this has anything to do with the payment itself, it's if the commands should be processed or not. You can't hold the payment at PayPal from CraftingStore.

~Tim

**Comment by MisterZet** [comment]
So would I cancel the payment with a external plugin?
