### ISSUE TITLE
Package expiration commands not being sent to game after package expiration timer.

### ISSUE THREAD

**Issue by Krerelath** [CraftingStore/Suggestions#80]
Hi there, I am experiencing issues with setting a package expiration time  and getting the expiration commands to be sent based on this time.

I tested with an expiration of 5, 15 minutes and multiple hours and the commands weren't executed, I have tried multiple server restarts.

Additional info:
 I have the expiration command set to "Execute directly" and have also tried the version where the player needs to be in game.
Server version Spigot 1.13.1
Plugin version with the title "Fixed server crash when the API was not responding."

**Comment by Tim-NL** [comment]
Hi @Krerelath, 

Can you share one of the payment IDs with this issue? It's in the URL. Please only share the ID, as this is a public location. 

-Tim

**Comment by Krerelath** [comment]
Here is the most recent purchase made and the ID: 107173

It was set to expire one hour after purchase.

**Comment by Krerelath** [comment]
@Tim-NL ere is the most recent purchase made and the ID: 107173

It was set to expire one hour after purchase.
