### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ChiefJava** [CraftingStore/Suggestions#82]
When you duplicate a package, it will save the image

make it so we can do `The name may not be greater than 20 characters.`

sometimes the image just disapear

**Comment by samkelley86** [comment]
https://gist.github.com/samkelley86/ac4cf8c6a5ddb0eb0edf4610b7f7f229
server is crashing with the plugin

**Comment by Tim-NL** [comment]
@samkelley86 Can you please create a new issue with this gist? As these issues are not the same, and they both need to be resolved by someone else. 

-Tim

**Comment by Tim-NL** [comment]
Hi,

The name limit has been raised to 40, from 30. And the bug regarding images being removed on updates is not resolved.

Also, the image should go with the package when you duplicate, as it's a copy action. It will copy the package one on one.

-Tim
