### ISSUE TITLE
Minecraft Plugin Error - Ver2.0.2

### ISSUE THREAD

**Issue by ChiefJava** [CraftingStore/Suggestions#84]
**Describe the bug**
there is 2 Skyblock * Dream
and it should be only 1
that 1 bug
and all the other catagorys are sub-categorys

**To Reproduce**
just see the ss

**Expected behavior**
i expected to have only 1 category *Skyblock * Kingdom*
and few sub-categorys in the category

**Screenshots**
https://gyazo.com/599d109b6d52411aa7d34e8b7ad2eb0a

**Platform**
Minecraft plugin, Skyblock server, 1.8.9 version.
plugin version 2.0.2

**Additional context**
N/A

**Comment by Tim-NL** [comment]
Hello,

The issue has been resolved, you might need to restart the server for this to take effect. 

Thank you for the report!

-Tim
