### ISSUE TITLE
Special Requests

### ISSUE THREAD

**Issue by ChiefJava** [CraftingStore/Suggestions#87]
** Feature Request #1 **

**Is your feature request related to a problem? Please describe.**
Team Permission 

**Describe the solution you'd like**
to give permission to the team in the site
Packages |  View , Create / Edit, / Delete
Payments | ""
Settings | ""
and all the features in your site.

** Feature Request #2  **

**Is your feature request related to a problem? Please describe.**
Minimize Packages / Categorys

**Describe the solution you'd like**
when i have lots of packages from the same category, and i want to move to other one, i need to scroll down alot..

** Feature Request #3   **

**Is your feature request related to a problem? Please describe.**
when you make a description of catagory or packages,
may you please add more ways to edit?
* Full Screen Feature
* Change Frots
* HEX Color
* Insert Tables
* Emoticons
* Special Characters
* Some Shorcuts
* Option to make it with a code, and option to code view

**Comment by Tim-NL** [comment]
Hi,

For the next time, please only add one request per issue, as we can't keep track this way. 

Request 1: 
Duplicated with #79 

Request 2:
How do you see the interface if it's not a list of packages? I'd suggest using your scroll wheel or the bar on the right side to scroll, as this is faster. 

Request 3:
You can do all those things in the editor already, click the <> button in the toolbar. 

-Tim
