### ISSUE TITLE
Import Buycraft payments

### ISSUE THREAD

**Issue by timhed** [CraftingStore/Suggestions#88]
At this time most minecraft shop owners are using Buycraft/Tebex for reciving donations. Therefore, it would be important to allow Buycraft/Tebex shop owners an easy way to switch to CraftingStore. I think at this time its not possible for everyone to switch. This is also known as [Vendor lock-in](https://en.wikipedia.org/wiki/Vendor_lock-in).
Current way to switch from BuyCraft to CraftingStore: 
1. Shop owners have to create all products newly. 
2. And even more important: They have to create manually all recent payments. Otherwise players would no longer be able to buy upgrade packages and so one.

I think an **"Import" function** would be a great solution. Buycraft itselfs provides an option to export all payments as an excel-sheet, containing all needed information (UUID, username, payment gatway, amount, currency, timestamp, product id, ...)
Therefore you only have to read this data and create...
1. payments with the given information
2. dummy packages with the given product ids of the payements (In order to have a package that is linked to every payment)

Without such a feature most shop owners will not switch to CraftingStore. I can say for myself personally that it is impossible to transfer all payments manually. And a loss of all payments is also unacceptable for the above reasons

Best regards, Tim

**Comment by Tim-NL** [comment]
Hello,
Thank you for the feature request!

I looked into their export feature, and I do get a list of all payments, but I can't link them to any package, as I can't find any way to export those. 

The .csv file contains all the payments, with the package ID's that only Tebex has linked to them. 

How would you implement this feature, or get the packages from their platform? 

-Tim

**Comment by wumptrax** [comment]
Hi! I'm afraid that there is no easy way to get the package information from their platform. Maybe you can get some basic data (name, price, currency) from the target buycraft webstore HTML code: 

![example-shop](https://user-images.githubusercontent.com/39104996/50872010-fe6fd780-13bd-11e9-9e52-b0a5fca8e196.PNG)

_But I think the following implementation would be enough:_
You could just put empty dummy packages with the appropriate id. The shop owners can then simply use the ids to manually edit the empty dummy packages. I think there is no way around it.. This possibility would reduce the effort at least significantly: Users still have to complete the package details, but save the effort with the payments.

I would switch to craftingstore immediately. ;)

Best regards, Tim

**Comment by wumptrax** [comment]
Something new? I just need a simple way to import my payments linked to empty packages with the specific package id. Filling in the package details afterwards is no problem!

**Comment by xion87** [comment]
you can export cvs file with buycraft so a import thing is doable here

**Comment by Tim-NL** [comment]
@xion87 The export only includes payments, not packages, thus we have no way of linking them currently.

**Comment by xion87** [comment]
that is fine, is just copy/paste at end, so the payments are importable right now? (i think the only issue will be like to link the package id to correct one)

**Comment by PulzHF** [comment]
I figured I'd poke a finger at this suggestion, despite its age- just to see if there is any change in CraftingStore's ability to offer such an import feature.

Having processed over $7000 across 503 purchases via Buycraft/Tebex, not being able to easily re-schedule commands when a map is wiped or offering existing customers the ability to use the cumulative feature (and instead relying on a 'buy this and I'll upgrade your purchase manually'), is the only reason I'm on the fence about switching completely to CraftingStore.

**Comment by Golicraft** [comment]
Hey Craftingstore team, I think you guys should really work with implementing this. Processed a lot of rank purchases and if they consider upgrading we need to do it manually as all data will be lost. As @Pulz-TCP said this is the only reason I'm on the fence about switching completely to CraftingStore.

**Comment by Tim-NL** [comment]
Hi,

We created the importer that can import from a .csv file (that you can export at Tebex).
The .csv file only contains package ID's. No commands, or anything like it. So when you import your payments, it will allow you to "map" these package IDs to packages at CraftingStore. Or create a new package (the package will get the ID as its name, so you can change it later).

-Tim
