### ISSUE TITLE
Sale Command

### ISSUE THREAD

**Issue by ChiefJava** [CraftingStore/Suggestions#89]
**Is your feature request related to a problem? Please describe.**
Command on sale, so when a player buy bulk items, i can run command from the sale
to say "thanks {player} for using our sale" something like this

**Describe the solution you'd like**
sale command

**Comment by Tim-NL** [comment]
Hi,

After looking into this, we've decided to decline the feature request. The main reason being that this is something that will be very hard to configure on the store.

-Tim
