### ISSUE TITLE
Giftcard Balance Module

### ISSUE THREAD

**Issue by ChiefJava** [CraftingStore/Suggestions#93]
**Is your feature request related to a problem? Please describe.**
add Giftcard Balance Module
**Describe the solution you'd like**
Check your giftcard balance

**Comment by yBaaaNG** [comment]
Nice suggestion.
**^^ Bump ^^**

**Comment by Tim-NL** [comment]
Hello,

The gift-card module has been implemented. If you are using any custom template, you need to adjust it with the changes; https://github.com/CraftingStore/Templates

-Tim
