### ISSUE TITLE
Random Coupon Generator

### ISSUE THREAD

**Issue by LoJoSho** [CraftingStore/Suggestions#94]
**Is your feature request related to a problem? Please describe.**

Sometimes, I just need a random coupon to give out to a certain player. I want a way for it to randomly generate a code.

**Describe the solution you'd like**

A button next to or below a coupon name that says, "Randomize" which gives a 4-4-6 character code (Ex. 42X0-2YX3-9UT52Y) to the name of the coupon. The Characters that will be used will be all letters (uppercase) and all numbers.

**Additional context**

Not really, just something that would be a nice extra feature :D

**Comment by Tim-NL** [comment]
Hello,
The feature has been implemented. Click the "refresh" icon after the name input to generate the random coupon.

-Tim
