### ISSUE TITLE
User limit on coupons

### ISSUE THREAD

**Issue by LiamBinLaden** [CraftingStore/Suggestions#95]
**Is your feature request related to a problem? Please describe.**
I would like to be able to set user limits on coupons - it'll help with promotional offers

**Describe the solution you'd like**
A user limit on coupons & an expiry time of the limit

**Additional context**
I'm sure this is quite self explanatory

**Comment by ronc617** [comment]
I have to agree with this one. It would be nice to be able to create a giftcard with a balance on it 
and have it so that they could use it to claim say $10.00 but have it limited to 1 per minecraft username

**Comment by TheMonDon** [comment]
I also am on board with this, sounds like an awesome idea

**Comment by Tim-NL** [comment]
Hi,

We'll decline this feature request, because gift-cards have been created to cover for this. Gift-cards have a fixed amount that one specific user can use. 

-Tim
