### ISSUE TITLE
Referral system (optional)

### ISSUE THREAD

**Issue by LiamBinLaden** [CraftingStore/Suggestions#97]
A sophisticated referral system which can be enabled or disabled at checkout. Much like the giftcard entry, you will put in a referral code (which users can generate). Users will have a giftcard linked to the referral code, viewable on the referral system which can be used to purchase items on stores. You are able to customise how much is given to giftcards, i.e. an option to make a percentage of what the user paid, or a set amount.
The admin panel will also be able to track how many referrals players have made.
There could also be an option for a 'boost referral' which is where the player will receive a different or boosted reward to the original when a player uses their referral code the first time round.

**Comment by TheMonDon** [comment]
I'm not sure how easy this would be to implement for them but this sounds like a really cool feature.

**Comment by Tim-NL** [comment]
We have implemented a "basic version" of a referral system for our higher premium plans. This allows a user to enter a referee. You can configure what commands should be executed when they refer someone to your store.

-Tim
