### ISSUE TITLE
gift card / username limit

### ISSUE THREAD

**Issue by ronc617** [CraftingStore/Suggestions#98]
It would be nice to be able to create a giftcard with a balance on it
and have it so that they could use it to claim say $10.00 
but have it limited to 1 per minecraft username

So basically looking to be able to create a gift card / coupon with a balance on it.
and be able to set it so only 1 use per minecraft name
and be able to set the amount that it can be used for

**Comment by Tim-NL** [comment]
Duplicate with #95
