### ISSUE TITLE
1.8.8 Join Error

### ISSUE THREAD

**Issue by Emile2250** [CraftingStore/Suggestions#99]
**Describe the bug**
PlayerJoinEvent on 1.8.8 Spigot, makes it unable to login what soever.

**To Reproduce**
1. Load on 1.8.8
2. Login

**Expected behavior**
Me being able to login.

**Screenshots**
https://pastebin.com/FDJV8ttC

**Platform**
MC Plugin

**Comment by thijsa** [comment]
Hello,

Thank you for the bug report.
Can you post a full log of the server since the startup until this error occurred?

Thanks in advance.

**Comment by Tim-NL** [comment]
-- Closed due to inactivity --
